// ============================================================================
// BATCH 1: Xonalar va maydonlar | Inson va sig'im | Ventilyatsiya (Topics 1-55)
// Rasmiy O'zbekiston standartlari (SHNQ 2.08.01-24, SHNQ 2.08.02-19, QMQ 2.04.05-18)
// ============================================================================

const SEED_TOPICS_BATCH1 = [
  // --- 1. Xonalar va maydonlar (1-20) ---
  {
    title: "1 xonali kvartirada umumiy yashash xonasi minimal maydoni",
    slug: "bir-xonali-yashash-xonasi-minimal-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Turar joy xonalari",
    data_type: "norma",
    normative_value: "14",
    unit: "m²",
    building_type: "Ko'p qavatli turar joy binolari",
    room_type: "Yashash xonasi",
    condition: "1 xonali kvartiralar uchun majburiy minimal talab",
    formula: null,
    calculation_example: null,
    practical_note: "Mebel joylashtirish (divan-krovat, shkaf, ish stoli) uchun xona proporsiyasi kamida 3.0 m enida bo'lishi qulay.",
    architect_note: "Tor va uzun rejalashtirishdan qoching (proporsiya 1:1.5 yoki 1:1.8 gacha bo'lishi maqbul).",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.4-band",
    source_table: "3.1-jadval",
    keywords: ["yashash xonasi", "bir xonali", "kvartira", "minimal maydon", "zal", "гостиная"],
    status: "AMALDA",
    order_index: 1
  },
  {
    title: "2 va undan ortiq xonali kvartirada asosiy yotoqxona minimal maydoni",
    slug: "asosiy-yotoqxona-minimal-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Turar joy xonalari",
    data_type: "norma",
    normative_value: "14",
    unit: "m²",
    building_type: "Turar joy binolari",
    room_type: "Asosiy yotoqxona (master bedroom)",
    condition: "2 kishilik oila a'zolari (ota-ona) uchun mo'ljallanganda",
    formula: null,
    calculation_example: null,
    practical_note: "Ikki kishilik karavot (180x200 sm) va ikki tomondan kamida 70 sm o'tish yo'lagi sig'ishi kerak.",
    architect_note: "Eshik ochilganda karavot ustiga to'g'ri kelmasligi va shkaf eshigi ochilishiga to'sqinlik qilmasligi ta'minlansin.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.4-band",
    source_table: null,
    keywords: ["yotoqxona", "master bedroom", "spalnya", " спальня", "ikki kishilik"],
    status: "AMALDA",
    order_index: 2
  },
  {
    title: "1 kishilik ikkinchi yotoqxona (bolalar xonasi) minimal maydoni",
    slug: "bir-kishilik-yotoqxona-bolalar-xonasi-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Turar joy xonalari",
    data_type: "norma",
    normative_value: "10",
    unit: "m²",
    building_type: "Turar joy binolari",
    room_type: "1 kishilik yotoqxona",
    condition: "Bir kishi yashashi uchun ajratilgan alohida yotoqxona",
    formula: null,
    calculation_example: null,
    practical_note: "1 kishilik krovat (90x200 sm), yozuv stoli va kiyim shkafi joylashtiriladi.",
    architect_note: "Deraza stol ustiga tabiiy yorug'lik tushadigan chap tomondan bo'lishi tavsiya etiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.4-band",
    source_table: null,
    keywords: ["bolalar xonasi", "yotoqxona", "1 kishilik", "детская"],
    status: "AMALDA",
    order_index: 3
  },
  {
    title: "Ko'p xonali kvartirada umumiy mehmonxona (zal) minimal maydoni",
    slug: "kop-xonali-mehmonxona-zal-minimal-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Turar joy xonalari",
    data_type: "norma",
    normative_value: "16",
    unit: "m²",
    building_type: "Turar joy binolari",
    room_type: "Umumiy yashash xonasi (mehmonxona)",
    condition: "3 va undan ortiq xonali kvartiralarda",
    formula: null,
    calculation_example: null,
    practical_note: "Mehmonlar va oila a'zolari birgalikda dam olishi, TV zonasi va divan guruhi uchun 18-22 m² optimal hisoblanadi.",
    architect_note: "Xonaning kengligi kamida 3.2 m bo'lishi talab etiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.5-band",
    source_table: null,
    keywords: ["mehmonxona", "zal", "гостиная", "umumiy xona", "katta zal"],
    status: "AMALDA",
    order_index: 4
  },
  {
    title: "Alohida oshxona xonasi minimal maydoni",
    slug: "alohida-oshxona-minimal-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Oshxona va ovqatlanish",
    data_type: "norma",
    normative_value: "8",
    unit: "m²",
    building_type: "Turar joy binolari",
    room_type: "Alohida oshxona",
    condition: "Mustaqil eshigi va derazasi bo'lgan alohida oshxona",
    formula: null,
    calculation_example: null,
    practical_note: "Plita, rakovina, muzlatgich va kichik ovqatlanish stoli (4 kishilik) sig'ishi ta'minlanadi.",
    architect_note: "Oshxona eni kamida 1.9 m bo'lishi qat'iy talab.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.6-band",
    source_table: null,
    keywords: ["oshxona", "kuhnya", "кухня", "minimal maydon", "gaz plita"],
    status: "AMALDA",
    order_index: 5
  },
  {
    title: "Oshxona-nisha (kuhnya-nisha) minimal maydoni va kengligi",
    slug: "oshxona-nisha-minimal-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Oshxona va ovqatlanish",
    data_type: "norma",
    normative_value: "5",
    unit: "m²",
    building_type: "1 va 2 xonali kvartiralar, studiyalar",
    room_type: "Oshxona-nisha",
    condition: "Majburiy mexanik ventilyatsiya va elektr plitasi bo'lgan hollarda",
    formula: null,
    calculation_example: null,
    practical_note: "Faqat elektr plitaga ruxsat beriladi; gaz plitasi bo'lsa alohida xona va deraza shart.",
    architect_note: "Kengligi kamida 1.8-1.9 m bo'lishi lozim.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.6-band",
    source_table: null,
    keywords: ["kuhnya nisha", "studiya", "oshxona nisha", "кухня-ниша"],
    status: "AMALDA",
    order_index: 6
  },
  {
    title: "Kvartira ichki koridori minimal kengligi",
    slug: "kvartira-ichki-koridori-minimal-kengligi",
    category: "Xonalar va maydonlar",
    subcategory: "Yo'laklar va dahlizlar",
    data_type: "norma",
    normative_value: "1.0",
    unit: "m",
    building_type: "Turar joy binolari",
    room_type: "Ichki koridor",
    condition: "Xonalarga olib boruvchi yordamchi koridorlar uchun",
    formula: null,
    calculation_example: null,
    practical_note: "Kirish dahlizi (prixojaya) uchun esa kiyim shkafi bilan birga kamida 1.4 m kenglik qulay.",
    architect_note: "Mebel ko'chirganda qiyinchilik tug'dirmasligi uchun burilish nuqtalarida 1.1-1.2 m saqlash tavsiya etiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.8-band",
    source_table: null,
    keywords: ["koridor", "dahliz", "kenglik", "коридор", "prixojaya"],
    status: "AMALDA",
    order_index: 7
  },
  {
    title: "Turar joy xonalarida toza pol sathidan shiftgacha minimal balandlik",
    slug: "turar-joy-shift-balandligi-minimal",
    category: "Xonalar va maydonlar",
    subcategory: "Vertikal parametrlar",
    data_type: "norma",
    normative_value: "2.5",
    unit: "m",
    building_type: "Iqlimiy IA, IB, IG zonalaridan tashqari barcha turar joylar",
    room_type: "Yashash xonalari va oshxona",
    condition: "Toza pardozlangan pol sathidan toza shift sathigacha",
    formula: null,
    calculation_example: null,
    practical_note: "Monolit orayopma va toza pol stajkasi, gipsokarton/cho'ziluvchan shift yo'qotishlari hisobga olinib, qurilishdagi balandlik 2.80-3.00 m loyihalanadi.",
    architect_note: "O'zbekistonning issiq iqlimida sanitariya qulayligi uchun 2.70-3.00 m tavsiya qilinadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.2-band",
    source_table: null,
    keywords: ["shift balandligi", "balandlik", "toza shift", "высота потолка"],
    status: "AMALDA",
    order_index: 8
  },
  {
    title: "Jamoat binolari va ofislarda minimal shift balandligi",
    slug: "jamoat-binolari-ofis-shift-balandligi",
    category: "Xonalar va maydonlar",
    subcategory: "Jamoat binolari",
    data_type: "norma",
    normative_value: "3.0",
    unit: "m",
    building_type: "Jamoat, ma'muriy va ofis binolari",
    room_type: "Ishchi xonalar, ofislar, qabullar",
    condition: "Oddiy ma'muriy va xizmat xonalarida",
    formula: null,
    calculation_example: null,
    practical_note: "Katta ventilyatsiya havo yo'llari (vozduxovod) shift orqasidan o'tishi sababli qavatlararo oraliq kamida 3.30-3.60 m olinadi.",
    architect_note: "Zallarda (100 kishidan ortiq) shift balandligi akustika va havo hajmiga ko'ra kamida 3.6-4.2 m qilib belgilanadi.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "2.3-band",
    source_table: null,
    keywords: ["ofis", "jamoat binosi", "shift", "balandlik", "офис", "высота"],
    status: "AMALDA",
    order_index: 9
  },
  {
    title: "1 xonali kvartiraning umumiy minimal maydoni",
    slug: "bir-xonali-kvartira-umumiy-minimal-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Kvartira turlari",
    data_type: "norma",
    normative_value: "28",
    unit: "m²",
    building_type: "Ko'p xonadonli uylar",
    room_type: "1 xonali kvartira (umumiy)",
    condition: "Davlat va xususiy shaharsozlik loyihalarida minimal me'yor",
    formula: null,
    calculation_example: null,
    practical_note: "Yashash xonasi (14 m²) + Oshxona (6-8 m²) + Sanuzel (3.5 m²) + Koridor (3.5-4 m²) = 27-30 m².",
    architect_note: "Balkon yoki lodjiya maydoni ushbu umumiy maydonga pasaytirish koeffitsienti bilan qo'shiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.3-band",
    source_table: "3.1-jadval",
    keywords: ["1 xonali", "kvartira", "minimal umumiy", "odnushka", "1-комнатная"],
    status: "AMALDA",
    order_index: 10
  },
  {
    title: "2 xonali kvartiraning umumiy minimal maydoni",
    slug: "ikki-xonali-kvartira-umumiy-minimal-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Kvartira turlari",
    data_type: "norma",
    normative_value: "44",
    unit: "m²",
    building_type: "Ko'p xonadonli uylar",
    room_type: "2 xonali kvartira (umumiy)",
    condition: "Standart ijtimoiy va tijorat kvartiralari",
    formula: null,
    calculation_example: null,
    practical_note: "Zal (16 m²) + Yotoqxona (10 m²) + Oshxona (8 m²) + Sanuzel (4 m²) + Koridor (6 m²) = 44 m².",
    architect_note: "2 xonali kvartirada sanuzelni alohida (vanna va hojatxona) qilish tavsiya etiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.3-band",
    source_table: "3.1-jadval",
    keywords: ["2 xonali", "kvartira maydoni", "двушка", "2-комнатная"],
    status: "AMALDA",
    order_index: 11
  },
  {
    title: "3 xonali kvartiraning umumiy minimal maydoni",
    slug: "uch-xonali-kvartira-umumiy-minimal-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Kvartira turlari",
    data_type: "norma",
    normative_value: "56",
    unit: "m²",
    building_type: "Ko'p xonadonli uylar",
    room_type: "3 xonali kvartira (umumiy)",
    condition: "Standart loyihalash normasi",
    formula: null,
    calculation_example: null,
    practical_note: "Zal (16-18 m²) + 2 ta yotoqxona (14+10 m²) + Oshxona (8-9 m²) + Sanuzellar (5 m²) + Koridorlar (8 m²) = 60-65 m² qulay variant hisoblanadi.",
    architect_note: "O'zbekistonda 3 xonali kvartiralar uchun mehmonlar va oila a'zolari sanuzelini ajratish talab qilinadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.3-band",
    source_table: "3.1-jadval",
    keywords: ["3 xonali", "kvartira", "treshka", "3-комнатная"],
    status: "AMALDA",
    order_index: 12
  },
  {
    title: "Ofis xonasida 1 nafar xodim uchun minimal ish maydoni",
    slug: "ofis-bir-xodim-ish-maydoni-normasi",
    category: "Xonalar va maydonlar",
    subcategory: "Ofis va ma'muriy",
    data_type: "norma",
    normative_value: "4.5",
    unit: "m²/kishi",
    building_type: "Ofislar, biznes markazlar, ma'muriy binolar",
    room_type: "Umumiy ish zali (Open space)",
    condition: "Kompyuter (shaxsiy monitor) bilan ishlovchi xodimlar uchun",
    formula: null,
    calculation_example: "10 kishilik bo'lim uchun: 10 kishi × 4.5 m² = kamida 45 m² toza maydon (yo'laklar bilan 50-55 m²).",
    practical_note: "Zamonaviy ergonomikada 6.0 m²/kishi optimal hisoblanadi; 4.5 m² esa qonuniy eng quyi chegara.",
    architect_note: "Monitorga quyosh nuri to'g'ridan-to'g'ri tushmasligi va konditsioner shamoli to'g'ri kelmasligi zonalashtirishda e'tiborga olinadi.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "3.14-band",
    source_table: null,
    keywords: ["ofis", "xodim maydoni", "open space", "ish o'rni", "рабочее место"],
    status: "AMALDA",
    order_index: 13
  },
  {
    title: "Kompaniya rahbari xonasi (kabinet) minimal maydoni",
    slug: "rahbar-xonasi-kabinet-minimal-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Ofis va ma'muriy",
    data_type: "tavsiya",
    normative_value: "12 - 15",
    unit: "m²",
    building_type: "Ofis va ma'muriy binolar",
    room_type: "Rahbar kabineti",
    condition: "Yakka rahbar va 3-4 kishilik kichik majlis stoli bilan",
    formula: null,
    calculation_example: null,
    practical_note: "Katta tashkilotlarda yordamchi qabulxona (resepshn - 8-10 m²) va ichki sanuzel (3 m²) bilan birga 24-30 m² loyihalanadi.",
    architect_note: "Ovoz izolyatsiyasi (kamida 50 dB) va xavfsiz evakuatsiya yo'li ta'minlanishi shart.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "Ilova 4",
    source_table: null,
    keywords: ["kabinet", "rahbar xonasi", "ofis", "директор", "кабинет"],
    status: "AMALDA",
    order_index: 14
  },
  {
    title: "Mehmonxona 1 o'rinli xonasi (Single room) minimal maydoni",
    slug: "mehmonxona-bir-orinli-xona-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Mehmonxona va turizm",
    data_type: "norma",
    normative_value: "12",
    unit: "m²",
    building_type: "Mehmonxonalar, motellar (3* va undan yuqori)",
    room_type: "1 o'rinli yotoq xonasi (sanuzelsiz toza xona)",
    condition: "Sanuzel va kirish tamburi maydoni hisobga olinmaganda",
    formula: null,
    calculation_example: null,
    practical_note: "Sanuzel (kamida 3.5 m²) va tambur (2.5 m²) bilan birga umumiy xona bloki 18 m² dan kam bo'lmaydi.",
    architect_note: "3-4 yulduzli standartlarda mebel, mini-bar, kiyim shkafi va ish stoli ergonomik masofasi tekshiriladi.",
    source_document_number: "SHNQ 2.08.06-18",
    source_band: "4.2-band",
    source_table: "4.1-jadval",
    keywords: ["mehmonxona", "hotel", "single room", "1 o'rinli", "гостиница"],
    status: "AMALDA",
    order_index: 15
  },
  {
    title: "Mehmonxona 2 o'rinli xonasi (Double / Twin) minimal maydoni",
    slug: "mehmonxona-ikki-orinli-xona-maydoni",
    category: "Xonalar va maydonlar",
    subcategory: "Mehmonxona va turizm",
    data_type: "norma",
    normative_value: "16",
    unit: "m²",
    building_type: "Mehmonxonalar",
    room_type: "2 o'rinli xona",
    condition: "Ikki krovat yoki bitta katta double krovat uchun",
    formula: null,
    calculation_example: null,
    practical_note: "Sanuzel (4 m²) va kirish zonasi bilan birga xona umumiy maydoni 22-25 m² ni tashkil etadi.",
    architect_note: "Krovatlar oralig'ida kamida 80 sm o'tish masofasi qoldirilishi shart.",
    source_document_number: "SHNQ 2.08.06-18",
    source_band: "4.2-band",
    source_table: "4.1-jadval",
    keywords: ["mehmonxona", "double room", "twin", "гостиница 2-местная"],
    status: "AMALDA",
    order_index: 16
  },
  {
    title: "Restoran mehmonlar zalida 1 o'ringa ajratiladigan maydon",
    slug: "restoran-zali-bir-mehmonga-maydon",
    category: "Xonalar va maydonlar",
    subcategory: "Umumiy ovqatlanish",
    data_type: "norma",
    normative_value: "1.8 - 2.0",
    unit: "m²/o'rin",
    building_type: "Restoranlar",
    room_type: "Mehmonlar ovqatlanish zali",
    condition: "Estradasiz va raqs maydonchasisiz restoran zali",
    formula: "S_zal = N_orin × 1.8 m²",
    calculation_example: "100 o'rinli restoran uchun zal toza maydoni: 100 × 1.8 = kamida 180 m² (raqs maydonchasi bilan 220 m²).",
    practical_note: "Stollar orasidagi asosiy o'tish yo'lagi kamida 1.5 m, qatorlar oralig'i 1.0 m bo'lishi talab qilinadi.",
    architect_note: "Ofitsiantlar harakati va yong'in evakuatsiyasi hisobida o'tish yo'laklari to'silmasligi shart.",
    source_document_number: "SHNQ 2.08.03-12",
    source_band: "3.2-band",
    source_table: "3.1-jadval",
    keywords: ["restoran", "kafe", "zal maydoni", "sig'im", "ресторан", "посадочное место"],
    status: "AMALDA",
    order_index: 17
  },
  {
    title: "Kafe va tez ovqatlanish maskanida 1 o'ringa maydon",
    slug: "kafe-bir-mehmonga-ajratiladigan-maydon",
    category: "Xonalar va maydonlar",
    subcategory: "Umumiy ovqatlanish",
    data_type: "norma",
    normative_value: "1.4 - 1.6",
    unit: "m²/o'rin",
    building_type: "Kafe, bar, bistro, pitsaxona",
    room_type: "Kafe zali",
    condition: "O'z-o'ziga xizmat ko'rsatish yoki ofitsiantli kafe",
    formula: null,
    calculation_example: "50 o'rinli kafe uchun: 50 × 1.4 = kamida 70 m² zal maydoni.",
    practical_note: "Bistro va kofeynyalarda ixcham mebel hisobiga 1.3-1.4 m² gacha zichlashtirish mumkin.",
    architect_note: "Kassa/tarqatish zonasi oldida to'planish maydonchasi (kamida 6-8 m²) qoldirilishi lozim.",
    source_document_number: "SHNQ 2.08.03-12",
    source_band: "3.2-band",
    source_table: "3.1-jadval",
    keywords: ["kafe", "kafe zali", "bistro", "kofeynya", "кафе"],
    status: "AMALDA",
    order_index: 18
  },
  {
    title: "Podval va texnik qavatlarda odam yuradigan yo'lak balandligi",
    slug: "podval-texnik-qavat-yolagi-balandligi",
    category: "Xonalar va maydonlar",
    subcategory: "Yordamchi va texnik xonalar",
    data_type: "norma",
    normative_value: "1.8",
    unit: "m",
    building_type: "Barcha bino turlari",
    room_type: "Texnik yerosti qavati, texnik qavat, podval",
    condition: "Odamlar muntazam o'tadigan xizmat yo'laklarining toza bo'shlig'i",
    formula: null,
    calculation_example: null,
    practical_note: "Quvurlar va osma kabellar ostidan toza polgacha bo'lgan masofa o'lchanadi.",
    architect_note: "Trassalarni rejalashtirishda muhandislik quvurlari o'tish yo'laklarining ustida qolib ketmasligini ta'minlang.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.10-band",
    source_table: null,
    keywords: ["podval", "texnik qavat", "balandlik", "подвал", "высота"],
    status: "AMALDA",
    order_index: 19
  },
  {
    title: "Mansarda qavatida qiya shiftning eng past nuqtasi balandligi",
    slug: "mansarda-qiya-shift-eng-past-nuqtasi",
    category: "Xonalar va maydonlar",
    subcategory: "Vertikal parametrlar",
    data_type: "norma",
    normative_value: "1.6",
    unit: "m",
    building_type: "Mansardali turar joy binolari",
    room_type: "Mansarda yashash xonasi",
    condition: "Shift qiyaligi 30° gacha bo'lganda (qiyalik 45° bo'lsa 1.9 m)",
    formula: null,
    calculation_example: null,
    practical_note: "1.6 metrdan past bo'lgan maydonlar mebel joylashtirish (shkafcha, javon) yoki yordamchi saqlash zonasi sifatida ishlatiladi.",
    architect_note: "Mansarda xonasi umumiy maydonini hisoblashda 1.6 m dan past qismiga 0.7 yoki 0 koeffitsient qo'llaniladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.2-band",
    source_table: null,
    keywords: ["mansarda", "qiya shift", "cherdak", "мансарда"],
    status: "AMALDA",
    order_index: 20
  },

  // --- 2. Inson va sig'im me'yorlari (21-38) ---
  {
    title: "1 kishiga to'g'ri keladigan minimal ijtimoiy yashash maydoni",
    slug: "bir-kishiga-minimal-yashash-maydoni-ijtimoiy",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Turar joy sanitariya me'yorlari",
    data_type: "norma",
    normative_value: "9 - 12",
    unit: "m²/kishi",
    building_type: "Ijtimoiy turar joylar, yotoqxonalar",
    room_type: "Yashash xonasi",
    condition: "Sanitariya qoidalariga binoan eng kam ruxsat etilgan me'yor",
    formula: null,
    calculation_example: "4 kishilik oila uchun toza yashash maydoni kamida 4 × 9 = 36 m² (umumiy maydon esa kamida 56 m²).",
    practical_note: "O'zbekiston uy-joy kodeksiga binoan ijtimoiy ijara uylari uchun kishi boshiga 16 m² umumiy maydon belgilangan.",
    architect_note: "Yotoqxona tipidagi binolarda 1 kishiga kamida 6 m² yashash maydoni ko'zda tutiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "2.5-band",
    source_table: null,
    keywords: ["sanitariya normasi", "kishi boshiga", "ijtimoiy norma", "жилая площадь на человека"],
    status: "AMALDA",
    order_index: 21
  },
  {
    title: "1 nafar inson uchun gigiyenik toza havo hajmi normasi",
    slug: "bir-insonga-toza-havo-hajmi-normasi",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Mikroklimat va sanitariya",
    data_type: "norma",
    normative_value: "30",
    unit: "m³/soat/kishi",
    building_type: "Turar joy va jamoat binolari",
    room_type: "Barcha xonalar",
    condition: "Xonada tabiiy shamollatish bilan kishi doimiy bo'lganda (2 soatdan ortiq)",
    formula: "L_havo = N_odam × 30 m³/soat",
    calculation_example: "3 kishilik yotoqxona uchun: 3 × 30 = 90 m³/soat toza havo oqimi zarur.",
    practical_note: "Xonada tabiiy oyna ochish imkoni bo'lmaganda yoki jamoat binolarida bu norma 40-60 m³/soat/kishigacha ko'tariladi.",
    architect_note: "Ventilyatsiya shaxtalari va klapanlar o'tkazuvchanligi shu formulaga asosan hisoblanadi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.12-band",
    source_table: "4.1-jadval",
    keywords: ["havo normasi", "toza havo", "kishi boshiga havo", "воздухообмен"],
    status: "AMALDA",
    order_index: 22
  },
  {
    title: "Yig'ilish va konferens-zallarida 1 o'ringa ajratiladigan maydon",
    slug: "yigilish-konferens-zal-bir-oringa-maydon",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Jamoat zallari",
    data_type: "norma",
    normative_value: "0.65 - 0.8",
    unit: "m²/o'rin",
    building_type: "Ma'muriy binolar, biznes markazlar",
    room_type: "Majlislar zali, konferens-zal",
    condition: "Qator qilib o'rnatilgan stullar (parter) bilan",
    formula: "S = N_orin × 0.7 m²",
    calculation_example: "200 kishilik majlis zali: 200 × 0.7 = 140 m² (sahna va orqa yo'laklarsiz).",
    practical_note: "Stol bilan ta'minlangan o'quv/konferens zalida bu norma 1.2 - 1.5 m²/o'ringacha oshadi.",
    architect_note: "Qatorlar orasidagi masofa kamida 45 sm, o'tish yo'lagi kengligi kamida 1.0 m bo'lishi shart.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "3.22-band",
    source_table: null,
    keywords: ["konferens zal", "majlis zali", "sig'im", "o'rin", "конференц-зал"],
    status: "AMALDA",
    order_index: 23
  },
  {
    title: "Kinoteatr va teatr tomosha zalida 1 tomoshabinga maydon",
    slug: "tomosha-zali-bir-tomoshabinga-maydon",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Madaniy binolar",
    data_type: "norma",
    normative_value: "0.7 - 0.9",
    unit: "m²/o'rin",
    building_type: "Kinoteatr, teatr, konsert zallari",
    room_type: "Tomosha zali (parter)",
    condition: "Ruxsat etilgan qator oralig'i 0.9 m bo'lganda",
    formula: null,
    calculation_example: "300 o'rinli kinoteatr zali: 300 × 0.8 = 240 m².",
    practical_note: "Akustik qoplama va ekrangacha bo'lgan minimal masofa (ekran balandligining 1.5 baravari) saqlanadi.",
    architect_note: "Yong'in evakuatsiyasi uchun bir qatorda maksimal 26 ta stul (ikki tomonga chiqish bo'lsa) qo'yilishi mumkin.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "3.25-band",
    source_table: null,
    keywords: ["kinoteatr", "teatr", "tomosha zali", "кинотеатр", "зрительный зал"],
    status: "AMALDA",
    order_index: 24
  },
  {
    title: "Sport trenajyor zalida 1 kishiga ajratiladigan minimal maydon",
    slug: "trenajyor-sport-zali-bir-kishiga-maydon",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Sport inshootlari",
    data_type: "norma",
    normative_value: "4.0 - 5.0",
    unit: "m²/kishi",
    building_type: "Fitnes klublar, sport zallari",
    room_type: "Trenajyor zali (kuch va kardiomashq)",
    condition: "Bir vaqtning o'zida shug'ullanuvchilar soni bo'yicha",
    formula: "S = N_shugullanuvchi × 4.5 m²",
    calculation_example: "Bir vaqtda 30 kishi shug'ullanadigan trenajyor zali: 30 × 4.5 = kamida 135 m².",
    practical_note: "Trenajyorlar orasidagi xavfsiz o'tish va himoya masofasi kamida 0.8-1.0 m bo'lishi kerak.",
    architect_note: "Shift balandligi kamida 3.3 m, ventilyatsiya 60-80 m³/soat/kishi qilib olinadi.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "3.40-band",
    source_table: null,
    keywords: ["sport zali", "fitnes", "trenajyor", "фитнес", "тренажерный зал"],
    status: "AMALDA",
    order_index: 25
  },
  {
    title: "Bolalar bog'chasi guruh xonasida (o'yin xonasi) 1 bolaga maydon",
    slug: "bogcha-oyinxona-bir-bolaga-maydon-normasi",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Maktabgacha ta'lim",
    data_type: "norma",
    normative_value: "2.5",
    unit: "m²/bola",
    building_type: "Maktabgacha ta'lim tashkilotlari (bog'chalar)",
    room_type: "Guruh o'yin xonasi (igrovaya)",
    condition: "Yasli guruhlarida kamida 2.5 m², bog'cha guruhlarida kamida 2.0 m²",
    formula: "S = N_bola × 2.5 m²",
    calculation_example: "20 bolalik guruh uchun o'yin xonasi: 20 × 2.5 = kamida 50 m².",
    practical_note: "Yotoqxona (spalnya) alohida bo'lsa, u yerda ham 1 bolaga kamida 2.0 m² maydon zarur.",
    architect_note: "Tabiiy yoritilganlik KEO koeffitsienti kamida 1.5% bo'lishi qat'iy talab qilinadi.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "3.5-band",
    source_table: "3.2-jadval",
    keywords: ["bog'cha", "bolalar bog'chasi", "maktabgacha", "детский сад"],
    status: "AMALDA",
    order_index: 26
  },
  {
    title: "Umumta'lim maktabi sinfxonasida 1 o'quvchiga ajratiladigan maydon",
    slug: "maktab-sinfxona-bir-oquvchiga-maydon-normasi",
    category: "Inson va sig'im me'yorlari",
    subcategory: "O'quv muassasalari",
    data_type: "norma",
    normative_value: "2.0 - 2.5",
    unit: "m²/o'quvchi",
    building_type: "Maktablar, litseylar, kollejlar",
    room_type: "Standart sinf xonasi (auditoriya)",
    condition: "Old tomondan orqaga qator partalar joylashtirilganda",
    formula: "S = N_oquvchi × 2.0 m²",
    calculation_example: "30 o'quvchilik sinf xonasi: 30 × 2.0 = kamida 60 m² (o'qituvchi stoli va doska zonasi bilan).",
    practical_note: "Doska va birinchi partalar qatori orasidagi masofa kamida 2.4-2.7 m bo'lishi shart.",
    architect_note: "Tabiiy yorug'lik faqat chap tomondan tushishi kerak (o'quvchining o'ng qo'li soya qilmasligi uchun).",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "3.10-band",
    source_table: null,
    keywords: ["maktab", "sinfxona", "parta", "auditoriya", "школа", "класс"],
    status: "AMALDA",
    order_index: 27
  },
  {
    title: "Kutubxona o'quv zalida 1 o'quvchi o'rniga maydon",
    slug: "kutubxona-oquv-zali-bir-oringa-maydon",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Ta'lim va madaniyat",
    data_type: "norma",
    normative_value: "2.4 - 3.0",
    unit: "m²/o'rin",
    building_type: "Kutubxonalar, oliygohlar",
    room_type: "O'qish zali",
    condition: "Yakka o'qish stoli yoki kompyuterli joy bilan",
    formula: null,
    calculation_example: "50 o'rinli kutubxona o'quv zali: 50 × 2.4 = 120 m².",
    practical_note: "O'quvchilar bir-biriga xalaqit bermasligi uchun qatorlar orasi kamida 1.2 m bo'ladi.",
    architect_note: "Tabiiy yorug'lik va shovqindan himoya (akustika < 40 dB) muhim ko'rsatkichdir.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "3.18-band",
    source_table: null,
    keywords: ["kutubxona", "o'quv zali", "kitobxona", "библиотека"],
    status: "AMALDA",
    order_index: 28
  },
  {
    title: "Ko'p qavatli turar joy binosi yo'lovchi lifti minimal yuk ko'tarish sig'imi",
    slug: "turar-joy-lift-yuk-kotarish-sigimi",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Vertikal transport",
    data_type: "norma",
    normative_value: "400",
    unit: "kg (5 kishi)",
    building_type: "Ko'p qavatli turar joy binolari (6 qavat va undan baland)",
    room_type: "Lift shaxtasi va kabinasi",
    condition: "Kichik yo'lovchi lifti uchun minimal chegara",
    formula: null,
    calculation_example: null,
    practical_note: "Zamonaviy ko'p qavatli uylarda mebel va zambil (nosilka) sig'ishi uchun kamida bitta 1000 kg (yoki 630 kg) yuk-yo'lovchi lifti o'rnatilishi shart.",
    architect_note: "10 qavatdan baland binolarda kamida 2 ta lift (biri yuk-yo'lovchi 1000 kg) talab qilinadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.15-band",
    source_table: "3.4-jadval",
    keywords: ["lift", "yo'lovchi lifti", "yuk lifti", "lift sig'imi", "лифт"],
    status: "AMALDA",
    order_index: 29
  },
  {
    title: "Jamoat binolarida nogironlar aravachasi sig'adigan lift sig'imi",
    slug: "nogironlar-aravachasi-uchun-lift-sigimi",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Inklyuzivlik va transport",
    data_type: "norma",
    normative_value: "630 - 1000",
    unit: "kg",
    building_type: "Jamoat, tibbiyot, savdo va turar joy binolari",
    room_type: "Universal lift kabinasi",
    condition: "Nogironlar aravachasi va hamrohlik qiluvchi shaxs uchun",
    formula: null,
    calculation_example: null,
    practical_note: "Kabina o'lchami kamida 1100×1400 mm, eshik kengligi kamida 900 mm bo'lishi majburiydir.",
    architect_note: "Tugmalar paneli 900-1100 mm balandlikda va Brayl alifbosi bilan ta'minlanishi shart.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "4.3-band",
    source_table: null,
    keywords: ["nogironlar lifti", "inklyuziv lift", "kabina o'lchami", "лифт для инвалидов"],
    status: "AMALDA",
    order_index: 30
  },
  {
    title: "Xonadan evakuatsiya chiqish eshigi minimal kengligi",
    slug: "xonadan-evakuatsiya-chiqish-eshigi-kengligi",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Yong'in evakuatsiyasi",
    data_type: "norma",
    normative_value: "0.8",
    unit: "m",
    building_type: "Barcha bino turlari",
    room_type: "Xonadan chiqish eshigi",
    condition: "Xonada 15 kishigacha bo'lganda",
    formula: null,
    calculation_example: null,
    practical_note: "Xonada 15 kishidan ortiq bo'lsa yoki nogironlar harakatlanadigan yo'llarda minimal eshik toza kengligi 0.9 m bo'ladi.",
    architect_note: "Eshik qanoti (polotno) 90° ochilganda toza o'tish teshigi 800 mm dan kam bo'lmasligi lozim (quti hisoblanmaydi).",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.2-band",
    source_table: null,
    keywords: ["evakuatsiya", "eshik kengligi", "chiqish eshigi", "эвакуационный выход"],
    status: "AMALDA",
    order_index: 31
  },
  {
    title: "Umumiy bino evakuatsiya yo'lagi (koridor) minimal toza kengligi",
    slug: "umumiy-bino-evakuatsiya-koridori-minimal-kengligi",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Yong'in evakuatsiyasi",
    data_type: "norma",
    normative_value: "1.2",
    unit: "m",
    building_type: "Turar joy va jamoat binolari",
    room_type: "Umumiy koridor",
    condition: "50 kishigacha bo'lgan yo'nalish bo'yicha evakuatsiya qilinganda",
    formula: null,
    calculation_example: null,
    practical_note: "50 kishidan ortiq odam evakuatsiya qilinadigan koridorlar kengligi kamida 1.5 m, maktab va shifoxonalarda 1.8-2.2 m bo'lishi shart.",
    architect_note: "Koridorga ochiladigan xona eshiklari koridor toza o'tish kengligini me'yordan kamaytirib qo'ymasligi lozim.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.5-band",
    source_table: null,
    keywords: ["evakuatsiya koridori", "koridor kengligi", "yo'lak", "эвакуационный коридор"],
    status: "AMALDA",
    order_index: 32
  },
  {
    title: "Evakuatsiya chiqish eshiklarining toza minimal balandligi",
    slug: "evakuatsiya-chiqish-eshigi-minimal-balandligi",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Yong'in evakuatsiyasi",
    data_type: "norma",
    normative_value: "1.9",
    unit: "m",
    building_type: "Barcha bino turlari",
    room_type: "Evakuatsiya yo'lidagi barcha eshiklar",
    condition: "Toza pol sathidan eshik qutisining yuqori chekkasigacha",
    formula: null,
    calculation_example: null,
    practical_note: "Standart loyihalashda qulaylik uchun 2.00 yoki 2.10 m balandlikdagi eshik bloklari qo'llaniladi.",
    architect_note: "Texnik qavatlar va xizmat chiqishlarida favqulodda holat uchun 1.9 m ruxsat beriladi.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.3-band",
    source_table: null,
    keywords: ["eshik balandligi", "evakuatsiya", "toza balandlik", "высота двери"],
    status: "AMALDA",
    order_index: 33
  },
  {
    title: "Xona sig'imi 50 kishigacha bo'lganda talab qilinadigan evakuatsiya chiqishi",
    slug: "xona-sigimi-50-kishigacha-chiqish-soni",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Yong'in evakuatsiyasi",
    data_type: "norma",
    normative_value: "1",
    unit: "ta chiqish",
    building_type: "Barcha binolar",
    room_type: "Ofis, sinf, kichik zal",
    condition: "Xona maydoni va odamlar soni 50 kishidan oshmaganda (1-qavatda)",
    formula: null,
    calculation_example: null,
    practical_note: "Agar xona 2-qavat yoki undan yuqorida bo'lsa, xonadan chiqish yo'lakka tutashishi va yo'lakdan 2 ta mustaqil zinapoyaga yo'l bo'lishi kerak.",
    architect_note: "Eshik tashqariga (chiqish yo'nalishi tomon) ochilishi shart.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.8-band",
    source_table: null,
    keywords: ["evakuatsiya chiqishi", "chiqishlar soni", "50 kishi", "эвакуационный выход"],
    status: "AMALDA",
    order_index: 34
  },
  {
    title: "Xona sig'imi 50 kishidan ortiq bo'lganda majburiy evakuatsiya chiqishlari soni",
    slug: "xona-sigimi-50-kishidan-ortiq-chiqish-soni",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Yong'in evakuatsiyasi",
    data_type: "norma",
    normative_value: "kamida 2",
    unit: "ta mustaqil chiqish",
    building_type: "Jamoat, madaniy, savdo va ishlab chiqarish binolari",
    room_type: "Zallar, restoranlar, majlis xonalari",
    condition: "50 nafardan ortiq odam bir vaqtda to'planadigan barcha xonalar",
    formula: null,
    calculation_example: "120 kishilik restoran zali uchun xonaning bir-biriga qarama-qarshi tomonlarida kamida 2 ta alohida evakuatsiya eshigi bo'lishi shart.",
    practical_note: "Chiqishlar bir-biridan maksimal masofada (zal diagonali yarmidan kam bo'lmagan masofada) joylashishi shart.",
    architect_note: "Eshiklar orasidagi masofa L >= D/2 (D - xona maksimal diagonali). Biri to'silsa, ikkinchisi ochiq qolishi kafolatlanadi.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.9-band",
    source_table: null,
    keywords: ["2 ta chiqish", "zal evakuatsiyasi", "yong'in xavfsizligi", "два выхода"],
    status: "AMALDA",
    order_index: 35
  },
  {
    title: "Zal sig'imi 500 kishidan ortiq bo'lganda evakuatsiya chiqishlari soni",
    slug: "katta-zal-sigimi-500-kishidan-ortiq-chiqish-soni",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Yong'in evakuatsiyasi",
    data_type: "norma",
    normative_value: "kamida 3 - 4",
    unit: "ta chiqish",
    building_type: "Katta teatrlar, konsert zallari, stadionlar, ko'rgazma zallari",
    room_type: "Tomosha va sport zallari",
    condition: "500 dan 1000 kishigacha bo'lgan sig'imda",
    formula: null,
    calculation_example: "800 kishilik konsert zali uchun har bir chiqish kamida 1.5 m kenglikda bo'lgan 4 ta chiqish loyihalanadi.",
    practical_note: "Umumiy evakuatsiya vaqti hisob-kitob (raschet) bilan tasdiqlanishi lozim (odatda 2-3 daqiqadan oshmasligi kerak).",
    architect_note: "Chiqish eshiklari 'Antipanika' (Push-bar) tutqichlari bilan jihozlanishi majburiy.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.10-band",
    source_table: null,
    keywords: ["katta zal", "antipanika", "evakuatsiya eshigi", "эвакуация зала"],
    status: "AMALDA",
    order_index: 36
  },
  {
    title: "1 dona yengil avtomobil uchun ochiq to'xtash joyi (parking) o'lchami",
    slug: "yengil-avtomobil-parking-orindiq-olchami",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Avtoturargohlar",
    data_type: "norma",
    normative_value: "2.5 × 5.3",
    unit: "m (13.25 m²)",
    building_type: "Turar joy hovlilari, jamoat binolari atrofidagi parkovkalar",
    room_type: "Ochiq avtoturargoh o'rni",
    condition: "Standart yengil avtomobillar uchun minimal toza chiziq o'lchami",
    formula: null,
    calculation_example: "10 ta mashina uchun perpendikulyar qo'yilganda: 25 metr front + orqaga burilish yo'li kamida 6.0 metr.",
    practical_note: "Nogironlar avtotransporti uchun o'rin kengligi kamida 3.5 m (aravacha eshik yonidan bemalol o'tishi uchun) bo'lishi shart.",
    architect_note: "Ikki tomonlama parkovka orasidagi harakatlanish yo'lagi kamida 6.0 m qilib loyihalanadi.",
    source_document_number: "SHNQ 2.07.01-03*",
    source_band: "6.35-band",
    source_table: null,
    keywords: ["avtoturargoh", "parkovka", "mashina joyi", "парковка", "машиноместо"],
    status: "AMALDA",
    order_index: 37
  },
  {
    title: "1 dona velosiped uchun to'xtash joyi (veloparkovka) o'lchami",
    slug: "veloparkovka-bir-velosiped-olchami",
    category: "Inson va sig'im me'yorlari",
    subcategory: "Avtoturargohlar",
    data_type: "tavsiya",
    normative_value: "0.6 × 2.0",
    unit: "m (1.2 m²)",
    building_type: "Barcha jamoat, ofis va turar joy binolari oldi",
    room_type: "Velosiped to'xtash joyi",
    condition: "Maxsus metall konstruktsiyali velostandartda",
    formula: null,
    calculation_example: "10 ta velosiped uchun maydoncha: uzunligi 6-7 metr, chuqurligi 2 metr.",
    practical_note: "Velosiped ushlagichlar orasi kamida 60-70 sm bo'lsa rullar bir-biriga tegib tirnalmaydi.",
    architect_note: "Yomg'ir va quyoshdan saqlovchi yengil bostirma (naves) va kuzatuv kamerasi ostida bo'lishi tavsiya etiladi.",
    source_document_number: "SHNQ 2.07.01-03*",
    source_band: "6.38-band",
    source_table: null,
    keywords: ["veloparkovka", "velosiped joyi", "velo", "велопарковка"],
    status: "AMALDA",
    order_index: 38
  },

  // --- 3. Ventilyatsiya va havo almashinuvi (39-55) ---
  {
    title: "Turar joy yashash xonalariga tabiiy toza havo oqimi normasi",
    slug: "turar-joy-yashash-xonasi-havo-oqimi-normasi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Turar joy ventilyatsiyasi",
    data_type: "norma",
    normative_value: "3.0",
    unit: "m³/soat har 1 m² yashash maydoniga",
    building_type: "Ko'p qavatli va yakka tartibdagi uylar",
    room_type: "Yashash xonalari (yotoqxona, zal)",
    condition: "Xonada kishi boshiga 20 m² dan kam maydon to'g'ri kelganda",
    formula: "L = S_yashash × 3.0 m³/soat",
    calculation_example: "20 m² yashash xonasi uchun: 20 × 3 = 60 m³/soat toza havo oqimi.",
    practical_note: "Agar xonada 1 kishiga 20 m² dan ortiq maydon to'g'ri kelsa, norma kishi boshiga kamida 30 m³/soat deb hisoblanadi.",
    architect_note: "Derazalarda shamollatish tirqishlari (fravuga) yoki havo kiritish klapanlari (aereco / KIV) bo'lishi shart.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.15-band",
    source_table: "4.2-jadval",
    keywords: ["havo oqimi", "yashash xonasi", "ventilyatsiya normasi", "приток воздуха"],
    status: "AMALDA",
    order_index: 39
  },
  {
    title: "4 konforkali gaz plitasi bo'lgan oshxonada ventilyatsiya tortish quvvati",
    slug: "oshxona-tortish-quvvati-4-konforkali-gaz-plita",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Oshxona ventilyatsiyasi",
    data_type: "norma",
    normative_value: "90",
    unit: "m³/soat",
    building_type: "Gazlashtirilgan turar joy binolari",
    room_type: "Oshxona",
    condition: "4 konforkali gaz plitasi o'rnatilgan xonada uzluksiz tortish",
    formula: null,
    calculation_example: null,
    practical_note: "Tabiiy tortish shaxtasi kamida 90 m³/soat chiqarishi shart. Ustiga o'rnatiladigan mo'ri (zontik) bu kanalni butunlay to'sib qo'ymasligi kerak.",
    architect_note: "Oshxona eshigi pastki qismida kamida 0.02 m² o'lchamli havo kirish panjarasi yoki 2 sm oraliq tirqish bo'lishi majburiy.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.20-band",
    source_table: "4.2-jadval",
    keywords: ["gaz plita", "oshxona ventilyatsiyasi", "tortish", "90 m3", "вытяжка кухня"],
    status: "AMALDA",
    order_index: 40
  },
  {
    title: "2 konforkali gaz plitasi bo'lgan oshxonada ventilyatsiya normasi",
    slug: "oshxona-tortish-quvvati-2-konforkali-gaz-plita",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Oshxona ventilyatsiyasi",
    data_type: "norma",
    normative_value: "60",
    unit: "m³/soat",
    building_type: "1-2 xonali gazlashtirilgan uylar",
    room_type: "Kichik oshxona",
    condition: "2 konforkali gaz plitasi bo'lganda",
    formula: null,
    calculation_example: null,
    practical_note: "Elektr plita bo'lsa ham minimal tortish 60 m³/soatni tashkil etadi.",
    architect_note: "Ventilyatsiya kanali g'ishtli (140x140 mm) yoki o'tga chidamli metall havo yo'li bilan to'g'ridan-to'g'ri tomga chiqariladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.20-band",
    source_table: "4.2-jadval",
    keywords: ["oshxona ventilyatsiyasi", "2 konforka", "вытяжка 60 м3"],
    status: "AMALDA",
    order_index: 41
  },
  {
    title: "Alohida hojatxona (tualet) uchun ventilyatsiya tortish normasi",
    slug: "hojatxona-tualet-ventilyatsiya-tortish-normasi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Sanuzel ventilyatsiyasi",
    data_type: "norma",
    normative_value: "25",
    unit: "m³/soat",
    building_type: "Turar joy binolari",
    room_type: "Alohida hojatxona (unitaz xonasi)",
    condition: "Har bir alohida hojatxona xonasi uchun",
    formula: null,
    calculation_example: null,
    practical_note: "Mexanik parrak (ventilyator) o'rnatilganda qaytaruvchi klapan (obratny klapan) qo'yilishi hidi boshqa xonadonlarga urmasligi uchun shart.",
    architect_note: "Hojatxona havosi turar joy xonalari yoki umumiy koridor orqali emas, faqat tik shaxta orqali tomga chiqariladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.22-band",
    source_table: "4.2-jadval",
    keywords: ["hojatxona", "tualet ventilyatsiyasi", "25 m3", "вытяжка санузел"],
    status: "AMALDA",
    order_index: 42
  },
  {
    title: "Vanna xonasi (hammom) uchun minimal ventilyatsiya tortish normasi",
    slug: "vanna-hammom-ventilyatsiya-tortish-normasi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Sanuzel ventilyatsiyasi",
    data_type: "norma",
    normative_value: "25",
    unit: "m³/soat",
    building_type: "Turar joy binolari",
    room_type: "Alohida vanna xonasi",
    condition: "Namlikni chiqarish uchun minimal quvvat",
    formula: null,
    calculation_example: null,
    practical_note: "Birlashgan sanuzel (vanna + unitaz) bo'lsa, tortish quvvati kamida 50 m³/soat bo'lishi talab etiladi.",
    architect_note: "Vanna xonasida namlik to'planib mog'or (gribok) hosil bo'lmasligi uchun havo tortish doimiy ishlashi kerak.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.22-band",
    source_table: "4.2-jadval",
    keywords: ["vanna ventilyatsiyasi", "hammom", "namlik", "вытяжка ванная"],
    status: "AMALDA",
    order_index: 43
  },
  {
    title: "Ofis xonasida 1 nafar xodim uchun toza havo kiritish me'yori",
    slug: "ofis-bir-xodim-toza-havo-normasi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Ofis va jamoat binolari",
    data_type: "norma",
    normative_value: "40 - 60",
    unit: "m³/soat/kishi",
    building_type: "Ofislar, banklar, biznes markazlar",
    room_type: "Ofis xonalari",
    condition: "Ochilmaydigan vitrajli derazali ofislarda (majburiy kiritish-tortish tizimi)",
    formula: "L = N_xodim × 50 m³/soat",
    calculation_example: "20 kishilik ofis bo'limi uchun: 20 × 50 = 1000 m³/soat toza havo yuborish (pritok) tizimi o'rnatiladi.",
    practical_note: "Ochiladigan derazalar bo'lsa 30-40 m³/soat/kishi qabul qilinadi; butunlay yopiq tizimda 60 m³/soat olinadi.",
    architect_note: "Havo tezligi ish zonasida 0.2 m/s dan oshmasligi kerak, aks holda xodimlar shamollab qoladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.28-band",
    source_table: null,
    keywords: ["ofis ventilyatsiyasi", "pritok", "toza havo ofis", "вентиляция офиса"],
    status: "AMALDA",
    order_index: 44
  },
  {
    title: "Xona havo almashinuv karraligini (kratnost) hisoblash formulasi",
    slug: "xona-havo-almashinuv-karraligini-hisoblash-formulasi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Hisoblash usullari",
    data_type: "hisoblash",
    normative_value: "L = V × K",
    unit: "m³/soat",
    building_type: "Barcha bino turlari",
    room_type: "Ixtiyoriy xona",
    condition: "Xona hajmi va talab qilinadigan havo karraligi asosida",
    formula: "L = V × K = (S × h) × K  [L - havo miqdori (m³/soat), V - xona hajmi (m³), K - karralik koeffitsienti]",
    calculation_example: "Maydoni S=25 m², balandligi h=3 m bo'lgan xona (V=75 m³). Karralik K=2 marta/soat bo'lsa: L = 75 × 2 = 150 m³/soat.",
    practical_note: "Turar joylar uchun K = 0.5 - 1.0 marta/soat, sanuzel uchun K = 3 - 5 marta/soat, laboratoriya/sex uchun K = 6 - 10 marta/soat.",
    architect_note: "HVAC muhandisiga loyiha topshirig'i (TZ) berishda me'moriy hajm (V) aynan shu formula orqali uzatiladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.8-band",
    source_table: null,
    keywords: ["karralik", "kratnost", "formula", "havo hisobi", "расчет воздухообмена"],
    status: "AMALDA",
    order_index: 45
  },
  {
    title: "20 m² yashash xonasi uchun toza havo talabi hisob-kitobi",
    slug: "yigirma-kvadrat-xona-havo-hisoblash-misoli",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Hisoblash usullari",
    data_type: "hisoblash",
    normative_value: "60",
    unit: "m³/soat",
    building_type: "Turar joy binosi",
    room_type: "20 m² xona",
    condition: "Shift balandligi 2.7 m, 2 nafar kishi istiqomat qilganda",
    formula: "L1 = S × 3 m³ = 20 × 3 = 60 m³/soat; L2 = N × 30 m³ = 2 × 30 = 60 m³/soat. L_hisob = max(L1, L2) = 60 m³/soat.",
    calculation_example: "Xona hajmi V = 20 × 2.7 = 54 m³. Soatiga 60 m³ havo kirganda, karralik K = 60 / 54 = 1.11 marta/soatni tashkil etadi.",
    practical_note: "Bu havo oqimi deraza oynasiga o'rnatilgan 1 ta standart havo klapani (masalan, 30-40 m³/soatlik 2 dona) orqali kiritilishi mumkin.",
    architect_note: "Eshik ostida 1.5-2.0 sm oraliq tirqish bo'lishi havo koridor orqali oshxona/sanuzel shaxtasiga o'tishini ta'minlaydi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.15-band",
    source_table: null,
    keywords: ["20 m2 xona", "havo hisobi", "misol", "primer", "расчет 20 м2"],
    status: "AMALDA",
    order_index: 46
  },
  {
    title: "15 m² yotoqxona uchun toza havo hisob-kitobi",
    slug: "on-besh-kvadrat-yotoqxona-havo-hisobi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Hisoblash usullari",
    data_type: "hisoblash",
    normative_value: "45 - 60",
    unit: "m³/soat",
    building_type: "Turar joy",
    room_type: "15 m² yotoqxona",
    condition: "2 kishi uxlaganda (CO₂ darajasi 1000 ppm dan oshmasligi uchun)",
    formula: "L = 2 kishi × 30 m³/soat = 60 m³/soat",
    calculation_example: "15 m² × 2.8 m = 42 m³ hajm. Kechasi 8 soat davomida 2 kishi nafas olganda 60 m³/soat doimiy oqim zarur.",
    practical_note: "Agar derazalar germetik yopilsa va klapan bo'lmasa, 2 soat ichida CO₂ miqdori 2000 ppm ga yetib, bosh og'rig'i keltirib chiqaradi.",
    architect_note: "Yotoqxona eshigi to'liq germetik qilinmasligi, tirqishli to'r bilan jihozlanishi tavsiya etiladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.15-band",
    source_table: null,
    keywords: ["yotoqxona havo", "15 m2", "co2", "uxlash xonasi", "вентиляция спальни"],
    status: "AMALDA",
    order_index: 47
  },
  {
    title: "Turar joy binosi tabiiy ventilyatsiya shaxtasining minimal ichki kesimi",
    slug: "turar-joy-ventilyatsiya-shaxtasi-kesimi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Shaxtalar va kanallar",
    data_type: "norma",
    normative_value: "140 × 140",
    unit: "mm (yoki d=125-150 mm)",
    building_type: "Turar joy binolari",
    room_type: "Ventilyatsiya shaxtasi",
    condition: "G'ishtli shaxtada 1/2 × 1/2 g'isht o'lchami",
    formula: "S_kanal = a × b = 0.14 × 0.14 = 0.0196 m²",
    calculation_example: "Tabiiy tortish tezligi v=1.0 m/s bo'lganda, kanal o'tkazuvchanligi: Q = S × v × 3600 = 0.0196 × 1.0 × 3600 ≈ 70 m³/soat.",
    practical_note: "Dumaloq plastmassa yoki ruxlangan quvur ishlatilganda diametri kamida 125 mm (oshxona uchun 150 mm) olinadi.",
    architect_note: "Ventilyatsiya shaxtalarini ichki yuk ko'taruvchi devorlar ichida yoki alohida blok-shaxtalarda loyihalash lozim.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.35-band",
    source_table: null,
    keywords: ["ventilyatsiya shaxtasi", "kanal kesimi", "mo'ri", "сечение вентканала"],
    status: "AMALDA",
    order_index: 48
  },
  {
    title: "Ventilyatsiya shaxtasining tom ustidagi balandligi normasi",
    slug: "ventilyatsiya-shaxtasi-tom-ustidagi-balandligi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Shaxtalar va kanallar",
    data_type: "norma",
    normative_value: "kamida 0.5",
    unit: "m",
    building_type: "Barcha bino turlari",
    room_type: "Tom ustidagi ventilyatsiya shaxtasi",
    condition: "Yassi tomda parapetdan baland yoki nishabli tom tizmasidan (konyok)",
    formula: null,
    calculation_example: null,
    practical_note: "Tizmadan (konyok) 1.5 metrgacha masofada joylashsa — tizma sathidan kamida 0.5 m baland bo'lishi shart.",
    architect_note: "Shamol orqaga urmasligi (obratnaya tyaga bo'lmasligi) uchun shaxta ustiga deflektor yoki zontik o'rnatiladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.42-band",
    source_table: null,
    keywords: ["shaxta balandligi", "tom", "konyok", "deflektor", "высота вентшахты"],
    status: "AMALDA",
    order_index: 49
  },
  {
    title: "Tabiiy ventilyatsiyada minimal vertikal tortish balandligi",
    slug: "tabiiy-ventilyatsiya-minimal-vertikal-tortish-balandligi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Shaxtalar va kanallar",
    data_type: "norma",
    normative_value: "3.0",
    unit: "m",
    building_type: "Ko'p qavatli binolarning yuqori qavatlari",
    room_type: "Eng yuqori qavatdagi ventilyatsiya panjarasi",
    condition: "Panjaradan to shaxtaning tom ustidagi chiqish og'zigacha",
    formula: "ΔP = g × h × (ρ_tashqi - ρ_ichki)",
    calculation_example: "Balandlik h < 3 m bo'lsa gravitatsion bosim ΔP yetarli bo'lmaydi va yuqori qavatlarda teskari tortish (obratnaya tyaga) yuzaga keladi.",
    practical_note: "Eng oxirgi qavatlar uchun individual ventilyatorlar yoki tomga umumiy tortuvchi gibrid ventilyator o'rnatiladi.",
    architect_note: "Arxitektor yuqori qavat shaxtalarini umumiy magistralga emas, to'g'ridan-to'g'ri tomga alohida quvur bilan chiqarishi tavsiya etiladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.40-band",
    source_table: null,
    keywords: ["tortish kuchi", "yuqori qavat", "obratnaya tyaga", "гравитационное давление"],
    status: "AMALDA",
    order_index: 50
  },
  {
    title: "Konditsioner quvvatini xona maydoni bo'yicha tezkor hisoblash formulasi",
    slug: "konditsioner-quvvatini-maydon-boyicha-hisoblash",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Sovutish va mikroklimat",
    data_type: "hisoblash",
    normative_value: "1.0 kVt sovutish quvvati har 10 m² maydonga",
    unit: "kVt / 10 m² (100 Vt/m²)",
    building_type: "Turar joy va ofis binolari",
    room_type: "Standart xonalar (shift balandligi 2.7-3.0 m)",
    condition: "O'zbekistonning issiq iqlimida o'rtacha quyosh tushadigan xonalarda",
    formula: "Q_sovutish = (S × 100 Vt) + Q_odam + Q_texnika",
    calculation_example: "30 m² mehmonxona: 30 × 100 Vt = 3.0 kVt. + 3 kishi (300 Vt) + TV/muzlatgich (400 Vt) = 3.7 kVt ≈ 12 000 BTU (12-talik split konditsioner).",
    practical_note: "Janubiy va g'arbiy tomonga qaragan panoramali oynali xonalarda me'yor 130-150 Vt/m² gacha oshiriladi.",
    architect_note: "Fasadda konditsioner tashqi bloklari uchun maxsus dekorativ savat (korzina) va drenaj trubasi ko'zda tutilishi shart.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "7.5-band",
    source_table: null,
    keywords: ["konditsioner", "sovutish hisobi", "btu", "split sistema", "расчет кондиционера"],
    status: "AMALDA",
    order_index: 51
  },
  {
    title: "Restoran issiq oshxonasi zonti uchun minimal havo tezligi",
    slug: "restoran-oshxonasi-zont-havo-tezligi-normasi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Tijorat oshxonalari",
    data_type: "norma",
    normative_value: "0.3 - 0.5",
    unit: "m/s (zont kesimida)",
    building_type: "Restoran, kafe, oshxonalar",
    room_type: "Issiq sex (goryachiy sex)",
    condition: "Plitalar va qovurish uskunalari ustidagi mahalliy tortish zontida",
    formula: "L = S_zont × v × 3600  [S_zont - zont yuzasi (m²), v - tezlik (m/s)]",
    calculation_example: "Zont o'lchami 2.0 × 1.0 m = 2 m². v=0.4 m/s bo'lsa: L = 2 × 0.4 × 3600 = 2880 m³/soat tortish quvvati zarur.",
    practical_note: "Yog' ushlagich labirintli filtrlar va gidrofiltr o'rnatilishi yong'in xavfsizligi bo'yicha majburiydir.",
    architect_note: "Restoran oshxonasi ventilyatsiyasi bino umumiy ventilyatsiyasiga ulanishi qat'iyan taqiqlanadi (alohida truba bilan tomga chiqadi).",
    source_document_number: "SHNQ 2.08.03-12",
    source_band: "5.14-band",
    source_table: null,
    keywords: ["restoran zonti", "issiq sex", "yog' ushlagich", "зонт вытяжной", "ресторан"],
    status: "AMALDA",
    order_index: 52
  },
  {
    title: "Ventilyatsiya kanallarining tranzit qismlarida o'tga chidamlilik chegarasi",
    slug: "ventilyatsiya-kanali-otga-chidamlilik-chegarasi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Yong'in xavfsizligi",
    data_type: "norma",
    normative_value: "EI 30 - EI 60",
    unit: "daqiqa (30-60 min)",
    building_type: "Ko'p qavatli barcha binolar",
    room_type: "Boshqa yong'in bo'linmasidan o'tuvchi tranzit havo yo'li",
    condition: "Yong'inga qarshi devor yoki orayopmani kesib o'tganda",
    formula: null,
    calculation_example: null,
    practical_note: "Kanal devori yong'inga qarshi maxsus bazalt qoplama (ognezashita) bilan o'raladi va kesishgan joyga o't o'chiruvchi klapan (ognezaderjivayushchiy klapan) qo'yiladi.",
    architect_note: "Tranzit shaxtalarni gipsokarton bilan yopganda kamida 2 qatlam olovga chidamli GKLO plitasi ishlatiladi.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "3.28-band",
    source_table: null,
    keywords: ["o'tga chidamlilik", "ognezashita", "EI 60", "ventkanal", "огнестойкость воздуховодов"],
    status: "AMALDA",
    order_index: 53
  },
  {
    title: "Yopiq avtoturargohlar (podval parkovka) uchun ventilyatsiya karraligi",
    slug: "podval-avtoturargoh-ventilyatsiya-karraligi",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Avtoturargohlar",
    data_type: "norma",
    normative_value: "kamida 4 - 6",
    unit: "marta/soat (yoki 150 m³/soat 1 mashinaga)",
    building_type: "Yerosti va ko'p qavatli avtoturargohlar",
    room_type: "Yerosti garaji / parkovka",
    condition: "Is gazi (CO) kontsentratsiyasini xavfsiz darajada ushlab turish",
    formula: null,
    calculation_example: "1000 m³ hajmli yerosti parkovkasi uchun: 1000 × 5 marta = 5000 m³/soat uzluksiz majburiy tortish tizimi.",
    practical_note: "CO gazini aniqlash datchiklari va tutun chiqarish (dimoudalenie) mustaqil avariya tizimi o'rnatiladi.",
    architect_note: "Tutun chiqarish shaxtasi odamlar ko'p yuradigan zonalardan va derazalardan kamida 15 m masofada chiqarilishi shart.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.55-band",
    source_table: null,
    keywords: ["yerosti parkovka", "garaj ventilyatsiyasi", "is gazi", "парковка вентиляция"],
    status: "AMALDA",
    order_index: 54
  },
  {
    title: "Xonalarda havo sifati bo'yicha karbonat angidrid (CO₂) maksimal ruxsat etilgan normasi",
    slug: "xona-havosi-co2-karbonat-angidrid-ruxsat-etilgan-norma",
    category: "Ventilyatsiya va havo almashinuvi",
    subcategory: "Mikroklimat va sanitariya",
    data_type: "norma",
    normative_value: "800 - 1000",
    unit: "ppm",
    building_type: "Barcha turar joy, ofis va maktab binolari",
    room_type: "Yashash va ish xonalari",
    condition: "Inson salomatligi va aqliy mehnat unumdorligi uchun qulay chegara",
    formula: null,
    calculation_example: "Tashqi atmosfera havosi ≈ 400-450 ppm. 800 ppm gacha — a'lo; 1000 ppm gacha — qoniqarli; 1400 ppm dan yuqori — havoning og'irlashishi va charchoq.",
    practical_note: "Zamonaviy aqlli uy (Smart Home) ventilyatsiyasi CO₂ datchigi 900 ppm dan oshganda avtomatik ravishda parraklarni kuchaytiradi.",
    architect_note: "Katta zichlikdagi auditoriya va zallarda CO₂ datchiklari orqali boshqariladigan VAV (o'zgaruvchan havo oqimi) tizimi tavsiya etiladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "Ilova 2",
    source_table: null,
    keywords: ["co2 normasi", "havo sifati", "ppm", "aqlli uy", "качество воздуха"],
    status: "AMALDA",
    order_index: 55
  }
];

module.exports = { SEED_TOPICS_BATCH1 };
