// ============================================================================
// BATCH 4: Oshxona loyihalash | Interyer me'yorlari va tavsiyalar (Topics 156-200)
// Rasmiy O'zbekiston standartlari (SHNQ 2.08.01-24, SHNQ 2.08.03-12, QMQ 2.04.05-18, QMQ 2.01.05-19)
// ============================================================================

const SEED_TOPICS_BATCH4 = [
  // --- 10. Oshxona loyihalash me'yorlari (156-177) ---
  {
    title: "Oshxona ishchi yuzasi (stoleshnitsa) standart chuqurligi",
    slug: "oshxona-ishchi-yuzasi-stoleshnitsa-chuqurligi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Oshxona mebeli ergonomikasi",
    data_type: "tavsiya",
    normative_value: "600",
    unit: "mm (60 sm)",
    building_type: "Barcha turar joylar",
    room_type: "Oshxona ishchi zonasi",
    condition: "Standart maishiy texnika (plitka, idish yuvish mashinasi) joylashtirilganda",
    formula: null,
    calculation_example: "Barcha o'rnatiladigan texnikalar (varochnaya panel, duxovka, posudomoyka) aynan 60 sm chuqurlikka moslab ishlab chiqariladi.",
    practical_note: "Katta kottejlarda yoki orolcha (ostrov)da chuqurlikni 70-90 sm gacha oshirish juda qulay va keng ish yuzasini yaratadi.",
    architect_note: "Stoleshnitsa old qirrasi ostidagi shkaf eshiklaridan 2-3 sm bo'rtib chiqishi kerak, shunda to'kilgan suyuqlik shkaf fasadiga oqmaydi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["stoleshnitsa", "oshxona chuqurligi", "60 sm", "mebel ergonomikasi", "столешница глубина"],
    status: "AMALDA",
    order_index: 156
  },
  {
    title: "Oshxona ishchi stolining toza poldan qulay balandligi",
    slug: "oshxona-ishchi-stoli-balandligi-ergonomikasi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Oshxona mebeli ergonomikasi",
    data_type: "tavsiya",
    normative_value: "850 - 900",
    unit: "mm (85 - 90 sm)",
    building_type: "Barcha turar joylar",
    room_type: "Oshxona",
    condition: "Taom tayyorlayotganda inson beli va yelkalari toliqmasligi uchun",
    formula: "H_stol = H_inson_tirsagi - 10-15 sm",
    calculation_example: "Bo'yi 160-168 sm bo'lgan inson uchun 85 sm ideal; bo'yi 170-180 sm bo'lganlar uchun 90 sm balandlik qulay.",
    practical_note: "Mebel tsokoli (pastki oyoq qismi) odatda 10-15 sm, shkaf korpusi 72 sm, stoleshnitsa qalinligi 3.8 sm bo'lib, jami 86-90 sm ni hosil qiladi.",
    architect_note: "Oshxona rozetkalarini montaj qilishda toza poldan 105-110 sm balandlik hisobga olinadi (stoleshnitsadan 15-20 sm balandda).",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["oshxona balandligi", "stoleshnitsa balandligi", "85 sm", "90 sm", "высота столешницы"],
    status: "AMALDA",
    order_index: 157
  },
  {
    title: "Oshxona osma shkaflarining (navesnoy shkaf) standart chuqurligi",
    slug: "oshxona-osma-shkaflari-chuqurligi-standarti",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Oshxona mebeli ergonomikasi",
    data_type: "tavsiya",
    normative_value: "300 - 350",
    unit: "mm (30 - 35 sm)",
    building_type: "Turar joylar",
    room_type: "Yuqori osma shkaflar",
    condition: "Taom pishirayotganda odamning peshonasi shkafga urilmasligi uchun",
    formula: null,
    calculation_example: "Pastki shkaf chuqurligi 60 sm, yuqori shkaf esa 30-35 sm. Oraliqdagi 25-30 sm farq erkin ko'rish va egilish imkonini beradi.",
    practical_note: "Agar yuqori shkaflar chuqur (antresol uslubida 60 sm) qilinayotgan bo'lsa, ular shift tagida balandda joylashishi shart.",
    architect_note: "Osma shkaflar og'ir idishlar bilan yuklanganda qulab tushmasligi uchun gipsokarton devor ichida albatta yog'och/fanera ipoteka qo'yiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["osma shkaf", "yuqori shkaf", "30 sm", "oshxona mebeli", "глубина верхних шкафов"],
    status: "AMALDA",
    order_index: 158
  },
  {
    title: "Oshxona fartuki (ish stoli va osma shkaf orasi) balandligi",
    slug: "oshxona-fartuki-stoleshnitsa-shkaf-orasi-balandligi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Oshxona mebeli ergonomikasi",
    data_type: "tavsiya",
    normative_value: "550 - 600",
    unit: "mm (55 - 60 sm)",
    building_type: "Barcha xonadonlar",
    room_type: "Oshxona fartuk zonasi (plitka devor)",
    condition: "Kichik maishiy texnikalar (choynak, blender, mikroto'lqinli pech) erkin sig'ishi uchun",
    formula: null,
    calculation_example: "55-60 sm balandlik qulay ko'rish va yuqori shkaf javonlariga erkin qo'l yetishini ta'minlaydi. 50 sm dan kam bo'lsa tor bo'lib qoladi.",
    practical_note: "Gaz plitasi ustida fartuk balandligi mo'rigacha (vytyajkagacha) kamida 75 sm gacha ko'tarilishi lozim.",
    architect_note: "Fartuk qoplamasi (keramogranit, chiniqtirilgan shisha) namlik, yog' va olov ta'siriga chidamli bo'lishi shart.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["oshxona fartuki", "fartuk balandligi", "60 sm", "фартук кухни"],
    status: "AMALDA",
    order_index: 159
  },
  {
    title: "Oshxonada klassik 'Ish uchburchagi' (Rabochiy treugolnik) qoidasi",
    slug: "oshxona-ish-uchburchagi-ergonomikasi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Ergonomik rejalashtirish",
    data_type: "tavsiya",
    normative_value: "Uchburchak perimetri: 4.0 - 7.0 m (nuqtalar orasi 1.2 - 2.5 m)",
    unit: "m",
    building_type: "Barcha xonadonlar va kottejlar",
    room_type: "Oshxona texnologik zonasi",
    condition: "Muzlatgich — Rakovina — Plita ketma-ketligi",
    formula: "P_uchburchak = L(muzlatgich-rakovina) + L(rakovina-plita) + L(plita-muzlatgich)",
    calculation_example: "Muzlatgichdan mahsulot olinadi -> Rakovinada yuviladi -> Kesish stolida tayyorlanadi -> Plitada pishiriladi. Bu tabiiy oqimdir.",
    practical_note: "Uchburchak tomonlari 1.2 m dan kam bo'lsa xona tor; 2.7 m dan oshsa uy bekasi kun davomida keraksiz charchaydi.",
    architect_note: "Muzlatgich va plita yonma-yon qo'yilmaydi (ular orasida kamida 40-60 sm oraliq ishchi stol bo'lishi shart).",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ergonomika qoidasi",
    source_table: null,
    keywords: ["ish uchburchagi", "muzlatgich rakovina plita", "ergonomika", "рабочий треугольник"],
    status: "AMALDA",
    order_index: 160
  },
  {
    title: "Gaz plitasi bilan devor yoki yon mebel orasidagi yong'in xavfsizligi masofasi",
    slug: "gaz-plitasi-yon-devor-mebel-orasi-xavfsizlik-masofasi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Yong'in xavfsizligi",
    data_type: "norma",
    normative_value: "kamida 150 - 200",
    unit: "mm (15 - 20 sm)",
    building_type: "Gazlashtirilgan binolar",
    room_type: "Oshxona plita zonasi",
    condition: "Yon devorlar va baland penallar olovdan qizib yonib ketmasligi uchun",
    formula: null,
    calculation_example: "Gaz plitasini burchak devorga taqab qo'yish taqiqlanadi! Devor bilan plita orasida kamida 15-20 sm bo'shliq yoki metall/plitka himoya qatlami bo'lishi lozim.",
    practical_note: "Plita yoniga parda kelib qolmasligi shart (shamol pardani olov ustiga olib kelishi eng ko'p yong'in sababchisi).",
    architect_note: "Derazadan gaz plitagacha bo'lgan masofa kamida 30-40 sm bo'lishi qat'iy talab qilinadi.",
    source_document_number: "QMQ 2.04.08-18 (Gaz ta'minoti)",
    source_band: "5.12-band",
    source_table: null,
    keywords: ["gaz plita masofasi", "yong'in xavfsizligi", "20 sm", "расстояние до газовой плиты"],
    status: "AMALDA",
    order_index: 161
  },
  {
    title: "Gaz plitasi va oshxona tortish mo'risi (vytyajka) orasidagi minimal masofa",
    slug: "gaz-plitasi-va-vytyajka-orasidagi-masofa",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Yong'in xavfsizligi",
    data_type: "norma",
    normative_value: "Gaz plitasi uchun: 750 - 850 mm | Elektr plita uchun: 650 - 750 mm",
    unit: "mm",
    building_type: "Barcha turar joylar",
    room_type: "Oshxona pishirish zonasi",
    condition: "Mo'rining plastik qismlari va filtri erib yonib ketmasligi uchun",
    formula: "H_vytyajka >= 750 mm (gaz plitasi)",
    calculation_example: "Gaz olovi ochiq alangalanadi, shuning uchun elektr plitaga qaraganda mo'ri 10 sm balandroq o'rnatiladi.",
    practical_note: "Agar mo'ri 85 sm dan ham baland qo'yilsa — u holda bug' va hidlarni tortish samaradorligi keskin tushib ketadi.",
    architect_note: "Qiya (naklonnaya) zamonaviy mo'rilar uchun pastki qirra gaz plitasidan 55-65 sm da o'rnatilishiga ruxsat beriladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "4.24-band",
    source_table: null,
    keywords: ["vytyajka balandligi", "mo'ri", "gaz plita", "75 sm", "высота вытяжки"],
    status: "AMALDA",
    order_index: 162
  },
  {
    title: "Oshxona orolchasi (kitchen island) atrofidagi erkin o'tish yo'laklari kengligi",
    slug: "oshxona-orolchasi-atrofidagi-otish-yolagi-kengligi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Ergonomik rejalashtirish",
    data_type: "tavsiya",
    normative_value: "kamida 1000 - 1200",
    unit: "mm (1.0 - 1.2 m)",
    building_type: "Katta kvartiralar, kottejlar",
    room_type: "Orolli oshxona (ostrov)",
    condition: "Shkaflar, duxovka va idish yuvish mashinasi eshiklari to'liq ochilishi uchun",
    formula: null,
    calculation_example: "Idish yuvish mashinasi eshigi ochilganda 60 sm joy egallaydi. Yo'lak 1.1 m bo'lsa, eshik ochiq paytda ham inson bemalol aylanib o'ta oladi.",
    practical_note: "Yo'lak 90 sm dan kam bo'lsa — ikki kishi oshxonada bir vaqtda ishlay olmaydi va orol noqulay to'siqqa aylanadi.",
    architect_note: "Orolchaning o'zida plita yoki rakovina joylashtirilsa, orol o'lchami kamida 180×90 sm qilib loyihalanadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["oshxona oroli", "ostrov", "yo'lak kengligi", "1.1 m", "кухонный остров"],
    status: "AMALDA",
    order_index: 163
  },
  {
    title: "Gazlashtirilgan oshxonalarda gaz quvurlarini (gazoprovod) o'tkazish qoidalari",
    slug: "gazlashtirilgan-oshxona-gaz-quvuri-qoidalari",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Muhandislik xavfsizligi",
    data_type: "norma",
    normative_value: "Faqat ochiq montaj; devor ichiga g'ishtlab yopish QAT'IYAN TAQIQLANADI",
    unit: "xavfsizlik talabi",
    building_type: "Gazlashtirilgan barcha binolar",
    room_type: "Oshxona",
    condition: "Gaz sizib chiqqanda hid darhol sezilishi va ta'mirlash oson bo'lishi uchun",
    formula: null,
    calculation_example: "Gaz quvurini devor ichiga yashirib gipsokarton yoki plitka bilan butunlay berkitish portlash xavfini keltirib chiqaradi va gaz idorasi tomonidan uzib qo'yiladi.",
    practical_note: "Mebel ichidan o'tganda osongina olinadigan dekorativ qopqoq (semny korob) yoki shkafning orqa foni ochiq bo'lishiga ruxsat etiladi.",
    architect_note: "Zamonaviy kvartiralarda gaz sizishini sezuvchi avtomatik signalizator va gazni uzuvchi elektromagnit klapan (otsekatel) o'rnatish majburiy.",
    source_document_number: "QMQ 2.04.08-18",
    source_band: "5.3-band",
    source_table: null,
    keywords: ["gaz quvuri", "gazoprovod", "ochiq montaj", "gaz xavfsizligi", "газовая труба"],
    status: "AMALDA",
    order_index: 164
  },
  {
    title: "Oshxonada elektr plita va duxovka uchun ajratiladigan elektr quvvati",
    slug: "oshxona-elektr-plita-duxovka-quvvati-kabeli",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Elektr ta'minoti",
    data_type: "norma",
    normative_value: "kamida 6.0 - 8.5 kVt (Kabel mis 3×6 mm² yoki 3×4 mm²)",
    unit: "kVt / kabel kesimi",
    building_type: "Gazlashtirilmagan ko'p qavatli uylar va kottejlar",
    room_type: "Elektr plita rozetkasi",
    condition: "Barcha 4 konforka va duxovka bir vaqtda to'liq quvvatda ishlaganda",
    formula: "I = P / U = 7000 Vt / 220 V ≈ 32 Amper",
    calculation_example: "32A lik alohida avtomat va to'g'ridan-to'g'ri shitdan keluvchi 3×6 mm² kesimli yonmaydigan VVGng-LS mis kabeli tortiladi.",
    practical_note: "Elektr plita uchun oddiy 16A rozetka ishlatish man etiladi — maxsus 32A kuch rozetkasi yoki bevosita klemma bloki o'rnatiladi.",
    architect_note: "Elektr loyihasida oshxona uchun jami kamida 10-12 kVt ajratilgan quvvat hisobga olinadi (choynak, plita, idish yuvish bir vaqtda ishlashi uchun).",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "Elektr bo'limi",
    source_table: null,
    keywords: ["elektr plita", "3x6 kabel", "32A", "oshxona quvvati", "электроплита кабель"],
    status: "AMALDA",
    order_index: 165
  },
  {
    title: "Oshxona ishchi yuzasida (fartukda) rozetkalar soni va joylashuvi",
    slug: "oshxona-fartuk-rozetkalar-soni-joylashuvi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Elektr ta'minoti",
    data_type: "tavsiya",
    normative_value: "kamida 3 - 4 ta blokda jami 6 - 8 dona rozetka",
    unit: "dona",
    building_type: "Barcha zamonaviy xonadonlar",
    room_type: "Oshxona ishchi stoli usti",
    condition: "Mayda maishiy texnikalarni (choynak, kofemashina, blender, toster) erkin ulash uchun",
    formula: null,
    calculation_example: "Choynak + kofemashina doimiy ulanadi (2 ta); qo'shimcha mikser/blender uchun yana 2 ta zaxira rozetka zarur.",
    practical_note: "Rozetkalar rakovina va gaz plitasidan kamida 50 sm masofada, toza poldan 105-110 sm balandlikda joylashtiriladi.",
    architect_note: "Muzlatgich, idish yuvish mashinasi va filtr uchun alohida shkaf orqasida yoki tsokol zonasida (poldan 10 sm da) yashirin rozetkalar qilinadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Elektr tavsiyasi",
    source_table: null,
    keywords: ["oshxona rozetkasi", "fartuk rozetka", "110 sm", "rozetki na kuhne"],
    status: "AMALDA",
    order_index: 166
  },
  {
    title: "Oshxona ishchi yuzasining normativ yoritilganlik darajasi",
    slug: "oshxona-ishchi-yuzasi-yoritilganlik-normasi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Yoritish va yorug'lik",
    data_type: "norma",
    normative_value: "kamida 300 - 500",
    unit: "lux (lyuks)",
    building_type: "Barcha turar joylar",
    room_type: "Oshxona stoleshnitsa yuzasi",
    condition: "Pichoq bilan ishlashda va tozalashda xavfsizlik va aniqlik uchun",
    formula: null,
    calculation_example: "Faqat umumiy shift lyustrasi yetarli emas (inson stoleshnitsaga qaraganda uning o'z tanasi soyasi ish yuzasiga tushadi).",
    practical_note: "Osma shkaflarning pastki qismiga o'rnatiladigan chiziqli LED lenta (4000K neytral oq nur) stoleshnitsani to'g'ridan-to'g'ri 400-500 lux bilan yoritadi.",
    architect_note: "Taomning tabiiy ko'rinishi buzilmasligi uchun rang ko'rsatish indeksi CRI (Ra) >= 85 bo'lgan yorug'lik diodlari tanlanadi.",
    source_document_number: "QMQ 2.01.05-19",
    source_band: "3.2-band",
    source_table: "3.1-jadval",
    keywords: ["oshxona yoritish", "300 lux", "LED profil", "fartuk chiroq", "освещенность кухни"],
    status: "AMALDA",
    order_index: 167
  },
  {
    title: "Gaz plitasi bo'lgan oshxonada eshik bo'lishi bo'yicha majburiy shaharsozlik normasi",
    slug: "gazli-oshxonada-eshik-bolishi-majburiy-normasi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Gaz xavfsizligi",
    data_type: "norma",
    normative_value: "Zich yopiluvchi eshik bo'lishi SHART (arkaga yoki ochiq proyomga ruxsat yo'q)",
    unit: "majburiy talab",
    building_type: "Gazlashtirilgan ko'p xonadonli uylar",
    room_type: "Oshxona bilan yashash xonasi / koridor chegarasi",
    condition: "Gaz sizib chiqqanda tunda uxlayotgan odamlarning yashash xonalariga tarqalmasligi uchun",
    formula: null,
    calculation_example: "Ko'pchilik moda deb gazli oshxona devorini buzib zal bilan birlashtiradi (kuxnya-gostinaya). Bu gaz inspeksiyasi qoidalariga mutlaqo ziddir!",
    practical_note: "Agar birlashtirish juda zarur bo'lsa — faqat surma shisha to'siq (razdvijnaya peregorodka) qo'yish yoki gaz plitasini rasman elektr plitaga almashtirish shart.",
    architect_note: "Eshik pastida havo kirishi uchun kamida 2 sm li tirqish bo'lishi majburiy.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.6-band",
    source_table: null,
    keywords: ["gazli oshxona eshigi", "arka taqiqi", "gaz xavfsizligi", "дверь на кухню с газом"],
    status: "AMALDA",
    order_index: 168
  },
  {
    title: "Oshxona pol qoplamasiga qo'yiladigan normativ talablar",
    slug: "oshxona-pol-qoplamasi-talablari",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Pardozlash materiallari",
    data_type: "tavsiya",
    normative_value: "Suvga chidamli, yonmaydigan, sirpanmaydigan (R10) keramogranit yoki SPC",
    unit: "material talabi",
    building_type: "Turar joylar",
    room_type: "Oshxona poli",
    condition: "Yog', issiq suv va og'ir idishlar tushishi xavfi mavjud bo'lganda",
    formula: null,
    calculation_example: "Oddiy laminat oshxonada suv to'kilsa choklaridan shishib ketadi. Sirlangan keramogranit esa suv to'kilganda o'ta sirpanchiq bo'ladi.",
    practical_note: "Matoviy yuzali teksturali keramogranit yoki tosh-polimer kompozit (SPC plitka) eng chidamli va amaliy yechimdir.",
    architect_note: "Kafel ostiga elektr yoki suvli issiq pol (tepliy pol) o'rnatilishi oyoqlarga qulay iliqlik yaratadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Pardozlash talabi",
    source_table: null,
    keywords: ["oshxona poli", "keramogranit", "SPC", "namlikka chidamli", "пол на кухне"],
    status: "AMALDA",
    order_index: 169
  },
  {
    title: "Oshxona rakovinasi kanalizatsiya chiqishi balandligi va diametri",
    slug: "oshxona-rakovinasi-kanalizatsiya-chiqishi-normasi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Santexnika muhandisligi",
    data_type: "norma",
    normative_value: "Diametri: d=50 mm | Chiqish balandligi: toza poldan 350 - 450 mm",
    unit: "mm",
    building_type: "Barcha bino turlari",
    room_type: "Oshxona rakovinasi osti",
    condition: "Sifon va idish yuvish mashinasi (posudomoyka) chiqindisini qulay ulash uchun",
    formula: null,
    calculation_example: "Agar chiqish poldan 55 sm dan baland qilib qo'yilsa, chuqur metall rakovina o'rnatilgach sifon pastda qolib suv yaxshi oqmay qoladi.",
    practical_note: "Idish yuvish mashinasi shlangi uchun sifon ustida maxsus qo'shimcha shtutser nazarda tutiladi.",
    architect_note: "Oziq-ovqat chiqindilarini maydalagich (izmelchitel / dizpozer) o'rnatilsa, kanalizatsiya quvuri nishabligi qat'iy nazorat qilinishi kerak.",
    source_document_number: "QMQ 2.04.01-98",
    source_band: "3.5-band",
    source_table: null,
    keywords: ["oshxona kanalizatsiyasi", "d50", "400 mm", "sifon", "канализация кухни"],
    status: "AMALDA",
    order_index: 170
  },
  {
    title: "Oshxona ichimlik suvini tozalash filtrlari (teskari osmos) uchun joy va ulanish",
    slug: "oshxona-teskari-osmos-suv-filtri-talablari",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Suv ta'minoti",
    data_type: "tavsiya",
    normative_value: "Rakovina ostida 400 × 400 × 500 mm toza bo'shliq + 220V rozetka",
    unit: "mm joy",
    building_type: "Turar joylar",
    room_type: "Oshxona moyka shkafi osti",
    condition: "Teskari osmos (obratny osmos) va saqlash baki (gidroakkumulyator) joylashtirish uchun",
    formula: null,
    calculation_example: "Bosim pompasi (nasos) bilan ishlovchi zamonaviy filtrlar uchun moyka ostida albatta bitta 220V rozetka kerak bo'ladi.",
    practical_note: "Filtrning drenaj suvi rakovina sifoniga maxsus qisqich (xomut) orqali ulanadi.",
    architect_note: "Stoleshnitsaga ikkinchi kran qo'yib teshmaslik uchun 2-in-1 (ham oddiy jo'mrak, ham tozalangan ichimlik suvi chiqadigan) aralash smesitel tavsiya etiladi.",
    source_document_number: "QMQ 2.04.01-98",
    source_band: "Amaliy tavsiya",
    source_table: null,
    keywords: ["osmos filtr", "suv filtri", "moyka osti", "ichimlik suvi", "фильтр обратного осмоса"],
    status: "AMALDA",
    order_index: 171
  },
  {
    title: "Restoran va kafelarda oshxona maydonining umumiy zal maydoniga nisbati",
    slug: "restoran-oshxona-maydonining-zalga-nisbati",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Tijorat umumiy ovqatlanishi",
    data_type: "norma",
    normative_value: "Zal maydonining 40% - 60% ini tashkil qiladi",
    unit: "nisbat (% zal maydoniga)",
    building_type: "Restoranlar, kafelar, oshxonalar",
    room_type: "Ishlab chiqarish oshxona bloki",
    condition: "To'liq siklda ishlovchi (xomashyodan pishirishgacha) restoranlarda",
    formula: "S_oshxona_bloki ≈ S_zal × 0.5",
    calculation_example: "200 m² zalga ega bo'lgan restoran uchun barcha sexlar (issiq, sovuq, go'sht, idish yuvish, ombor) jami kamida 100-120 m² bo'lishi shart.",
    practical_note: "Yarim tayyor (polufabrikat) mahsulotlardan foydalaniladigan kafelarda oshxona maydonini zalning 25-30% igacha qisqartirish mumkin.",
    architect_note: "Restoran loyihalashda eng ko'p yo'l qo'yiladigan xato — zalni katta qilib, oshxonani tor qilib qo'yishdir.",
    source_document_number: "SHNQ 2.08.03-12",
    source_band: "3.4-band",
    source_table: "3.2-jadval",
    keywords: ["restoran oshxonasi", "nisbat", "sexlar maydoni", "кухня ресторана"],
    status: "AMALDA",
    order_index: 172
  },
  {
    title: "Restoran oshxonasida texnologik oqimlar (Potochnost) kesishmasligi qoidasi",
    slug: "restoran-oshxonasi-texnologik-oqimlar-kesishmasligi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Sanitariya qoidalari (SanPiN)",
    data_type: "norma",
    normative_value: "Xomashyo kirishi va tayyor taom chiqishi qat'iyan bir-biri bilan kesishmasligi shart",
    unit: "sanitariya qonuni",
    building_type: "Barcha umumiy ovqatlanish korxonalari",
    room_type: "Oshxona sexlari va yo'laklari",
    condition: "Bakteriyalar va xom go'sht mikrobi pishgan ovqatga o'tmasligi (infektsiya oldini olish) uchun",
    formula: null,
    calculation_example: "1-oqim: Xomashyo tushirish -> Omborxona -> Boshlang'ich ishlov (go'sht/sabzavot sexi). 2-oqim: Issiq/sovuq pishirish sexi -> Tarqatish stoli -> Mehmon zali. 3-oqim: Kir idishlar qaytishi -> Idish yuvish xonasi.",
    practical_note: "Kir idishlar yuvishga kiradigan eshik bilan tayyor taom zalga olib chiqiladigan eshik mutlaqo alohida bo'ladi.",
    architect_note: "SES (Sanitariya-epidemiologiya xizmati) potochnost buzilgan loyihani hech qachon ishga tushirishga ruxsat bermaydi.",
    source_document_number: "SHNQ 2.08.03-12",
    source_band: "4.2-band",
    source_table: null,
    keywords: ["potochnost", "oqimlar", "restoran sanitariyasi", "xomashyo", "поточность на кухне"],
    status: "AMALDA",
    order_index: 173
  },
  {
    title: "Tijoriy oshxonalarda yog' ushlagich (jiroulovitel) o'rnatish majburiyati",
    slug: "oshxona-yog-ushlagich-jiroulovitel-normasi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Kanalizatsiya va ekologiya",
    data_type: "norma",
    normative_value: "Barcha restoran va kafelar kanalizatsiyasida majburiy",
    unit: "ekologik talab",
    building_type: "Restoran, kafe, oshxona, qandolatchilik sexlari",
    room_type: "Idish yuvish va go'sht sexi chiqindi suvlari",
    condition: "Yog'lar shahar umumiy kanalizatsiya quvurlarini qotib to'sib qo'ymasligi uchun",
    formula: null,
    calculation_example: "Kichik kafelarda moyka ostiga kompakt lokal yog' ushlagich (50-100 litr) qo'yiladi; katta restoranlarda yerosti markaziy yog' ajratuvchi loyihalanadi.",
    practical_note: "Yog' ushlagichsiz restoranga 'Suvsoz' davlat korxonasi kanalizatsiyaga ulanishga ruxsat bermaydi va katta jarima soladi.",
    architect_note: "Yog' ushlagich xizmat ko'rsatish va tozalash uchun qulay bo'lgan alohida texnik xonada yoki tashqarida joylashtiriladi.",
    source_document_number: "QMQ 2.04.01-98",
    source_band: "4.18-band",
    source_table: null,
    keywords: ["jiroulovitel", "yog' ushlagich", "restoran kanalizatsiyasi", "жироуловитель"],
    status: "AMALDA",
    order_index: 174
  },
  {
    title: "Oshxona mebellarining burchak tutashuvlarida (G va P shaklli) 'o'lik zona' yechimlari",
    slug: "oshxona-burchak-shkafi-olik-zona-yechimlari",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Mebel furniturasi",
    data_type: "tavsiya",
    normative_value: "Karousel (90x90 sm) yoki Sehrli burchak (Magic Corner / LeMans)",
    unit: "furnitura yechimi",
    building_type: "Turar joylar",
    room_type: "Burchakli oshxona гарнитури",
    condition: "Burchakdagi 60x60 sm chuqur bo'shliqdan samarali foydalanish uchun",
    formula: null,
    calculation_example: "Oddiy tokcha qo'yilsa odam ichkariga qo'li yetmaydi va buyumlar unutiladi. Aylanuvchi karusel barcha qozonlarni bir harakat bilan tashqariga chiqaradi.",
    practical_note: "Burchak qismiga rakovina qo'yilganda trapesiyasimon 90x90 sm burchak shkafi loyihalash qulayroq.",
    architect_note: "Burchak tortmalari ochilganda bir-birining tutqichlariga urilmasligi uchun burchakda kamida 50 mm li dekorativ qo'shimcha planka (falshpanal) ko'zda tutiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["burchak oshxona", "karusel", "magic corner", "falshpanal", "угол кухни"],
    status: "AMALDA",
    order_index: 175
  },
  {
    title: "Oshxona muzlatgichi atrofidagi shamollatish tirqishlari",
    slug: "muzlatgich-atrofidagi-shamollatish-tirqishlari",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Maishiy texnika montaji",
    data_type: "tavsiya",
    normative_value: "Orqadan: kamida 50 mm | Tepadan: kamida 100 mm (yoki tsokolda ventpanjara)",
    unit: "mm bo'shliq",
    building_type: "Barcha uylar",
    room_type: "Muzlatgich joyi",
    condition: "Kompressor va radiator qizib ketmasligi, elektr tejalishi uchun",
    formula: null,
    calculation_example: "Mebel ichiga o'rnatiladigan (vstraivaemy) muzlatgichlarda pastki tsokolda kamida 200 sm² li ventilyatsiya to'ri va orqa devor bo'ylab havo chiqish kanali shart.",
    practical_note: "Muzlatgich devorga taqab qo'yilsa, radiator sovimay kompressor uzluksiz ishlaydi va 1-2 yilda kuyadi.",
    architect_note: "Muzlatgich yoniga issiq duxovka yoki radiator qo'yilishi qat'iyan tavsiya etilmaydi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["muzlatgich", "xolodilnik", "ventilyatsiya", "tsokol to'ri", "вентиляция холодильника"],
    status: "AMALDA",
    order_index: 176
  },
  {
    title: "Oshxona chiqindilarini saralash (musor) va saralash tizimi ergonomikasi",
    slug: "oshxona-chiqindilarini-saralash-tizimi-joylashuvi",
    category: "Oshxona loyihalash me'yorlari",
    subcategory: "Ekologiya va tozalik",
    data_type: "tavsiya",
    normative_value: "Rakovina ostida 60-80 sm li tortmada 2-3 bo'lmali chelaklar",
    unit: "tizim",
    building_type: "Zamonaviy turar joylar",
    room_type: "Oshxona moyka shkafi",
    condition: "Organik, qog'oz/plastik va shisha chiqindilarni alohida ajratish uchun",
    formula: null,
    calculation_example: "Oyoq pedali yoki fasadni tizzada turtganda ochiluvchi (Tip-On / Servo-Drive) tizim qo'llar iflos bo'lganda juda qulaydir.",
    practical_note: "Organik qoldiqlar uchun moyka ostiga o'rnatiladigan dizpozer (izmelchitel) chiqindi chelagidagi noxush hidni 80% ga yo'qotadi.",
    architect_note: "Bino umumiy chiqindi tashlash xonasida ham alohida konteynerlar uchun maydoncha hisobga olinadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ekologik tavsiya",
    source_table: null,
    keywords: ["musor", "chiqindi saralash", "moyka osti", "dizpozer", "сортировка мусора"],
    status: "AMALDA",
    order_index: 177
  },

  // --- 11. Interyer me'yorlari va amaliy tavsiyalar (178-200) ---
  {
    title: "Yashash xonalari va koridorlarda rozetkalarning poldan standart o'rnatish balandligi",
    slug: "rozetkalar-standart-ornatish-balandligi-poldan",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Elektr montaji",
    data_type: "tavsiya",
    normative_value: "300",
    unit: "mm (toza poldan 30 sm - Yevrostandart)",
    building_type: "Turar joy va ofis binolari",
    room_type: "Yashash xonalari, yotoqxona, koridor",
    condition: "Elektr simlari ko'zga tashlanmasligi va changyutgich, lampalar qulay ulanishi uchun",
    formula: null,
    calculation_example: "Qora suvoq davrida toza pol stajkasi hisobga olinib, poldan 35-40 sm da teshik (podrozetnik) burg'ulanadi.",
    practical_note: "Yotoqxonada kravat yonidagi tumba usti rozetkalari poldan 65-70 sm balandlikda (tumba ustidan 10-15 sm da) qilinadi.",
    architect_note: "TV zonasi (plazma televizor orqasi) uchun rozetkalar bloki toza poldan 100-110 sm balandlikda joylashtirilsa kabellar butunlay yashirinadi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "Elektr qoidalari",
    source_table: null,
    keywords: ["rozetka balandligi", "30 sm", "yevrostandart", "podrozetnik", "высота розеток"],
    status: "AMALDA",
    order_index: 178
  },
  {
    title: "Yorug'lik o'chirgichlarining (vyklyuchatel) toza poldan standart o'rnatish balandligi",
    slug: "vyklyuchatel-standart-ornatish-balandligi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Elektr montaji",
    data_type: "tavsiya",
    normative_value: "800 - 900",
    unit: "mm (toza poldan 85-90 sm)",
    building_type: "Barcha bino turlari",
    room_type: "Barcha xonalar kirishi",
    condition: "Inson qo'lini pastga tushirganda tirsak bukilmasdan barmoq bilan qulay bosilishi uchun",
    formula: null,
    calculation_example: "Eshik ochiladigan tomonda (tutqich tomonda) eshik romidan 100-150 mm masofada joylashtiriladi.",
    practical_note: "Eski sovet standarti 160 sm edi; yangi 90 sm standart bolalar uchun ham, kattalar uchun ham ancha qulay.",
    architect_note: "Vyklyuchatel eshik orqasida qolib ketishi (eshik ochilganda to'silishi) qo'pol me'moriy xatodir!",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["vyklyuchatel", "chiroq tugmasi", "90 sm", "balandlik", "высота выключателя"],
    status: "AMALDA",
    order_index: 179
  },
  {
    title: "Turar joy xonalari uchun sun'iy yoritilganlik normasi (lux)",
    slug: "turar-joy-suniy-yoritilganlik-normasi-lux",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Yoritish va qulaylik",
    data_type: "norma",
    normative_value: "Mehmonxona: 150 lux | Yotoqxona: 100-150 lux | Bolalar xonasi: 200 lux | Ish kabineti: 300 lux",
    unit: "lux (pol yoki ish sathi bo'yicha)",
    building_type: "Turar joy binolari",
    room_type: "Yashash va yordamchi xonalar",
    condition: "LED yoritgichlar bilan umumiy yoritishda",
    formula: "Lumen_jami = Maydon × Lux",
    calculation_example: "20 m² mehmonxona uchun: 20 × 150 = 3000 Lumen yorug'lik oqimi zarur (taxminan 30-35 Vt zamonaviy sifatli LED lampalar).",
    practical_note: "Yotoqxonada 2700-3000K iliq sariq yorug'lik (dam olish uchun), ish stolida esa 4000K neytral oq yorug'lik tanlanadi.",
    architect_note: "Ko'p darajali yoritish (asosiy shift nuri + nuqtali chiroqlar + devor bra + pol torcheri) har qanday xonada qulay atmosfera yaratadi.",
    source_document_number: "QMQ 2.01.05-19",
    source_band: "2.1-band",
    source_table: "2.2-jadval",
    keywords: ["yoritilganlik", "lux", "150 lux", "lyumen", "LED chiroq", "нормы освещения"],
    status: "AMALDA",
    order_index: 180
  },
  {
    title: "Yashirin parda karnizlari uchun shift o'yig'ining (nisha dlya shtor) o'lchamlari",
    slug: "yashirin-karniz-parda-nisha-olchamlari",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Shift konstruksiyalari",
    data_type: "tavsiya",
    normative_value: "Chuqurligi: 150 - 200 mm | Eni: devordan 200 - 250 mm",
    unit: "mm",
    building_type: "Barcha xonadonlar va uylar",
    room_type: "Deraza oldi shift qismi",
    condition: "Parda va tyul erkin harakatlanishi, radiatordan va deraza tokchasidan tegmasligi uchun",
    formula: null,
    calculation_example: "Deraza tokchasi devordan 5 sm chiqadi, radiator 10 sm chiqadi. Karniz nishasi eni 20-25 sm bo'lsa parda qalin tushganda ham radiatorga tegmay erkin osilib turadi.",
    practical_note: "Nisha ichiga yashirin LED lenta o'rnatilsa parda bo'ylab chiroyli yorug'lik sharsharasi (svetovaya liniya) hosil bo'ladi.",
    architect_note: "Gipsokarton yoki cho'ziluvchan shift profilini o'rnatishdan oldin bu o'lcham chizmada qat'iy belgilanadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["yashirin karniz", "parda nishasi", "20 sm", "shift nishasi", "ниша для штор"],
    status: "AMALDA",
    order_index: 181
  },
  {
    title: "Yashirin plintus (skryty plintus) va soya choki (tenevoy shov) montaj o'lchamlari",
    slug: "yashirin-plintus-tenevoy-shov-montaj-olchamlari",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Devor va pol tutashuvi",
    data_type: "tavsiya",
    normative_value: "Balandligi: 40 - 60 mm | Chuqurligi: devor ichiga 12 - 15 mm",
    unit: "mm",
    building_type: "Zamonaviy interyerlar (minimalizm, neoklassika)",
    room_type: "Barcha xonalar va koridorlar",
    condition: "Devor bilan pol orasida bo'rtib chiqmaydigan tekis yoki havoda muallaq turgan devor effekti yaratishda",
    formula: null,
    calculation_example: "Alyuminiy profil gipsokarton ostiga yoki suvoq devor shtrobasiga mahkamlanadi. Pol qoplamasi (parket/laminat) profil ostiga 5-8 mm kirib turadi.",
    practical_note: "Mebelni devorga 100% taqab qo'yish imkonini beradi (oddiy plintus mebelni 1.5-2 sm devordan uzoqlashtiradi).",
    architect_note: "Profil ichiga LED lenta o'rnatilsa — xira tungi yoritish sifatida koridorlarda juda ajoyib samara beradi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Zamonaviy dizayn tavsiyasi",
    source_table: null,
    keywords: ["yashirin plintus", "tenevoy plintus", "soya choki", "skryty plintus", "скрытый плинтус"],
    status: "AMALDA",
    order_index: 182
  },
  {
    title: "Laminat va parket pol qoplamalari ostidagi texnologik harorat choki (kompensatsionny shov)",
    slug: "laminat-parket-kompensatsion-chok-masofasi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Pol qoplamalari",
    data_type: "norma",
    normative_value: "Devorlar bo'ylab kamida 8 - 12 mm oraliq tirqish",
    unit: "mm",
    building_type: "Barcha binolar",
    room_type: "Laminat, parket, LVT yotqizilgan barcha xonalar",
    condition: "Yozda namlik va issiqda yog'och kengayganda pol ko'tarilib qavariq (domkrat) bo'lmasligi uchun",
    formula: null,
    calculation_example: "Devor bilan laminat orasiga montaj paytida 10 mm li ponalar (klinya) qo'yiladi. Keyinchalik bu tirqish plintus bilan to'liq yopiladi.",
    practical_note: "Agar xona uzunligi 8-10 metrdan oshsa — xona o'rtasidagi eshik tagiga ham ajratuvchi kompensatsion T-profil o'rnatiladi.",
    architect_note: "Plitka va laminat tutashgan joyda metall nakladnoy porog o'rniga suyuq po'kak (probkovy kompensator) qo'yilsa silliq ostonasiz go'zal chok hosil bo'ladi.",
    source_document_number: "QMQ 2.03.01-96",
    source_band: "3.4-band",
    source_table: null,
    keywords: ["laminat choki", "kompensatsion shov", "10 mm", "pol kengayishi", "зазор для ламината"],
    status: "AMALDA",
    order_index: 183
  },
  {
    title: "Issiq pol (tyoply pol) stajkasi minimal qalinligi va issiqlik izolyatsiyasi",
    slug: "issiq-pol-stajkasi-minimal-qalinligi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Isitish va pol",
    data_type: "norma",
    normative_value: "Quvurlar ustidan kamida 30 - 50 mm (umumiy qalinlik 65 - 85 mm)",
    unit: "mm",
    building_type: "Barcha bino turlari",
    room_type: "Issiq polli zonalar (sanuzel, koridor, oshxona, hovli uylar)",
    condition: "Quvurlar siqilib yorilmasligi va issiqlik pol yuzasiga bir tekis tarqalishi uchun",
    formula: "H_stajka = D_truba (16 mm) + H_ustki_qatlam (45 mm) = 60-65 mm",
    calculation_example: "Quvur ostiga kamida 30-50 mm ekstrudirlangan penopolistirol (XPS) yotqiziladi, aks holda issiqlikning yarmi pastki qavatga behuda ketadi.",
    practical_note: "Stajka tarkibiga plastifikator va tolali fibra (fibrovolokno) qo'shilishi qiziganda stajkaning yorilib ketishidan asraydi.",
    architect_note: "Perimetr bo'ylab 8-10 mm li dempfer lentasi (kromochnaya lenta) qo'yilishi shart, aks holda stajka kengayib devorlarni turtib buzadi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "3.25-band",
    source_table: null,
    keywords: ["issiq pol", "tyoply pol", "stajka", "dempfer lentasi", "стяжка теплого пола"],
    status: "AMALDA",
    order_index: 184
  },
  {
    title: "O'zbekistonda yashash xonalari pol yuzasi maksimal ruxsat etilgan harorati",
    slug: "issiq-pol-yuzasi-maksimal-harorati-normasi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Isitish va pol",
    data_type: "norma",
    normative_value: "Yashash xonalari: max 26 - 29°C | Sanuzel va basseyn: max 31°C",
    unit: "°C (gradus Seltsiy)",
    building_type: "Turar joy binolari",
    room_type: "Inson doimiy yashaydigan xonalar",
    condition: "Sanitariya-gigiyena me'yori bo'yicha inson oyog'i qizib ketmasligi uchun",
    formula: null,
    calculation_example: "Pol harorati 30°C dan oshsa — inson tanasida qon aylanishi buziladi, varikoz xavfi oshadi va xona havosi o'ta quruq bo'lib chang ko'tariladi.",
    practical_note: "Laminat va parket ostidagi issiq pol harorati ishlab chiqaruvchi tomonidan maksimal 27-28°C bilan cheklangan (yuqori bo'lsa formaldegid ajraladi).",
    architect_note: "Termoregulyator o'rnatilganda polga solingan datchik haroratni aynan shu normada cheklashga dasturlanadi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "3.26-band",
    source_table: null,
    keywords: ["pol harorati", "26 gradus", "sanitariya normasi", "issiqlik me'yori", "температура теплого пола"],
    status: "AMALDA",
    order_index: 185
  },
  {
    title: "Isitish radiatori bilan devor va deraza tokchasi orasidagi zarur tirqishlar",
    slug: "radiator-devor-tokcha-orasi-tirqishlar-normasi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Isitish muhandisligi",
    data_type: "norma",
    normative_value: "Poldan: kamida 100-120 mm | Devordan: kamida 30-50 mm | Tokchadan: kamida 100 mm",
    unit: "mm",
    building_type: "Barcha bino turlari",
    room_type: "Deraza osti radiator zonasi",
    condition: "Tabiiy konveksiya (sovuq havoni pastdan so'rib, qizdirib tepaga haydash) uchun",
    formula: null,
    calculation_example: "Agar radiator to'g'ridan-to'g'ri polga qo'yilsa pastdan sovuq havo kirmaydi; agar tokchaga taqab qo'yilsa issiq havo yuqoriga chiqolmaydi va xona sovuq qoladi.",
    practical_note: "Radiatorni dekorativ ekran bilan yopganda, uning pastida va ustida kamida 50% maydonga teng bo'lgan teshikli panjara bo'lishi shart.",
    architect_note: "Radiator orqasidagi devorga folgali issiqlik qaytaruvchi ekran (penofol) yopishtirilsa, devor isib ketishi oldi olinib, 5-8% issiqlik tejaladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "3.18-band",
    source_table: null,
    keywords: ["radiator tirqishi", "konveksiya", "radiator devor", "poldan balandlik", "установка радиатора"],
    status: "AMALDA",
    order_index: 186
  },
  {
    title: "Devorga osiladigan televizor (TV) ekranining qulay ko'rish balandligi",
    slug: "televizor-tv-ekrani-qulay-ko'rish-balandligi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Ergonomika va ko'rish",
    data_type: "tavsiya",
    normative_value: "Ekran markazi toza poldan 1000 - 1200 mm (o'tirgan inson ko'zi sathida)",
    unit: "mm (1.0 - 1.2 m)",
    building_type: "Turar joylar",
    room_type: "Mehmonxona, yashash xonasi",
    condition: "Divanda o'tirib uzoq tomosha qilganda bo'yin muskullari toliqmasligi uchun",
    formula: "H_ekran_markazi = H_koz_sathi (divanda o'tirganda ≈ 105-110 sm)",
    calculation_example: "Agar televizor baland osilsa (1.5 m da), odam boshini orqaga tashlab ko'rishga majbur bo'ladi va bo'yin umurtqasi og'riydi.",
    practical_note: "Yotoqxonada kravatda yotib ko'rilganda ekran markazi biroz balandroq (120-140 sm) qilinadi va kronshteyn pastga egiluvchi qilib o'rnatiladi.",
    architect_note: "Ekrandan divangacha bo'lgan optimal masofa zamonaviy 4K televizorlar uchun ekran diagonalining 1.5 - 2 baravarini tashkil qiladi (masalan 65 dyuym uchun 2.2 - 2.5 metr).",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ergonomik tavsiya",
    source_table: null,
    keywords: ["tv balandligi", "televizor", "ekran markazi", "110 sm", "высота телевизора"],
    status: "AMALDA",
    order_index: 187
  },
  {
    title: "Kiyim shkafi (garderob) ichki ergonomik bo'limlarining o'lchamlari",
    slug: "garderob-kiyim-shkafi-ichki-ergonomikasi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Garderob mebeli",
    data_type: "tavsiya",
    normative_value: "Shkaf chuqurligi: 600 mm | Uzun kiyimlar bo'limi: 1400 - 1600 mm | Kalta kiyimlar: 900 - 1100 mm",
    unit: "mm",
    building_type: "Turar joylar",
    room_type: "Garderob, yotoqxona, dahliz",
    condition: "Kiyim ilgichlar (plechiki) erkin sig'ishi va kiyimlar ezilmasligi uchun",
    formula: null,
    calculation_example: "Kupe eshikli (surma) shkaflarda mexanizm yo'li 10 sm oladi, shuning uchun shkaf umumiy chuqurligi kamida 65-70 sm qilib yasaladi.",
    practical_note: "Poyabzal polkasi balandligi 15-20 sm (etiklar uchun 40-45 sm); ichki tortmalar balandligi 15-20 sm qilinadi.",
    architect_note: "Garderob xonasida (walk-in closet) kiyim javonlari orasidagi o'tish yo'lagi kamida 80-90 sm bo'lishi shart.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["garderob o'lchami", "shkaf chuqurligi", "60 sm", "kiyim ilgich", "размеры гардероба"],
    status: "AMALDA",
    order_index: 188
  },
  {
    title: "Ikki kishilik karavot (Double bed) atrofidagi erkin o'tish yo'laklari",
    slug: "ikki-kishilik-karavot-atrofidagi-otish-masofasi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Yotoqxona ergonomikasi",
    data_type: "tavsiya",
    normative_value: "kamida 700",
    unit: "mm (70 sm har ikki tomondan)",
    building_type: "Turar joylar, mehmonxonalar",
    room_type: "Yotoqxona",
    condition: "Ikkala inson ham bir-birini bezovta qilmasdan karavotga yotishi va turishi uchun",
    formula: null,
    calculation_example: "Karavot kengligi 180 sm + ikki tomondan 70 sm + 70 sm = xona toza eni kamida 3.20 metr bo'lishi kerak.",
    practical_note: "Agar karavot bir tomoni bilan devorga taqab qo'yilsa — devor tomonidagi odam har safar narigi odam ustidan oshib o'tishga majbur bo'ladi.",
    architect_note: "Karavot oyoq uchidan qarama-qarshi devor/komodgacha ham kamida 70-80 sm o'tish yo'li qoldirilishi lozim.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["karavot o'lchami", "yotoqxona o'tish", "70 sm", "spalnya", "проход вокруг кровати"],
    status: "AMALDA",
    order_index: 189
  },
  {
    title: "Ovqatlanish stoli atrofidagi ergonomik o'tish va stulni surish masofasi",
    slug: "ovqatlanish-stoli-atrofidagi-ergonomik-masofa",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Oshxona va mehmonxona",
    data_type: "tavsiya",
    normative_value: "Stoldan devorgacha kamida 800 - 900 mm (orqadan odam o'tishi bilan 1000 - 1100 mm)",
    unit: "mm",
    building_type: "Barcha xonadonlar",
    room_type: "Oshxona, stolovaya, zal",
    condition: "Stulni erkin orqaga surib o'tirish va ovqat berayotganda orqadan bemalol o'tish uchun",
    formula: null,
    calculation_example: "Stul orqaga surilganda 50 sm joy egallaydi. Devorgacha 80 sm bo'lsa odam qisilib qolmaydi.",
    practical_note: "Bitta odamning stolda qulay ovqatlanishi uchun stol kengligidan kamida 60 sm, chuqurligidan 40 sm shaxsiy maydon ajratiladi.",
    architect_note: "Ovqatlanish stoli tepasiga osiladigan lyustra stol yuzasidan 75-85 sm balandlikda osilsa, mehmonga ko'zini qamashtirmasdan chiroyli nur beradi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ergonomik tavsiya",
    source_table: null,
    keywords: ["ovqatlanish stoli", "stul surish", "stolovaya", "обеденный стол"],
    status: "AMALDA",
    order_index: 190
  },
  {
    title: "Gipsokarton (GKL) devor va to'siqlarga og'ir mebel osish qoidalari",
    slug: "gipsokarton-devorga-ogir-mebel-osish-qoidalari",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Konstruktiv montaj",
    data_type: "norma",
    normative_value: "Bir nuqtaga maxsus dyubel-kapalak (Molly) bilan max 15-20 kg; 20 kg dan ortiq bo'lsa ipoteka (zakladnaya) shart",
    unit: "kg yuklama",
    building_type: "Barcha bino turlari",
    room_type: "Gipsokarton to'siqli xonalar",
    condition: "Oshxona shkaflari, televizor, qozon (boyler) osilganda devor yorilib qulamasligi uchun",
    formula: null,
    calculation_example: "Oshxona shkafi idishlar bilan 60-80 kg yuklanadi. GKL profil karkasi ichiga oldindan 18-20 mm li qalin fanera yoki yog'och brus ipoteka o'rnatiladi.",
    practical_note: "Karkas montaji bosqichida dizayner mebel va televizor joyini aniq ko'rsatuvchi 'Zakladnye' chizmasini ustalarga topshirishi shart.",
    architect_note: "Balandligi 3 metrdan ortiq GKL to'siqlarda 0.6 mm qalinlikdagi Knauf UA kuchaytirilgan profillari ishlatiladi.",
    source_document_number: "QMQ 2.01.03-19",
    source_band: "Konstruktiv talab",
    source_table: null,
    keywords: ["gipsokarton", "GKL", "zakladnaya", "og'ir shkaf", "нагрузка на гипсокартон"],
    status: "AMALDA",
    order_index: 191
  },
  {
    title: "Yotoqxonada pardozlash materiallarining ekologik va xavfsizlik toifasi",
    slug: "yotoqxona-pardoz-ekologik-xavfsizlik-toifasi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Ekologiya va salomatlik",
    data_type: "norma",
    normative_value: "Emissiya klassi E1 (formaldegid emissiyasi <= 0.124 mg/m³)",
    unit: "klass (E1 / E0)",
    building_type: "Turar joylar va bolalar muassasalari",
    room_type: "Yotoqxona, bolalar xonasi",
    condition: "Mebel (DSP, MDF), laminat, bo'yoq va oboylardan zaharli gazlar ajralmasligi uchun",
    formula: null,
    calculation_example: "E2 toifasidagi arzon texnik DSP dan uy ichida mebel yasash qat'iyan taqiqlanadi (surunkali allergiya va astmaga sabab bo'ladi).",
    practical_note: "Devor bo'yog'i suv-dispersiyali (vodno-dispersionnaya), hidsiz va formaldegidsiz bo'lishi shart.",
    architect_note: "Bolalar mebeli uchun xalqaro 'Blue Angel' yoki E0 ekologik sertifikatiga ega materiallar tavsiya etiladi.",
    source_document_number: "O'z DSt 3524:2021",
    source_band: "4-bob",
    source_table: null,
    keywords: ["ekologiya", "E1 klass", "formaldegid", "zararsiz bo'yoq", "экологичность материалов"],
    status: "AMALDA",
    order_index: 192
  },
  {
    title: "Interyerda ranglar va shift yorug'lik qaytarish koeffitsienti",
    slug: "interyer-ranglari-yoruglik-qaytarish-koeffitsienti",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Optika va ranglar",
    data_type: "tavsiya",
    normative_value: "Oq shift: 70 - 80% | Och devor: 50 - 60% | Pol: 15 - 30%",
    unit: "% nur qaytarish (LRV)",
    building_type: "Barcha turar joy va ofislar",
    room_type: "Barcha xonalar",
    condition: "Xona tabiiy va sun'iy yorug'ligini tejash hamda vizual kengaytirishda",
    formula: null,
    calculation_example: "Oq matoviy shift quyosh va lampa nurini 80% qaytarib butun xonaga tarqatadi. Qora yoki to'q shift esa nurning 85% ini yutib xonani qorong'ilashtiradi.",
    practical_note: "Kichik va shimolga qaragan xonalarda sovuq kulrang o'rniga iliq qaymoqrang, och qumrang tonlar xonani ancha yorug' va issiq ko'rsatadi.",
    architect_note: "LRV (Light Reflectance Value) ko'rsatkichi me'moriy bo'yoq kataloglarida har bir rang kodi yonida rasman ko'rsatiladi.",
    source_document_number: "QMQ 2.01.05-19",
    source_band: "Yorug'lik qoidalari",
    source_table: null,
    keywords: ["LRV", "nur qaytarish", "oq shift", "ranglar", "коэффициент отражения"],
    status: "AMALDA",
    order_index: 193
  },
  {
    title: "Ofis va konferens-zallarda xona reverberatsiya vaqti (akustika me'yori)",
    slug: "ofis-konferens-zal-reverberatsiya-vaqti-akustika",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Akustika",
    data_type: "norma",
    normative_value: "0.6 - 0.8",
    unit: "soniya (reverberatsiya vaqti T)",
    building_type: "Ofislar, muzokara xonalari (meeting room), kinoteatrlar, darsxonalar",
    room_type: "Muzokara va konferens xonalari",
    condition: "Ovoz aks-sadosi (exo) bo'lmasligi va nutq so'zlari aniq tushunilishi uchun",
    formula: "T = 0.161 × V / A  (Sabine formulasi: V - hajm, A - tovush yutish yuzasi)",
    calculation_example: "Devorlari faqat shisha va beton bo'lgan xonada aks-sado T=1.5 soniyadan oshadi (gaplashganda g'o'ng'illash paydo bo'ladi).",
    practical_note: "Akustik gilam (kovrolin), yumshoq pardalar va devorga akustik kigiz/panellar (akusticheskiy fetr) o'rnatish orqali T=0.7 soniyaga tushiriladi.",
    architect_note: "Zoom / video-konferensiya xonalarida akustik shift (Armstrong Akustik yoki parolon panellar) majburiy shartdir.",
    source_document_number: "QMQ 2.01.08-96*",
    source_band: "3.2-band",
    source_table: null,
    keywords: ["reverberatsiya", "exo", "akustika", "meeting room", "время реверберации"],
    status: "AMALDA",
    order_index: 194
  },
  {
    title: "Sanuzel ko'zgusi oldida yoritishning optimal joylashuvi",
    slug: "sanuzel-kozgusi-yoritish-optimal-joylashuvi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Yoritish va ko'zgular",
    data_type: "tavsiya",
    normative_value: "Ko'zguning ikki yonidan (yuz sathida) 1.5 - 1.6 m balandlikda diffuz nur",
    unit: "ergonomik tavsiya",
    building_type: "Turar joylar va mehmonxonalar",
    room_type: "Vanna xonasi rakovina zonasi",
    condition: "Yuzni soqol olish va makiyaj qilishda yuzga soyalar tushirmaslik uchun",
    formula: null,
    calculation_example: "Faqat tepadan bitta chiroq qo'yilsa — qosh, burun va iyak ostida qora soyalar paydo bo'lib, inson yuzi xira va charchagan ko'rinadi.",
    practical_note: "Ko'zgu orqasidan chiqadigan perimetral LED lenta yoki ko'zguning ikki chetidagi vertikal chiroqlar (bra) eng to'g'ri yechimdir.",
    architect_note: "Yorug'lik harorati 3000-4000K (tabiiy oq) va CRI >= 90 bo'lishi yuz rangini buzmasdan aniq ko'rsatadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Dizayn tavsiyasi",
    source_table: null,
    keywords: ["ko'zgu chirog'i", "makiyaj nuri", "vanna bra", "zerkalo podsvetka", "подсветка зеркала"],
    status: "AMALDA",
    order_index: 195
  },
  {
    title: "Pol plitkasi (kafel / keramogranit) choklari (zatirka choki) kengligi",
    slug: "plitka-keramogranit-choki-kengligi-standarti",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Plitka yotqizish qoidalari",
    data_type: "tavsiya",
    normative_value: "Rektifikatsiyalangan keramogranit: 1.5 - 2.0 mm | Oddiy kafel: 2.5 - 3.0 mm",
    unit: "mm (chok kengligi)",
    building_type: "Barcha bino turlari",
    room_type: "Pol va devor plitkalari",
    condition: "Bino qisqarishi va harorat o'zgarishida plitka yorilib ko'chib ketmasligi uchun",
    formula: null,
    calculation_example: "Mutlaqo choksiz (0 mm) plitka terish xato! Harorat o'zgarganda plitkalar bir-birini qisib, yorib yuboradi.",
    practical_note: "Epoksidli zatirka sementliga qaraganda suv, yog' va kirlarni mutlaqo shimib olmaydi, mog'orlamaydi va 20 yil rangini saqlaydi.",
    architect_note: "Katta formatli (masalan 600×1200 mm) plitkalar uchun 1.5 mm li SVP (sistema vyravnivaniya plitki) qisqichlari bilan terish mukammal tekislik beradi.",
    source_document_number: "QMQ 2.03.01-96",
    source_band: "4.8-band",
    source_table: null,
    keywords: ["plitka choki", "zatirka", "1.5 mm", "keramogranit", "шов плитки"],
    status: "AMALDA",
    order_index: 196
  },
  {
    title: "Gipsokarton shiftlarda devor bo'ylab yoriqlarning oldini olish (soya profili)",
    slug: "gipsokarton-shift-yorilish-oldini-olish-soya-profili",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Shift konstruksiyalari",
    data_type: "tavsiya",
    normative_value: "Devor bilan GKL shift orasida 10-15 mm li soya choki (tenevoy profil) qo'llash",
    unit: "mm chok",
    building_type: "Ko'p qavatli yangi yangi binolar (bino o'tirishi davrida)",
    room_type: "Barcha xonalar shifti",
    condition: "Yangi bino 2-3 yil davomida tebranib o'tirganda burchakdagi suvoq yorilib ketmasligi uchun",
    formula: null,
    calculation_example: "Devorga qattiq qotirib shpaklyovka qilingan shift burchaklari binoning mikro-harakatlarida darhol chiziq bo'lib yoriladi.",
    practical_note: "Soya profili (masalan Prozet, Kraab) shiftni devordan ajratib qo'yadi va mikroyoriqlar paydo bo'lishining oldini 100% oladi.",
    architect_note: "Klassik interyerda esa bu tutashuv burchak bageti (gantel / karniz) bilan yopiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["tenevoy shift", "gipsokarton yorilishi", "soya choki", "shpaklyovka", "теневой потолок"],
    status: "AMALDA",
    order_index: 197
  },
  {
    title: "Interyer xonalarida havo harorati va nisbiy namlikning sanitariya normasi",
    slug: "xona-harorati-va-nisbiy-namlik-sanitariya-normasi",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Mikroklimat",
    data_type: "norma",
    normative_value: "Harorat: 20 - 22°C (qishda) | Nisbiy namlik: 40% - 60%",
    unit: "°C va % namlik",
    building_type: "Turar joylar va bolalar xonalari",
    room_type: "Yotoqxona, bolalar xonasi, mehmonxona",
    condition: "Inson salomatligi va immunitetini saqlash uchun",
    formula: null,
    calculation_example: "Qishda isitish radiatorlari havoni 20% gacha quritib yuboradi — natijada burun shilliq qavati quriydi va viruslar tez yuqadi.",
    practical_note: "Qish mavsumida ultratovushli yoki bug'li havo namlagich (uvlajnitel vozduxa) ishlatish orqali namlikni kamida 45-50% da ushlab turish tavsiya etiladi.",
    architect_note: "Namlik 65-70% dan oshib ketsa devorlarda qora mog'or (plesen) rivojlanish xavfi tug'iladi.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "2.1-band",
    source_table: "2.1-jadval",
    keywords: ["harorat 22", "namlik 50 foiz", "mikroklimat", "uvlajnitel", "влажность воздуха"],
    status: "AMALDA",
    order_index: 198
  },
  {
    title: "Kichik maydonli studiya va xonalarni vizual kengaytirishning me'moriy uslublari",
    slug: "kichik-xonani-vizual-kengaytirish-uslublari",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Optik illyuziyalar",
    data_type: "tavsiya",
    normative_value: "Ko'zgu panellari, shiftgacha eshiklar, bir xil uzluksiz pol qoplamasi",
    unit: "arxitektura uslubi",
    building_type: "Ixcham kvartiralar, studiyalar (25-45 m²)",
    room_type: "Kichik xonalar",
    condition: "Tor joyni vizual keng va yorug' ko'rsatishda",
    formula: null,
    calculation_example: "1) Butun kvartirada (sanuzeldan tashqari) bitta pol qoplamasini ostonasiz uzluksiz yotqizish maydonni yaxlit ko'rsatadi. 2) Baland (2.3-2.4 m) eshiklar shiftni baland ko'rsatadi.",
    practical_note: "Derazaga qarama-qarshi devorga katta ko'zgu qo'yilishi xonaga ikkinchi deraza ochilgandek taassurot qoldiradi.",
    architect_note: "Ko'p mayda mayda mebellar o'rniga bitta devor bo'ylab yaxlit shiftgacha bo'lgan yopiq monoxrom shkaf tizimi xonani toza va tartibli saqlaydi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["kichik xona", "vizual kengaytirish", "studiya dizayni", "ko'zgu", "дизайн маленькой комнаты"],
    status: "AMALDA",
    order_index: 199
  },
  {
    title: "O'zbekistonda xonadonlararo seysmik xavfsizlik va devorlarni noqonuniy buzish javobgarligi",
    slug: "seysmik-xavfsizlik-va-devor-buzish-taqiqlari",
    category: "Interyer me'yorlari va amaliy tavsiyalar",
    subcategory: "Seysmik xavfsizlik va qonunchilik",
    data_type: "norma",
    normative_value: "Monolit ustunlar, rigellar, diafragmalar va ko'taruvchi g'isht devorlarni buzish QAT'IYAN TAQIQLANADI",
    unit: "davlat qonuni",
    building_type: "Ko'p qavatli barcha turar joylar (7, 8, 9 ball seysmik zonalarda)",
    room_type: "Barcha xonalar",
    condition: "Zilzila paytida butun binoning qulab tushishining oldini olish uchun",
    formula: null,
    calculation_example: "Hatto 1-qavatdagi bitta do'kon egasi monolit devor yoki ustunni kesib tashlasa — 9 qavatli butun dom zilzilada kartadek qulashi mumkin.",
    practical_note: "Faqat yuk ko'tarmaydigan (samonesushchiy) yengil gipsokarton yoki 10 sm lik gazoblok to'siqlarni ruxsatnoma bilan o'zgartirish mumkin.",
    architect_note: "O'zbekiston Respublikasi Jinoyat va Ma'muriy kodekslariga binoan bino konstruksiyasiga noqonuniy zarar yetkazish jinoiy javobgarlikka sabab bo'ladi.",
    source_document_number: "QMQ 2.01.03-19",
    source_band: "1.4-band",
    source_table: null,
    keywords: ["seysmik xavfsizlik", "devor buzish", "nesushchiy devor", "zilzilabardoshlik", "сейсмостойкость перепланировка"],
    status: "AMALDA",
    order_index: 200
  }
];

module.exports = { SEED_TOPICS_BATCH4 };
