// ============================================================================
// BATCH 3: Zinalar | Pandus va inklyuzivlik | Sanuzellar (Topics 106-155)
// Rasmiy O'zbekiston standartlari (SHNQ 2.08.01-24, SHNQ 2.01.02-04, SHNQ 2.01.18-23, QMQ 2.04.01-98)
// ============================================================================

const SEED_TOPICS_BATCH3 = [
  // --- 7. Zinalar va vertikal aloqa (106-122) ---
  {
    title: "Turar joy binolarida zinapoya pog'onasi balandligi (podstupenok) normasi",
    slug: "zina-pogonasi-balandligi-podstupenok-normasi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Pog'ona o'lchamlari",
    data_type: "norma",
    normative_value: "150 - 180",
    unit: "mm (15 - 18 sm)",
    building_type: "Ko'p qavatli va yakka tartibdagi turar joylar",
    room_type: "Qavatlararo zinapoya",
    condition: "Asosiy kirish va evakuatsiya zinalarida",
    formula: null,
    calculation_example: "Qavat balandligi H=3000 mm bo'lsa, 17 ta pog'ona har biri h = 3000 / 17 ≈ 176 mm qilib loyihalanadi.",
    practical_note: "Bitta marsh ichidagi barcha pog'onalarning balandligi mutlaqo bir xil bo'lishi shart! Atigi 1 sm farq ham odamning qoqilib yiqilishiga sabab bo'ladi.",
    architect_note: "Yakka tartibdagi uylarda (chordoq va podvalga tushishda) balandlikni 190 mm gacha oshirishga ruxsat etiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.11-band",
    source_table: "3.3-jadval",
    keywords: ["zina balandligi", "podstupenok", "pog'ona", "lestnitsa", "высота подступенка"],
    status: "AMALDA",
    order_index: 106
  },
  {
    title: "Zinapoya pog'onasi kengligi (prostup) normativ o'lchami",
    slug: "zina-pogonasi-kengligi-prostup-normasi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Pog'ona o'lchamlari",
    data_type: "norma",
    normative_value: "280 - 300",
    unit: "mm (28 - 30 sm)",
    building_type: "Barcha bino turlari",
    room_type: "Asosiy zinapoya marshi",
    condition: "Inson oyog'i to'liq sig'ishi va pastga tushish xavfsizligi uchun",
    formula: null,
    calculation_example: "Kattalar oyog'i (41-43 razmer) uzunligi 27-28 sm. 30 sm kenglik oyoq tovonidan barmoqlarigacha to'liq tayanishni kafolatlaydi.",
    practical_note: "Tor pog'ona (25 sm dan kam) pastga tushayotganda tovon tayanchsiz qolib, sirpanib ketish xavfini keskin oshiradi.",
    architect_note: "Agar joy torlik qilsa, yuqori pog'ona pastkisining ustiga 20-30 mm osiltirib (sves prostupi) bajariladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.11-band",
    source_table: "3.3-jadval",
    keywords: ["zina kengligi", "prostup", "pog'ona eni", "lestnitsa prostup", "ширина проступи"],
    status: "AMALDA",
    order_index: 107
  },
  {
    title: "Zina loyihalashning klassik xavfsizlik va qulaylik formulasi (Blondel formulasi)",
    slug: "zina-loyihalash-blondel-formulasi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Hisoblash usullari",
    data_type: "hisoblash",
    normative_value: "2h + b = 600 - 640 mm",
    unit: "mm (qulay qadam uzunligi)",
    building_type: "Barcha bino turlari",
    room_type: "Ixtiyoriy zinapoya konstruksiyasi",
    condition: "h - pog'ona balandligi, b - pog'ona kengligi",
    formula: "2h + b = 620 mm  (ideal o'rtacha)",
    calculation_example: "Agar pog'ona balandligi h=160 mm bo'lsa: b = 620 - 2×160 = 300 mm. Formula to'liq bajarildi (2×160 + 300 = 620 mm).",
    practical_note: "Qulaylik formulasi: b - h = 120 mm (masalan 290 - 170 = 120). Xavfsizlik formulasi: b + h = 460 mm (masalan 290 + 170 = 460).",
    architect_note: "Loyiha chizayotganda ushbu formulani tekshirmasdan tasodifiy sonlar bilan zina qo'yish qo'pol professional xato hisoblanadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.11-band",
    source_table: null,
    keywords: ["blondel formulasi", "zina hisobi", "2h+b", "qadam uzunligi", "формула лестницы"],
    status: "AMALDA",
    order_index: 108
  },
  {
    title: "Asosiy zinapoya marshining qulay qiyalik burchagi",
    slug: "zina-marshi-qulay-qiyalik-burchagi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Qiyalik burchagi",
    data_type: "norma",
    normative_value: "1:2 dan 1:1.75 gacha (26° - 33°)",
    unit: "daraja (°)",
    building_type: "Ko'p qavatli turar joy va jamoat binolari",
    room_type: "Asosiy qavatlararo zina",
    condition: "Kundalik doimiy foydalanish uchun",
    formula: "tg α = h / b = 150 / 300 = 0.5 (α = 26.5°)",
    calculation_example: "27° — eng qulay ideal burchak. 35° dan oshsa — tik (charchatuvchi). 45° dan oshsa — zinapoya emas, narvon (strelmyanka) hisoblanadi.",
    practical_note: "Qariyalari va bolalari bor oilalar uchun kottejlarda 28-30° qiyalik optimal qulaylik beradi.",
    architect_note: "Podval va chordoqqa chiqishda 1:1.25 (40-42°) gacha ruxsat etiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.11-band",
    source_table: "3.3-jadval",
    keywords: ["zina qiyaligi", "burchak", "27 daraja", "uksus lestnitsy", "уклон лестницы"],
    status: "AMALDA",
    order_index: 109
  },
  {
    title: "Turar joy binosi zinapoya marshining minimal toza kengligi",
    slug: "turar-joy-zina-marshi-minimal-kengligi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Marsh o'lchamlari",
    data_type: "norma",
    normative_value: "1.05 - 1.20",
    unit: "m (1050 - 1200 mm)",
    building_type: "Ko'p xonadonli turar joy binolari",
    room_type: "Zinapoya marshi",
    condition: "Perila va devor orasidagi toza masofa",
    formula: null,
    calculation_example: "2 qavatli uylarda kamida 1.05 m; 3 va undan yuqori qavatli ko'p xonadonli uylarda kamida 1.20 m bo'lishi shart.",
    practical_note: "Zinapoyadan ikki kishi bir vaqtda to'qnashmasdan o'ta olishi va zambil (nosilka) erkin burilishi kerak.",
    architect_note: "Perila tutqichi devordan marsh ichiga 8-10 sm kirib turadi; toza kenglik tutqichdan (periladan) devorgacha o'lchanadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.11-band",
    source_table: null,
    keywords: ["marsh kengligi", "zina eni", "1.05 m", "1.20 m", "ширина марша"],
    status: "AMALDA",
    order_index: 110
  },
  {
    title: "Yakka tartibdagi hovli va kottejlar ichki zinapoyasining minimal kengligi",
    slug: "kottej-ichki-zina-minimal-kengligi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Marsh o'lchamlari",
    data_type: "norma",
    normative_value: "0.9",
    unit: "m (900 mm)",
    building_type: "Yakka tartibdagi 2-3 qavatli uylar (kottejlar)",
    room_type: "Kottej ichki zinasi",
    condition: "Bitta oila yashaydigan shaxsiy uy ichida",
    formula: null,
    calculation_example: "Devordagi o'yiq kamida 1000 mm qoldiriladi, perila o'rnatilgach toza o'tish 900 mm ni tashkil qiladi.",
    practical_note: "Mebel va matraslarni 2-qavatga olib chiqish qulay bo'lishi uchun amaliyotda 1000-1100 mm tavsiya etiladi.",
    architect_note: "Zina tagida kiyim shkafi yoki kichik sanuzel joylashtirish mumkin (agar toza balandlik kamida 2.0 m bo'lsa).",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.11-band",
    source_table: null,
    keywords: ["kottej zinasi", "uy zinasi", "900 mm", "лестница в коттедже"],
    status: "AMALDA",
    order_index: 111
  },
  {
    title: "Zinapoya maydonchasining (ploshchadka) minimal kengligi",
    slug: "zina-maydonchasi-minimal-kengligi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Maydonchalar",
    data_type: "norma",
    normative_value: "Zinapoya marshining enidan kam bo'lmasligi shart (kamida 1.2 - 1.3 m)",
    unit: "m",
    building_type: "Barcha bino turlari",
    room_type: "Qavatlararo va qavat zinalari maydonchasi",
    condition: "Marshlar tutashgan burilish maydonchasida",
    formula: "L_maydoncha >= B_marsh",
    calculation_example: "Marsh kengligi 1.20 m bo'lsa, qavatlararo burilish maydonchasi chuqurligi kamida 1.20 m (yaxshisi 1.30-1.40 m) bo'lishi shart.",
    practical_note: "Maydonchada lift eshigi joylashsa, maydoncha kengligi kamida 1.6 - 2.1 m bo'lishi talab qilinadi.",
    architect_note: "Zinapoya maydonchasida hech qanday quvur, elektrshit yoki to'siq bo'lmasligi lozim (evakuatsiya yo'li).",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.11-band",
    source_table: null,
    keywords: ["zina maydonchasi", "ploshchadka", "evakuatsiya", "площадка лестницы"],
    status: "AMALDA",
    order_index: 112
  },
  {
    title: "Zinapoya to'siqlari va tutqichlarining (perila) minimal balandligi",
    slug: "zina-perila-tutqich-minimal-balandligi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Xavfsizlik to'siqlari",
    data_type: "norma",
    normative_value: "0.9",
    unit: "m (900 mm)",
    building_type: "Turar joy va jamoat binolari",
    room_type: "Zinapoya marshi va maydonchasi to'sig'i",
    condition: "Pog'ona burnidan tutqichning yuqori sirtigacha vertikal o'lcham",
    formula: null,
    calculation_example: "Kattalar uchun 900 mm; 3 qavatdan baland umumiy ochiq atriumlarda xavfsizlik uchun 1100-1200 mm olinadi.",
    practical_note: "Tutqich qo'l bilan mahkam ushlanadigan qulay diametrda (dumaloq 40-50 mm yoki to'rtburchak 40x60 mm) bo'lishi kerak.",
    architect_note: "Tutqich marsh boshlanishidan oldin va tugashidan keyin 300 mm gorizontal davom etishi va uchi pastga bukilgan bo'lishi talab etiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.12-band",
    source_table: null,
    keywords: ["perila balandligi", "tutqich", "900 mm", "zina to'sig'i", "высота перил"],
    status: "AMALDA",
    order_index: 113
  },
  {
    title: "Maktab va bolalar bog'chalarida zina perilasi balandligi va qo'shimcha tutqich",
    slug: "bolalar-muassasasi-zina-perilasi-balandligi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Xavfsizlik to'siqlari",
    data_type: "norma",
    normative_value: "Asosiy: 1.2 m (1200 mm) | Bolalar tutqichi: 0.5 - 0.7 m",
    unit: "m",
    building_type: "Maktabgacha ta'lim (bog'cha), maktab, bolalar shifoxonasi",
    room_type: "Barcha zinapoyalar",
    condition: "Bolalar tushib ketishining mutlaqo oldini olish uchun",
    formula: null,
    calculation_example: "Devor bo'ylab ikkita parallel tutqich o'rnatiladi: biri 50 sm balandlikda (kichik bolalar uchun), ikkinchisi 70 sm da (o'quvchilar uchun), asosiy to'siq esa 120 sm.",
    practical_note: "To'siqda gorizontal tirqishlar (bolalar narvondek tirmashib chiqishi mumkin bo'lgan qismlar) bo'lishi qat'iyan taqiqlanadi!",
    architect_note: "Faqat vertikal sterjenlar qo'yiladi va oraliq qat'iy nazorat qilinadi.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "3.8-band",
    source_table: null,
    keywords: ["bolalar perilasi", "bog'cha zinasi", "1200 mm", "xavfsiz perila", "перила детский сад"],
    status: "AMALDA",
    order_index: 114
  },
  {
    title: "Zina to'sig'i vertikal elementlari (balyasinlar) orasidagi maksimal masofa",
    slug: "zina-balyasina-vertikal-element-masofasi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Xavfsizlik to'siqlari",
    data_type: "norma",
    normative_value: "ko'pi bilan 100 - 120",
    unit: "mm (10 - 12 sm)",
    building_type: "Barcha bino turlari",
    room_type: "Zinapoya to'siqlari",
    condition: "Kichik bolaning boshi oraliqqa tiqilib qolmasligi yoki tushib ketmasligi uchun",
    formula: "L_tirqish <= 120 mm (bolalar muassasasida <= 100 mm)",
    calculation_example: "Balyasinlar orasi 15 sm qilinsa — 2 yoshli bolaning gavdasi o'tib, pastga qulash xavfi paydo bo'ladi.",
    practical_note: "Shisha to'siq ishlatilsa — yaxlit tripleks (kamida 10 mm) o'rnatiladi, hech qanday tirqish qolmaydi.",
    architect_note: "Ekspertiza va davlat qabul komissiyasi ushbu 120 mm lik o'lchamni qat'iy tekshiradi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.12-band",
    source_table: null,
    keywords: ["balyasina masofasi", "120 mm", "xavfsizlik", "perila orasi", "расстояние между балясинами"],
    status: "AMALDA",
    order_index: 115
  },
  {
    title: "Bitta zinapoya marshidagi pog'onalar sonining minimal va maksimal chegarasi",
    slug: "bitta-marshdagi-pogonalar-soni-chegarasi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Marsh tuzilishi",
    data_type: "norma",
    normative_value: "kamida 3 ta, ko'pi bilan 16 - 18 ta",
    unit: "dona pog'ona",
    building_type: "Barcha bino turlari",
    room_type: "To'g'ri zinapoya marshi",
    condition: "Inson charchamasligi va ko'rish reflekslari qoidasi",
    formula: "3 <= N_pogona <= 18",
    calculation_example: "1 yoki 2 ta pog'onani odam sezmay qoqilib ketadi (kamida 3 ta bo'lishi shart). 18 tadan ortiq bo'lsa — oraliq maydoncha (otdix) bilan 2 ga bo'linadi.",
    practical_note: "Agar qavat balandligi 3.6 m bo'lib 20 ta pog'ona kerak bo'lsa, albatta oraliq maydoncha bilan 10 + 10 qilib ikki marshli zina loyihalanadi.",
    architect_note: "Bitta marsh ichida pog'onalar toq sonli (masalan 9, 11, 15) bo'lishi tavsiya etiladi (odam qaysi oyog'i bilan chiqishni boshlasa, xuddi shu oyoq bilan maydonchaga qadam qo'yadi).",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.11-band",
    source_table: null,
    keywords: ["pog'onalar soni", "kamida 3 ta", "18 pog'ona", "zina marshi", "количество ступеней"],
    status: "AMALDA",
    order_index: 116
  },
  {
    title: "Zinapoyadan o'tishda toza vertikal bo'shliq balandligi (bosh urilmasligi)",
    slug: "zina-ustidagi-toza-vertikal-boshliq-balandligi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Vertikal parametrlar",
    data_type: "norma",
    normative_value: "kamida 2.0",
    unit: "m (2000 mm)",
    building_type: "Barcha bino turlari",
    room_type: "Zinapoya marshi usti",
    condition: "Ixtiyoriy pog'onaning burnidan to ustki orayopma (shift/balka) pastigacha",
    formula: "H_vertikal >= 2000 mm (yaxshisi 2100 mm)",
    calculation_example: "Zina ustidagi devor yoki ikkinchi qavat orayopmasi o'yig'i tor bo'lsa, baland bo'yli odam (185-190 sm) tushayotganda boshini shipga urib oladi.",
    practical_note: "Qora qurilishda 2.15-2.20 m qoldirilishi lozim, chunki shiftga gipsokarton va pog'onaga marmar/yog'och qo'yilgach 10-15 sm yo'qoladi.",
    architect_note: "Zinapoya o'yig'ining uzunligini (proyom v perekrytii) hisoblashda eng birinchi tekshiriladigan me'moriy qoida.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.11-band",
    source_table: null,
    keywords: ["bosh urilmasligi", "zina balandligi", "2 metr", "proyom", "высота прохода лестницы"],
    status: "AMALDA",
    order_index: 117
  },
  {
    title: "Evakuatsiya zinapoya kataklarining o'tga chidamlilik chegarasi",
    slug: "evakuatsiya-zinasi-otga-chidamlilik-chegarasi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Yong'in xavfsizligi",
    data_type: "norma",
    normative_value: "Konstruksiya: REI 60 (1 soat) | Devorlari: REI 120 - 150",
    unit: "minut (60-150 daqiqa)",
    building_type: "Barcha ko'p qavatli jamoat va turar joy binolari",
    room_type: "Evakuatsiya zinapoya kataklari",
    condition: "Yong'in paytida odamlar xavfsiz tushishi va konstruksiya qulamasligi uchun",
    formula: null,
    calculation_example: "Zinapoya marshlari faqat yonmaydigan materiallardan (temir-beton, himoyalangan metall) yasaladi.",
    practical_note: "Evakuatsiya zinalariga yonuvchan yog'och, plastmassa yoki gilam qoplamalari yotqizish qat'iyan taqiqlanadi.",
    architect_note: "Zinapoya katagi ichida gaz quvurlari, yonuvchan suyuqliklar quvurlari va umumiy elektr kabellari tranziti taqiqlanadi.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "2.10-band",
    source_table: "2.1-jadval",
    keywords: ["REI 60", "zina yong'in", "evakuatsiya zinasi", "ognezashchita", "огнестойкость лестниц"],
    status: "AMALDA",
    order_index: 118
  },
  {
    title: "Spiral (vintli) va aylanma zinalarni qo'llashdagi me'yoriy cheklovlar",
    slug: "spiral-vintli-zina-qollash-cheklovlari",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Maxsus zina turlari",
    data_type: "norma",
    normative_value: "Faqat ichki qo'shimcha (dekorativ) zina sifatida; evakuatsiya uchun taqiqlanadi",
    unit: "cheklov",
    building_type: "Turar joylar (dupleks kvartira, kottej)",
    room_type: "Ichki ikkinchi darajali zina",
    condition: "Odamlar oqimi kam bo'lgan individual xonalarda",
    formula: null,
    calculation_example: "Burilish markazidan 200 mm masofada pog'ona kengligi kamida 100 mm, harakatlanish o'qi bo'yicha (o'rtada) kamida 250 mm bo'lishi shart.",
    practical_note: "Vintli zinadan katta mebel, muzlatgich yoki nosilka olib chiqish imkonsiz.",
    architect_note: "Jamoat binolarida yoki asosiy evakuatsiya yo'lida vintli zina loyihalash davlat ekspertizasidan aslo o'tmaydi.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.16-band",
    source_table: null,
    keywords: ["vintli zina", "spiral lestnitsa", "cheklov", "evakuatsiya taqiqi", "винтовая лестница"],
    status: "AMALDA",
    order_index: 119
  },
  {
    title: "Zinapoya pog'onalari qoplamasining sirpanishga qarshi xususiyati",
    slug: "zina-pogonasi-sirpanishga-qarshi-xususiyati",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Xavfsizlik qoplamalari",
    data_type: "tavsiya",
    normative_value: "Sirpanish qarshiligi koeffitsienti R10 - R11 (nam sharoitda)",
    unit: "DIN 51130 klassi",
    building_type: "Barcha bino turlari (ayniqsa tashqi kirish zinalari)",
    room_type: "Zinapoya pog'onalari",
    condition: "Yomg'ir, qor va pol yuvilganda odam toyib yiqilmasligi uchun",
    formula: null,
    calculation_example: "Yaltiroq (glyantsevy) silliq kafel/marmar zinaga qo'yilsa, qishda u yaxmalakka aylanadi. Pog'ona burniga kamida 5 sm li abraziv tasma yoki rezina profil o'rnatiladi.",
    practical_note: "Tashqi kirish zinalarida elektr isitish kabeli (kabelny obogrev) o'rnatish qishda muzlashni bartaraf etadi.",
    architect_note: "Pog'onaning birinchi va oxirgi qadamiga ko'zi ojizlar uchun sariq kontrast ogohlantiruvchi chiziq bo'yash shaharsozlik talabidir.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.15-band",
    source_table: null,
    keywords: ["sirpanishga qarshi", "R10", "antiskolzenie", "muzlama", "противоскользящее покрытие"],
    status: "AMALDA",
    order_index: 120
  },
  {
    title: "Kottejda zina ostidagi bo'shliqdan (podlestnichnoe prostranstvo) foydalanish",
    slug: "zina-ostidagi-boshliqdan-foydalanish-qoidalari",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Interyer ergonomikasi",
    data_type: "tavsiya",
    normative_value: "Toza balandlik kamida 1.9 m bo'lganda to'laqonli xona (sanuzel/garderob)",
    unit: "ergonomik me'yor",
    building_type: "Kottejlar, hovli uylar, duplekslar",
    room_type: "Zina osti maydoni",
    condition: "Foydali maydonni tejash uchun",
    formula: null,
    calculation_example: "Balandlik 1.9-2.2 m bo'lgan qismiga unitaz yoki kir yuvish mashinasi qo'yiladi; 1.0-1.5 m bo'lgan past qismiga esa tortmali kiyim javonlari (vydvijnye yashiki) yasaladi.",
    practical_note: "Ko'p qavatli binolarning umumiy evakuatsiya zinapoya katagi ostida omborxona qilish yoki buyum saqlash yong'in qoidalari bo'yicha qat'iyan man etiladi!",
    architect_note: "Faqat yakka tartibdagi shaxsiy uy ichida zina ostini yopib ishlatishga ruxsat bor.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["zina osti", "garderob zina osti", "podlestnichnoe", "подлестничное пространство"],
    status: "AMALDA",
    order_index: 121
  },
  {
    title: "Tashqi kirish zinapoyasi (krilso) maydonchasining eshikka nisbatan sathi",
    slug: "tashqi-kirish-krilso-maydonchasi-sathi",
    category: "Zinalar va vertikal aloqa",
    subcategory: "Kirish guruhlari",
    data_type: "norma",
    normative_value: "Ichki pol sathidan 20 - 50 mm (2 - 5 sm) pastda",
    unit: "mm",
    building_type: "Barcha bino turlari",
    room_type: "Tashqi kirish maydonchasi (krilso)",
    condition: "Yomg'ir va erigan qor suvlari bino ichiga oqib kirmasligi uchun",
    formula: null,
    calculation_example: "Tashqi maydoncha poldan 3 sm past qilinadi va tashqariga qarab 1-2% nishablik beriladi.",
    practical_note: "Krilso maydonchasining eni eshik kengligidan kamida 1.5 baravar katta bo'lishi kerak (eshik ochilganda odam orqaga tushib ketmasligi uchun).",
    architect_note: "Krilso ustiga yog'ingarchilikdan himoyalovchi bostirma (kozyorok) o'rnatilishi shart.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.13-band",
    source_table: null,
    keywords: ["krilso", "kirish zinasi", "kozyorok", "porog", "крыльцо здания"],
    status: "AMALDA",
    order_index: 122
  },

  // --- 8. Pandus va inklyuziv loyihalash (123-138) ---
  {
    title: "Bino kirishidagi statsionar pandusning maksimal ruxsat etilgan qiyaligi",
    slug: "statsionar-pandus-maksimal-qiyaligi-normasi",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Pandus qiyaligi",
    data_type: "norma",
    normative_value: "1:12 (8% yoki 4.76°)",
    unit: "nisbat (8%)",
    building_type: "Barcha bino va inshootlar",
    room_type: "Bino bosh kirish pandusi",
    condition: "Nogironlar aravachasi o'z kuchi bilan erkin va xavfsiz chiqa olishi uchun",
    formula: "i = H / L <= 1/12 (i - qiyalik, H - ko'tarilish balandligi, L - pandus uzunligi)",
    calculation_example: "Poldan krilsogacha balandlik H = 0.6 m (60 sm) bo'lsa: pandus uzunligi L kamida 0.6 × 12 = 7.2 metr bo'lishi shart.",
    practical_note: "Agar qiyalik 1:10 yoki 1:8 qilinsa — aravachadagi inson orqaga ag'darilib ketadi yoki chiqolmaydi. Bu qoidabuzarlikdir!",
    architect_note: "Balandlik 0.2 m dan kam bo'lgan kichik joylarda istisno tariqasida 1:10 (10%) qiyalik ruxsat etiladi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.2-band",
    source_table: null,
    keywords: ["pandus qiyaligi", "1:12", "8 foiz", "nogironlar pandusi", "уклон пандуса"],
    status: "AMALDA",
    order_index: 123
  },
  {
    title: "Bir marshli pandusning maksimal ko'tarilish balandligi va uzunligi",
    slug: "bir-marshli-pandus-maksimal-kotarilish-balandligi",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Pandus parametrlari",
    data_type: "norma",
    normative_value: "Balandlik: max 0.8 m | Marsh uzunligi: max 9.0 m",
    unit: "m",
    building_type: "Barcha binolar",
    room_type: "Pandus marshi",
    condition: "Inson charchab to'xtashi va dam olishi uchun",
    formula: null,
    calculation_example: "Agar kirish balandligi 1.2 m bo'lsa, uni bitta to'g'ri chiziq qilib bo'lmaydi. 0.6 m ko'tarilgach gorizontal maydoncha (1.5x1.5 m) qo'yilib, so'ng ikkinchi marsh davom ettiriladi.",
    practical_note: "Har 9 metr masofada albatta dam olish maydonchasi bo'lishi shart.",
    architect_note: "Pandusning boshlanishida va tugashida kamida 1.5 × 1.5 m gorizontal burilish maydonchasi ko'zda tutiladi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.3-band",
    source_table: null,
    keywords: ["pandus marshi", "0.8 m ko'tarilish", "9 metr", "maydoncha", "длина марша пандуса"],
    status: "AMALDA",
    order_index: 124
  },
  {
    title: "Bir tomonlama harakatlanadigan pandusning minimal toza kengligi",
    slug: "bir-tomonlama-pandus-minimal-kengligi",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Pandus o'lchamlari",
    data_type: "norma",
    normative_value: "kamida 1.0",
    unit: "m (1000 mm)",
    building_type: "Barcha binolar",
    room_type: "Bir tomonlama harakatlanish pandusi",
    condition: "Ikki tomonlama tutqichlar orasidagi toza masofa",
    formula: null,
    calculation_example: "Devorlar orasidagi kenglik 1.2 m bo'lganda, tutqichlar o'rnatilgach toza 1.0 m masofa qoladi.",
    practical_note: "Pandus juda keng (masalan 1.8 m) bo'lsa ham noqulay, chunki nogiron ikki tomondagi tutqichni bir vaqtda ushlay olmay qoladi.",
    architect_note: "Pandus chetida g'ildirak chiqib ketmasligi uchun balandligi kamida 50 mm (5 sm) bo'lgan himoya bortigi (kolyosootboinik) bo'lishi shart.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.4-band",
    source_table: null,
    keywords: ["pandus kengligi", "1 metr", "bortik", "kolyosootboinik", "ширина пандуса"],
    status: "AMALDA",
    order_index: 125
  },
  {
    title: "Ikki tomonlama harakatlanadigan (uchrashuvli) pandus kengligi",
    slug: "ikki-tomonlama-pandus-minimal-kengligi",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Pandus o'lchamlari",
    data_type: "norma",
    normative_value: "kamida 1.5 - 1.8",
    unit: "m",
    building_type: "Katta savdo markazlari, vokzallar, shifoxonalar",
    room_type: "Asosiy ommaviy pandus",
    condition: "Ikkita aravacha bir-biri bilan to'qnashmasdan o'tishi uchun",
    formula: null,
    calculation_example: "1.8 m kenglikdagi pandus o'rtasiga qo'shimcha bo'luvchi oraliq tutqich (razdelitelny porochen) o'rnatilishi tavsiya etiladi.",
    practical_note: "Katta tirbandlik bo'lgan joylarda pandus yonida alohida odatiy zinapoya ham bo'lishi shart.",
    architect_note: "Tashqi ochiq panduslarga muzlashga qarshi isitish kabeli yotqizilishi xavfsizlikni kafolatlaydi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.4-band",
    source_table: null,
    keywords: ["ikki tomonlama pandus", "1.8 metr", "katta pandus", "двусторонний пандус"],
    status: "AMALDA",
    order_index: 126
  },
  {
    title: "Pandus burilish va dam olish gorizontal maydonchalarining minimal o'lchami",
    slug: "pandus-gorizontal-dam-olish-maydonchasi-olchami",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Maydonchalar",
    data_type: "norma",
    normative_value: "kamida 1.5 × 1.5",
    unit: "m (1500 × 1500 mm)",
    building_type: "Barcha binolar",
    room_type: "Panduslar oraliq va oxirgi maydonchasi",
    condition: "Nogironlar aravachasi 90° yoki 180° ga to'liq burila olishi uchun",
    formula: null,
    calculation_example: "90° buriluvchi pandus maydonchasi kamida 1.5x1.5 m. 180° burilishda maydoncha kengligi kamida pandusning ikki hissa eniga teng bo'lishi kerak.",
    practical_note: "Maydoncha mutlaqo gorizontal bo'lishi kerak, faqat suv oqishi uchun 1% gacha nishablikka ruxsat beriladi.",
    architect_note: "Maydoncha chegarasiga eshik ochilmasligi kerak; agar eshik ochilsa, maydoncha o'lchami eshik radiusi hisobiga kengaytiriladi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.3-band",
    source_table: null,
    keywords: ["pandus maydonchasi", "burilish radiusi", "1.5x1.5", "площадка пандуса"],
    status: "AMALDA",
    order_index: 127
  },
  {
    title: "Pandus tutqichlari (perila) o'rnatiladigan ikkita majburiy balandlik",
    slug: "pandus-tutqichlari-ikkita-majburiy-balandligi",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Tutqichlar va xavfsizlik",
    data_type: "norma",
    normative_value: "Pastki tutqich: 0.7 m (700 mm) | Yuqori tutqich: 0.9 m (900 mm)",
    unit: "m (ikki qator)",
    building_type: "Barcha bino turlari",
    room_type: "Pandusning har ikki tomoni",
    condition: "Aravachadagi insonlar va keksalar ushlab tortishi uchun",
    formula: null,
    calculation_example: "Pastki 70 sm lik tutqich — aravachada o'tirgan odam uchun; yuqori 90 sm lik tutqich — hassa bilan yuradigan insonlar uchun xizmat qiladi.",
    practical_note: "Tutqich profili dumaloq (diametri 30-50 mm) va butun uzunlik bo'ylab uzluksiz bo'lishi shart.",
    architect_note: "Tutqich pandus marshi tugagandan keyin ham gorizontal holatda kamida 300 mm oldinga davom etishi shart.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.6-band",
    source_table: null,
    keywords: ["pandus tutqichi", "70 sm", "90 sm", "ikkita perila", "поручни пандуса"],
    status: "AMALDA",
    order_index: 128
  },
  {
    title: "Pandus chetidagi g'ildirak chiqib ketishiga qarshi bortik (otboynik) balandligi",
    slug: "pandus-chetidagi-himoya-bortigi-balandligi",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Xavfsizlik detallari",
    data_type: "norma",
    normative_value: "kamida 0.05",
    unit: "m (50 mm / 5 sm)",
    building_type: "Barcha bino turlari",
    room_type: "Pandusning ochiq chetlari",
    condition: "Aravacha kichik old g'ildiraklari pandusdan tushib ketmasligi uchun",
    formula: "h_bortik >= 50 mm",
    calculation_example: "Metall yoki beton bordyurcha pandus cheti bo'ylab uzluksiz qilinadi.",
    practical_note: "Agar pandus devorga taqalgan bo'lsa devor tomoniga bortik shart emas; ochiq tomoniga esa qat'iy majburiydir.",
    architect_note: "Bortik ustiga tutqich ustunlari payvandlanadi yoki ankerlanadi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.4-band",
    source_table: null,
    keywords: ["bortik", "otboynik", "50 mm", "kolyosootboinik", "бортик пандуса"],
    status: "AMALDA",
    order_index: 129
  },
  {
    title: "Nogironlar aravachasi to'liq 360° burilishi uchun zarur aylana diametri",
    slug: "nogironlar-aravachasi-burilish-aylanasi-diametri",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Ergonomik bo'shliqlar",
    data_type: "norma",
    normative_value: "kamida 1.5",
    unit: "m (1500 mm diametr)",
    building_type: "Jamoat binolari, maxsus sanuzellar, xonadonlar",
    room_type: "Koridor, lift xoli, moslashtirilgan sanuzel, oshxona",
    condition: "Standart qo'lda harakatlantiriladigan va elektr aravachalar uchun",
    formula: "D_burilish >= 1500 mm",
    calculation_example: "Sanuzel loyihalashda uning ichida diametri 1.5 m bo'lgan erkin toza doira (mebel va asboblarsiz) chizilishi shart.",
    practical_note: "Bu doiraga na unitaz, na rakovina, na dush traypi kirmasligi kerak (ochiq pol maydoni bo'lishi lozim).",
    architect_note: "Arxitektor reja chizganda 1.5 m diametrli shartli aylanani har bir xonaga qo'yib tekshirishi inklyuziv auditning asosi hisoblanadi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "2.3-band",
    source_table: null,
    keywords: ["burilish radiusi", "1.5 metr", "aravacha doirasi", "разворот коляски"],
    status: "AMALDA",
    order_index: 130
  },
  {
    title: "Nogironlar uchun universal moslashtirilgan sanuzelning minimal o'lchamlari",
    slug: "universal-nogironlar-sanuzeli-minimal-olchamlari",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Moslashtirilgan sanuzellar",
    data_type: "norma",
    normative_value: "kamida 2.20 × 1.60 (maydoni kamida 3.5 m²)",
    unit: "m",
    building_type: "Barcha jamoat, savdo, umumiy ovqatlanish va sport binolari",
    room_type: "Imkoniyati cheklanganlar uchun universal sanuzel",
    condition: "Aravachani unitaz yoniga qo'yib o'tirish va rakovinadan foydalanish uchun",
    formula: null,
    calculation_example: "Unitaz bir burchakda emas, devordan 75-80 sm oraliqda qo'yiladi (aravacha yoniga parallel turishi uchun).",
    practical_note: "Eshik kengligi kamida 900 mm va FAQAT TASHQARIGA ochilishi shart (ichkarida qulab tushsa eshikni to'sib qo'ymasligi uchun).",
    architect_note: "Favqulodda yordam chaqirish uchun poldan 20-30 sm balandlikda qizil shnurli signal tugmasi o'rnatiladi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.10-band",
    source_table: null,
    keywords: ["nogironlar sanuzeli", "universal sanuzel", "2.2x1.6", "санузел для МГН"],
    status: "AMALDA",
    order_index: 131
  },
  {
    title: "Nogironlar sanuzelida unitaz yonidagi maxsus tutqichlar (poruchni) parametrlari",
    slug: "nogironlar-unitazi-tutqichlari-parametrlari",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Moslashtirilgan sanuzellar",
    data_type: "norma",
    normative_value: "Balandligi: 0.75 - 0.80 m | Biri bukiluvchi (otkidnoy)",
    unit: "m",
    building_type: "Jamoat va moslashtirilgan turar joylar",
    room_type: "Universal hojatxona",
    condition: "Unitazga aravachadan mustaqil o'tirish uchun",
    formula: null,
    calculation_example: "Devor tomondagi tutqich statsionar mahkamlangan; ochiq tomondagi tutqich esa aravacha yaqinlashishi uchun tepaga bukiluvchi (otkidnoy) bo'ladi.",
    practical_note: "Tutqichlar kamida 120-150 kg og'irlikdagi zarbaviy yuklamaga bardosh beradigan ankerlar bilan devorga qotiriladi.",
    architect_note: "Unitaz o'rindig'i balandligi oddiy unitazdan balandroq — poldan 450-480 mm balandlikda bo'lishi qulay.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.11-band",
    source_table: null,
    keywords: ["otkidnoy porochen", "sanuzel tutqichi", "unitaz poruchni", "поручни для унитаза"],
    status: "AMALDA",
    order_index: 132
  },
  {
    title: "Nogironlar foydalanadigan rakovina o'rnatish balandligi va osti bo'shlig'i",
    slug: "nogironlar-rakovinasi-balandligi-osti-boshligi",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Moslashtirilgan sanuzellar",
    data_type: "norma",
    normative_value: "Yuqori qirrasi: 0.80 - 0.85 m | Ostdagi tizzalar bo'shlig'i: kamida 0.70 m",
    unit: "m",
    building_type: "Barcha moslashtirilgan obyektlar",
    room_type: "Universal sanuzel rakovinasi",
    condition: "Aravachaning tizzalari rakovina ostiga erkin kirishi uchun",
    formula: null,
    calculation_example: "Rakovina ostida tumba yoki oyoq (tyulpan) bo'lishi taqiqlanadi! Sifon devorga kiradigan gorizontal maxsus model tanlanadi.",
    practical_note: "Rakovinaning old tomoni ichkariga bukilgan ergonomik shaklda bo'lishi qo'llar yetishini osonlashtiradi.",
    architect_note: "Ko'zgu qiya egiluvchi (naklonnoe zerkalo) qilib o'rnatiladi, shunda aravachada o'tirgan inson o'zini bemalol ko'radi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.12-band",
    source_table: null,
    keywords: ["nogironlar rakovinasi", "naklonnoe zerkalo", "tizza bo'shlig'i", "раковина для инвалидов"],
    status: "AMALDA",
    order_index: 133
  },
  {
    title: "Ko'zi ojizlar uchun taktil yo'naltiruvchi va ogohlantiruvchi plitkalar o'rnatish",
    slug: "taktil-plitka-ornatish-qoidalari",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Taktil ko'rsatkichlar",
    data_type: "norma",
    normative_value: "To'siq yoki zinadan 300 - 500 mm oldin ogohlantiruvchi konusli plitka",
    unit: "mm masofa",
    building_type: "Piyodalar yo'laklari, bino kirishlari, vestibyullar, vokzallar",
    room_type: "Tashqi va ichki harakatlanish yo'llari",
    condition: "Ko'zi ojiz insonlar hassa bilan his qilishi uchun",
    formula: null,
    calculation_example: "Bo'ylama chiziqli plitka — to'g'ri harakatlanish yo'nalishini ko'rsatadi; Nuqtali/konusli plitka — xavf (zina, o'tish joyi, to'siq) haqida ogohlantiradi.",
    practical_note: "Taktil plitkalar atrofidagi qoplamaga nisbatan kontrast (yorqin sariq) rangda bo'lishi zaif ko'ruvchilar uchun muhim.",
    architect_note: "Plitka pol yuzasidan 4-5 mm dan ortiq bo'rtib chiqmasligi lozim, aks holda boshqa odamlar qoqiladi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.18-band",
    source_table: null,
    keywords: ["taktil plitka", "ko'zi ojizlar", "sariq plitka", "taktil yo'lak", "тактильная плитка"],
    status: "AMALDA",
    order_index: 134
  },
  {
    title: "Nogironlar aravachasi uchun lift kabinasining minimal ichki o'lchami",
    slug: "nogironlar-lift-kabinasi-minimal-olchami",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Vertikal transport",
    data_type: "norma",
    normative_value: "kamida 1.10 × 1.40",
    unit: "m (1100 × 1400 mm)",
    building_type: "Barcha jamoat va yangi turar joy binolari",
    room_type: "Moslashtirilgan lift kabinasi",
    condition: "Aravacha va hamrohlik qiluvchi shaxs uchun",
    formula: null,
    calculation_example: "Eshik kengligi kamida 900 mm. Kabina ichida kamida 3 tomondan tutqich (90 sm balandlikda) va orqa devorda ko'zgu bo'ladi.",
    practical_note: "Orqa devordagi ko'zgu aravachadagi odamga orqaga qarab kabinadan xavfsiz chiqishga yordam beradi.",
    architect_note: "Tugmalar 900-1100 mm balandlikda gorizontal yoki vertikal joylashtiriladi, Brayl alifbosi va ovozli e'lon (rechevoy informator) majburiy.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "4.3-band",
    source_table: null,
    keywords: ["inklyuziv lift", "lift kabinasi", "1100x1400", "brayl", "лифт для инвалидов"],
    status: "AMALDA",
    order_index: 135
  },
  {
    title: "Imkoniyati cheklangan shaxslar avtotransporti uchun kengaytirilgan to'xtash joyi",
    slug: "nogironlar-avtomobil-parking-joyi-olchami",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Avtoturargohlar",
    data_type: "norma",
    normative_value: "kamida 3.5 × 5.0 (optimal 3.6 × 6.0)",
    unit: "m (maydoni kamida 18 m²)",
    building_type: "Barcha ochiq va yopiq avtoturargohlar",
    room_type: "Maxsus ajratilgan mashina joyi",
    condition: "Avtomobil eshigi to'liq ochilib, yoniga aravacha qo'yilishi uchun",
    formula: null,
    calculation_example: "Oddiy joy 2.5 m bo'lsa, bu yerda 1.0 metrli xavfsiz o'tish zonasi (sariq chiziqli shtraxovka) qo'shiladi: 2.5 + 1.0 = 3.5 m.",
    practical_note: "Jami to'xtash joylarining kamida 10% i nogironlar uchun ajratilishi va bino kirishiga eng yaqin masofada (50 m dan oshmagan) bo'lishi shart.",
    architect_note: "Asfalt ustiga xalqaro nogironlar belgisi (aravacha piktogrammasi) va vertikal yo'l belgisi o'rnatiladi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "2.8-band",
    source_table: null,
    keywords: ["nogironlar parkovkasi", "3.5 metr", "inklyuziv parking", "парковка для инвалидов"],
    status: "AMALDA",
    order_index: 136
  },
  {
    title: "Binoga kirishda ko'chma yoki statsionar vertikal nogironlar ko'targichi (pod'yomnik)",
    slug: "vertikal-nogironlar-koytargichi-podyomnik-normasi",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Mexanik vositalar",
    data_type: "norma",
    normative_value: "Ko'tarilish balandligi > 0.8 m bo'lib pandusga joy yetmaganda",
    unit: "texnik yechim",
    building_type: "Qayta ta'mirlanadigan yoki tor uchastkali jamoat binolari",
    room_type: "Fasad kirish portali",
    condition: "Pandus uzunligi binoni o'rab olishi imkonsiz bo'lgan shaharsozlik cheklovlarida",
    formula: null,
    calculation_example: "Platforma o'lchami kamida 900 × 1200 mm, yuk ko'tarishi kamida 250-350 kg.",
    practical_note: "Ochiq havoda ishlaydigan ko'targich yomg'ir va qordan himoyalovchi maxsus qoplama va antifrizli gidravlika bilan jihozlanadi.",
    architect_note: "Ko'targich chaqiruv tugmasi bino xodimlariga signal beruvchi tablo bilan bog'lanishi lozim.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.22-band",
    source_table: null,
    keywords: ["podyomnik", "vertikal ko'targich", "lift platforma", "подъемник для инвалидов"],
    status: "AMALDA",
    order_index: 137
  },
  {
    title: "Vizual va tovushli axborot vositalari (mnemosxema, ovozli mayak)",
    slug: "mnemosxema-ovozli-mayak-inklyuziv-axborot",
    category: "Pandus va inklyuziv loyihalash",
    subcategory: "Orientatsiya va navigatsiya",
    data_type: "norma",
    normative_value: "Bino kirishidan o'ng tomonda 1.2 - 1.4 m balandlikda mnemosxema",
    unit: "standart",
    building_type: "Shifoxonalar, vokzallar, banklar, davlat xizmatlari markazlari",
    room_type: "Bosh vestibyul, kirish zonasi",
    condition: "Ko'zi ojiz va qulog'i og'ir insonlar erkin yo'l topishi uchun",
    formula: null,
    calculation_example: "Taktil mnemosxemada bino qavati rejasi bo'rtma chiziqlar va Brayl alifbosi bilan ko'rsatiladi.",
    practical_note: "Kirish eshigi tepasida ovozli mayak (zvukovoy mayak) ko'zi ojiz insonni ovozi bilan chaqirib turadi.",
    architect_note: "Navigatsiya belgilari kontrast ranglarda (ko'k/oq yoki sariq/qora) va yaltiramas matoviy sirtda bajariladi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "5.1-band",
    source_table: null,
    keywords: ["mnemosxema", "brayl", "ovozli mayak", "inklyuziv navigatsiya", "мнемосхема"],
    status: "AMALDA",
    order_index: 138
  },

  // --- 9. Sanuzel va ho'l zonalar (139-155) ---
  {
    title: "Birlashgan sanuzel (vanna + unitaz + rakovina) minimal maydoni",
    slug: "birlashgan-sanuzel-minimal-maydoni-turar-joy",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Xona maydonlari",
    data_type: "norma",
    normative_value: "3.8 - 4.0",
    unit: "m²",
    building_type: "Turar joy binolari (1 va 2 xonali kvartiralar)",
    room_type: "Birlashgan sanuzel",
    condition: "Vanna (170x70 sm), unitaz va rakovinani qulay joylashtirishda",
    formula: null,
    calculation_example: "Xona o'lchami: 1.8 m × 2.2 m = 3.96 m² — barcha standart santexnika va hatto tor kir yuvish mashinasi sig'adi.",
    practical_note: "Dush kabinasi (90x90 sm) qo'yilsa, minimal maydonni 3.0 - 3.2 m² gacha qisqartirish mumkin.",
    architect_note: "Kvartirada yagona bo'lgan birlashgan sanuzel faqat 1 yoki 2 xonali uylarda ruxsat etiladi; 3 va undan ko'p xonali uylarda alohida hojatxona talab qilinadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.8-band",
    source_table: null,
    keywords: ["birlashgan sanuzel", "vanna hojatxona", "3.8 m2", "совмещенный санузел"],
    status: "AMALDA",
    order_index: 139
  },
  {
    title: "Alohida hojatxona xonasining minimal o'lchamlari va maydoni",
    slug: "alohida-hojatxona-minimal-olchami-maydoni",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Xona maydonlari",
    data_type: "norma",
    normative_value: "Eni: kamida 0.8 - 0.9 m | Chuqurligi: kamida 1.2 - 1.5 m (maydoni 1.1 - 1.3 m²)",
    unit: "m",
    building_type: "Turar joy va jamoat binolari",
    room_type: "Alohida tualet xonasi",
    condition: "Eshik tashqariga ochilganda chuqurligi kamida 1.2 m; ichkariga ochilsa kamida 1.5 m",
    formula: null,
    calculation_example: "Eni 0.9 m, chuqurligi 1.3 m = 1.17 m². Unitaz (uzunligi 65 sm) o'rnatilgach, oldida 65 sm erkin bo'shliq qoladi.",
    practical_note: "Hojatxonaga kichik qo'l yuvgich (rukamoynik - 35x20 sm) qo'yish rejalashtirilsa, xona eni kamida 1.0 m, chuqurligi 1.4 m bo'lishi kerak.",
    architect_note: "Kanalizatsiya stoyagi uchun burchakda 30x30 sm montaj qutisi hisobga olinadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.8-band",
    source_table: null,
    keywords: ["alohida hojatxona", "tualet o'lchami", "0.8x1.2", "туалет размеры"],
    status: "AMALDA",
    order_index: 140
  },
  {
    title: "Alohida vanna xonasi (hammom) minimal maydoni",
    slug: "alohida-vanna-xonasi-minimal-maydoni",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Xona maydonlari",
    data_type: "norma",
    normative_value: "kamida 2.5 - 2.8",
    unit: "m²",
    building_type: "Turar joy binolari",
    room_type: "Alohida vanna xonasi (hojatxonasiz)",
    condition: "Vanna, rakovina va kir yuvish mashinasini joylashtirish uchun",
    formula: null,
    calculation_example: "O'lchami 1.7 m × 1.6 m = 2.72 m². Vanna 170x70 sm butun devor bo'yicha sig'adi.",
    practical_note: "Kir yuvish mashinasini sanuzel ichiga qo'yish uchun xona maydonini kamida 3.0-3.3 m² qilish tavsiya etiladi.",
    architect_note: "Vanna ostiga drenaj yoki trap qo'yilishi avariya holatida suv toshib ketishining oldini oladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.8-band",
    source_table: null,
    keywords: ["vanna xonasi", "hammom maydoni", "2.5 m2", "ванная комната"],
    status: "AMALDA",
    order_index: 141
  },
  {
    title: "Dush kabinasi / dush zonasi minimal qulay o'lchamlari",
    slug: "dush-kabinasi-minimal-qulay-olchami",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Dush zonalari",
    data_type: "tavsiya",
    normative_value: "kamida 0.8 × 0.8 m (optimal 0.9 × 0.9 yoki 1.0 × 1.0 m)",
    unit: "m",
    building_type: "Barcha turar joy va mehmonxonalar",
    room_type: "Dush zonasi",
    condition: "Inson dush qabul qilayotganda qo'llari devorga urilmasligi uchun",
    formula: null,
    calculation_example: "80×80 sm juda ixcham (harakat cheklangan). 90×90 sm yoki 120×90 sm li pol bilan bir sathdagi shisha to'siqli walk-in dush eng qulay hisoblanadi.",
    practical_note: "Polga yotqiziladigan trapli dushda nishablik suv to'planmasligi uchun trap tomon 1.5-2% qilib bajariladi.",
    architect_note: "Dush zonasi devorlariga to'liq 2.0-2.2 m balandlikkacha gidroizolyatsiya surtiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["dush o'lchami", "dush kabina", "90x90", "walk-in dush", "душевая кабина"],
    status: "AMALDA",
    order_index: 142
  },
  {
    title: "Unitaz oldidagi erkin bo'shliq ergonomika normasi",
    slug: "unitaz-oldidagi-erkin-boshliq-masofasi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Santexnika ergonomikasi",
    data_type: "norma",
    normative_value: "kamida 0.6",
    unit: "m (600 mm / 60 sm)",
    building_type: "Barcha bino turlari",
    room_type: "Hojatxona, sanuzel",
    condition: "Unitaz old qirrasidan qarama-qarshi devor yoki eshikkacha",
    formula: null,
    calculation_example: "Agar bu masofa 50 sm dan kam bo'lsa, o'tirgan odamning tizzalari eshikka uriladi va turib-o'tirish juda noqulay bo'ladi.",
    practical_note: "Qulay premium standart — 70-75 sm erkin masofa.",
    architect_note: "Osma unitaz (installyatsiya) ishlatilganda bak devor ichiga kirgani uchun 10-15 sm joy tejaladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ergonomik ilova",
    source_table: null,
    keywords: ["unitaz oldi", "60 sm", "tualet masofasi", "расстояние перед унитазом"],
    status: "AMALDA",
    order_index: 143
  },
  {
    title: "Unitaz o'qi bilan yon devorlar orasidagi minimal masofa",
    slug: "unitaz-oqi-bilan-yon-devor-oraligi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Santexnika ergonomikasi",
    data_type: "norma",
    normative_value: "kamida 0.38 - 0.40 m (unitaz o'qidan devorgacha)",
    unit: "m (o'qdan 40 sm, jami eni 80 sm)",
    building_type: "Barcha bino turlari",
    room_type: "Hojatxona",
    condition: "Inson tirsaklari devorga tegmasligi uchun",
    formula: "L_devorgacha >= 380 mm",
    calculation_example: "Hojatxona eni 80 sm bo'lsa, unitaz qoq o'rtada (ikki tomondan devorgacha 22 sm, o'qidan 40 sm) turishi shart.",
    practical_note: "Gigiyenik dush (bide-dush) o'rnatilganda unitaz yon devorida 15-20 sm bo'shliq va mikser uchun joy qoldiriladi.",
    architect_note: "Qog'oz ushlagich unitaz old chetidan 20-30 sm oldinda va poldan 60-70 sm balandlikda qulay qo'yiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ergonomik ilova",
    source_table: null,
    keywords: ["unitaz o'qi", "yon devor", "40 sm", "расстояние от стены до унитаза"],
    status: "AMALDA",
    order_index: 144
  },
  {
    title: "Qo'l yuvish rakovinasi oldidagi erkin ergonomik bo'shliq",
    slug: "rakovina-oldidagi-erkin-boshliq-masofasi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Santexnika ergonomikasi",
    data_type: "tavsiya",
    normative_value: "kamida 0.70",
    unit: "m (700 mm / 70 sm)",
    building_type: "Barcha bino turlari",
    room_type: "Vanna xonasi, sanuzel",
    condition: "Inson yuvinayotganda egilishi va sochiq bilan artinishi uchun",
    formula: null,
    calculation_example: "Rakovina oldida kamida 70×100 sm li bo'sh to'rtburchak maydon bo'lishi kerak.",
    practical_note: "Rakovina bilan unitaz yonma-yon tursa, ular orasidagi masofa kamida 25 sm bo'lishi lozim.",
    architect_note: "Rakovina yonidagi elektr rozetkasi IP44 himoyali bo'lib, suv manbaidan (kranning to'g'ri o'qidan) kamida 60 sm uzoqlikda o'rnatiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ergonomik tavsiya",
    source_table: null,
    keywords: ["rakovina oldi", "70 sm", "yuvinish maydoni", "расстояние перед раковиной"],
    status: "AMALDA",
    order_index: 145
  },
  {
    title: "Rakovinaning toza pol sathidan standart o'rnatish balandligi",
    slug: "rakovina-standart-ornatish-balandligi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Santexnika montaj balandliklari",
    data_type: "norma",
    normative_value: "0.80 - 0.85",
    unit: "m (800 - 850 mm)",
    building_type: "Turar joy va jamoat binolari",
    room_type: "Sanuzel, vanna",
    condition: "Toza pol sathidan rakovinaning yuqori bortigacha",
    formula: null,
    calculation_example: "Bo'yi 170-180 sm bo'lgan kattalar uchun 85 sm ideal qulaylik beradi. Ustiga qo'yiladigan (nakladnaya chasha) rakovinada mebel stoli 70-75 sm qilinadi, chashaning ustki qirrasi 85 sm ga to'g'rilanadi.",
    practical_note: "Boshlang'ich kanalizatsiya chiqishi poldan 50-55 sm balandlikda, issiq-sovuq suv quvurlari esa 55-60 sm balandlikda chiqariladi.",
    architect_note: "Maktabgacha ta'lim muassasalarida (bog'chalarda) bolalar rakovinasi 500 mm (kichiklar) va 600 mm (kattalar) balandlikda o'rnatiladi.",
    source_document_number: "QMQ 2.04.01-98",
    source_band: "3.14-band",
    source_table: null,
    keywords: ["rakovina balandligi", "85 sm", "montaj balandligi", "высота раковины"],
    status: "AMALDA",
    order_index: 146
  },
  {
    title: "Sanuzel pol va devorlarining majburiy gidroizolyatsiya chegaralari",
    slug: "sanuzel-gidroizolyatsiya-qoidalari-va-balandligi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Gidroizolyatsiya",
    data_type: "norma",
    normative_value: "Pol to'liq + devorlar kamida 15-20 sm; Dush zonasida devorlar kamida 2.0 m",
    unit: "balandlik",
    building_type: "Barcha bino turlari",
    room_type: "Vanna, dush, hojatxona, kirxona",
    condition: "Suv pastki qavatdagi qo'shnilarga oqib tushmasligi uchun",
    formula: null,
    calculation_example: "Polga polimer-sementli yoki elastik bitumli 2 qatlam gidroizolyatsiya surtiladi va devorga 20 sm ko'tariladi ('gidro-krovat' hosil qilinadi).",
    practical_note: "Quvurlar polni kesib o'tgan joylar maxsus elastik elastik manjetlar va burchak lentalari bilan mustahkamlanadi.",
    architect_note: "Plitka va zatirka suvdan 100% himoya qilmaydi; asosiy suv to'siq plitka tagidagi gidroizolyatsiya qatlamidir.",
    source_document_number: "QMQ 2.03.01-96",
    source_band: "4.12-band",
    source_table: null,
    keywords: ["gidroizolyatsiya", "vanna poli", "dush zonasi", "suv oqishi", "гидроизоляция санузла"],
    status: "AMALDA",
    order_index: 147
  },
  {
    title: "Dush zonasi polining trap (trapp) tomon minimal nishabligi",
    slug: "dush-poli-trap-tomon-minimal-nishabligi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Kanalizatsiya va suv oqishi",
    data_type: "norma",
    normative_value: "1.5% - 2.0% (har 1 metrga 1.5 - 2.0 sm)",
    unit: "nishablik (% yoki sm/m)",
    building_type: "Turar joy, mehmonxona, sport zallari",
    room_type: "Poddonli yoki poddonsiz (walk-in) dush poli",
    condition: "Suvning to'planib ko'lmak bo'lmasdan tezda kanalizatsiyaga oqib ketishi uchun",
    formula: "i = h_tushish / L = 0.02 (2 sm / 1 m)",
    calculation_example: "Dush devoridan trapigacha masofa 1 metr bo'lsa, devor yonidagi pol trap sathidan 2 sm balandroq bo'lishi shart.",
    practical_note: "Nishablik 1% dan kam bo'lsa suv sirt tarangligi tufayli ko'lmak bo'lib turib qoladi; 3% dan oshsa oyoq ostida noqulay qiyalik seziladi.",
    architect_note: "Chiziqli (shchelevoy) zanglamas po'lat trap ishlatilsa bir tomonga nishablik qilinadi, bu katta formatli plitka kesilmasdan chiroyli yotqizilishini ta'minlaydi.",
    source_document_number: "QMQ 2.04.01-98",
    source_band: "3.8-band",
    source_table: null,
    keywords: ["trap nishabligi", "dush poli", "2 foiz", "suv oqishi", "уклон трапа"],
    status: "AMALDA",
    order_index: 148
  },
  {
    title: "Sanuzel pol sathining koridorga nisbatan xavfsizlik chuqurligi",
    slug: "sanuzel-poli-koridordan-past-bolishi-normasi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "To'kilishdan himoya",
    data_type: "norma",
    normative_value: "15 - 20 mm (1.5 - 2 sm) past bo'lishi yoki ostona (porog) qo'yilishi",
    unit: "mm",
    building_type: "Ko'p xonadonli turar joy binolari",
    room_type: "Barcha ho'l zonalar (sanuzel, vanna)",
    condition: "Santexnika avariyasida suv zudlik bilan koridor va yashash xonalariga toshib ketmasligi uchun",
    formula: "h_koridor - h_sanuzel >= 15 mm",
    calculation_example: "Sanuzel toza poli koridordan 2 sm past qilinadi yoki eshik tagiga 2 sm balandlikdagi marmar/kafel ostona qo'yiladi.",
    practical_note: "Zamonaviy aqlli kvartiralarda qo'shimcha ravishda polga avtomatik suv toshish datchiklari (gidrolok, neptun) o'rnatilib, kranlar avtomatik yopiladi.",
    architect_note: "Nogironlar yashaydigan xonadonlarda ostonasiz yechim tanlanib, sanuzel ichi teskari nishablik bilan loyihalanadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.9-band",
    source_table: null,
    keywords: ["sanuzel poli", "porog", "suv toshishi", "ostona", "перепад пола санузла"],
    status: "AMALDA",
    order_index: 149
  },
  {
    title: "Ichki kanalizatsiya quvurlari minimal nishabligi (diametri bo'yicha)",
    slug: "ichki-kanalizatsiya-quvurlari-minimal-nishabligi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Kanalizatsiya muhandisligi",
    data_type: "norma",
    normative_value: "d=50 mm uchun: 0.03 (3 sm/m) | d=110 mm uchun: 0.02 (2 sm/m)",
    unit: "nishablik (sm har metrga)",
    building_type: "Barcha bino turlari",
    room_type: "Ichki suv chiqarish tarmoqlari",
    condition: "Suv va najas massalarining o'z-o'zini tozalash tezligi (samoochishchenie) uchun",
    formula: "i = 0.03 (d=50 mm) | i = 0.02 (d=110 mm)",
    calculation_example: "Rakovinadan (d=50 mm) tik stoyakkacha 3 metr masofa bo'lsa: balandlik tushishi 3 × 3 sm = 9 sm bo'lishi shart.",
    practical_note: "Nishablik kam bo'lsa truba tiqilib qoladi; nishablik HADDAN ORTIQ KATTA bo'lsa suv tez oqib ketib quyqa cho'kib qoladi!",
    architect_note: "Sanuzel asboblarini stoyakdan uzoqlashtirganda stajka ichida nishablik uchun yetarli balandlik bor-yo'qligi tekshiriladi.",
    source_document_number: "QMQ 2.04.01-98",
    source_band: "3.2-band",
    source_table: "3.1-jadval",
    keywords: ["kanalizatsiya nishabligi", "uklon truby", "d50 nishablik", "d110 nishablik", "уклон канализации"],
    status: "AMALDA",
    order_index: 150
  },
  {
    title: "Unitazning vertikal kanalizatsiya stoyagigacha bo'lgan maksimal ruxsat etilgan masofasi",
    slug: "unitaz-stoyakgacha-maksimal-ruxsat-etilgan-masofa",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Kanalizatsiya muhandisligi",
    data_type: "norma",
    normative_value: "ko'pi bilan 1.0 - 1.5",
    unit: "m (ideal 1.0 m gacha)",
    building_type: "Barcha bino turlari",
    room_type: "Unitaz ulash trubasi",
    condition: "110 mm li trubaning 90° o'tkir burilishlarsiz stoyakka to'g'ri ulanishi",
    formula: null,
    calculation_example: "Unitaz stoyakdan 3 metr uzoqqa ko'chirilsa: kamida 6 sm nishablik kerak bo'ladi va truba pol ustiga chiqib qoladi, qolaversa suv ketganda gidrozatvorni so'rib oladi.",
    practical_note: "Unitazni ko'chirish kerak bo'lsa faqat 45° li burilish tirsaklari (otvod) ishlatiladi, to'g'ri 90° burchak man etiladi.",
    architect_note: "Kvartira pereplanirovkasida unitazni boshqa xonaga stoyakdan uzoqqa ko'chirishga qat'iyan ruxsat berilmaydi.",
    source_document_number: "QMQ 2.04.01-98",
    source_band: "3.4-band",
    source_table: null,
    keywords: ["unitaz stoyak", "masofa", "tiqilish", "stoyak masofasi", "расстояние от унитаза до стояка"],
    status: "AMALDA",
    order_index: 151
  },
  {
    title: "Kvartiralarda ho'l nuqtalarni (sanuzel va vanna) ko'chirish bo'yicha qonuniy taqiq",
    slug: "sanuzelni-yashash-xonasi-ustiga-kochirish-taqiqi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Qayta rejalashtirish (pereplanirovka)",
    data_type: "norma",
    normative_value: "Pastki qavatdagi qo'shnining yashash xonasi va oshxonasi ustiga ko'chirish QAT'IYAN TAQIQLANADI",
    unit: "qonuniy taqiq",
    building_type: "Ko'p kvartirali turar joy binolari",
    room_type: "Sanuzel, dush, vanna",
    condition: "Avariya yuz berganda pastki qavat yashash xonasini suv bosmasligi uchun",
    formula: null,
    calculation_example: "Sanuzelni faqat o'zining avvalgi chegaralarida, yoki koridor, dahliz va kladovka (yordamchi xonalar) hisobiga kengaytirishga ruxsat beriladi.",
    practical_note: "Istisno: eng pastki turar joy qavatida (ostida podval yoki do'kon bo'lsa) sanuzelni ixtiyoriy joyga ko'chirish mumkin.",
    architect_note: "Ekspertiza va kadastr bunday noqonuniy pereplanirovkani tasdiqlamaydi va sud orqali avvalgi holatga qaytartiradi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.10-band",
    source_table: null,
    keywords: ["ho'l zona taqiqi", "pereplanirovka", "sanuzel ko'chirish", "mokraya zona", "перенос мокрой зоны"],
    status: "AMALDA",
    order_index: 152
  },
  {
    title: "Sanuzel ichidagi elektr xavfsizlik zonalari (0, 1, 2 va 3 zonalar)",
    slug: "sanuzel-elektr-xavfsizlik-zonalari",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Elektr xavfsizligi",
    data_type: "norma",
    normative_value: "Zona 0 (vanna ichi) | Zona 1 (suv oqimi) | Zona 2 (60 sm gacha) | Zona 3 (>60 sm)",
    unit: "xavfsizlik zonalari",
    building_type: "Barcha bino turlari",
    room_type: "Vanna xonasi va dush",
    condition: "Elektr toki urishi xavfini mutlaqo bartaraf etish",
    formula: null,
    calculation_example: "Zona 0 va 1 da 220V rozetka va asboblar o'rnatish qat'iyan man! Rozetkalar faqat Zona 3 da (dush va vannadan kamida 60 sm uzoqda) o'rnatiladi.",
    practical_note: "Barcha sanuzel elektr tarmoqlari 30 mA (yaxshisi 10 mA) o'ta sezgir differensial avtomat yoki UZO (qochqin tok relesi) orqali ulanishi shart.",
    architect_note: "Rozetkalar albatta qopqoqli va namlikdan himoyalangan IP44 toifasida bo'lishi lozim.",
    source_document_number: "QMQ 2.04.05-18",
    source_band: "Elektr qoidalari",
    source_table: null,
    keywords: ["sanuzel elektr", "UZO", "IP44", "rozetka zona", "зоны безопасности санузла"],
    status: "AMALDA",
    order_index: 153
  },
  {
    title: "Sanuzellarda sochiq quritgich (polotentsesushitel) o'rnatish balandligi",
    slug: "sochiq-quritgich-polotentsesushitel-balandligi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Santexnika montaj balandliklari",
    data_type: "tavsiya",
    normative_value: "Poldan pastki qismi: 0.9 - 1.1 m | Yuqori qismi: 1.7 - 1.9 m",
    unit: "m",
    building_type: "Turar joy binolari",
    room_type: "Vanna xonasi",
    condition: "Qo'l cho'zganda sochiqni erkin olish va quritish uchun",
    formula: null,
    calculation_example: "M-shaklidagi yoki 'lesenka' shaklidagi suvli sochiq quritgich markazi poldan taxminan 120-140 sm balandlikda joylashadi.",
    practical_note: "Elektr sochiq quritgich o'rnatilganda yashirin ulanish (skryty montaj) tanlansa kabel osilib xunuk ko'rinmaydi va xavfsiz bo'ladi.",
    architect_note: "Suvli sochiq quritgich issiq suv sirkulyatsiya (GVS) stoyagiga ulanishi kerak; faqat isitish (otoplenie) tizimiga ulasa yozda muzlab qoladi.",
    source_document_number: "QMQ 2.04.01-98",
    source_band: "3.16-band",
    source_table: null,
    keywords: ["sochiq quritgich", "polotentsesushitel", "1.2 m", "vanna isitish", "полотенцесушитель"],
    status: "AMALDA",
    order_index: 154
  },
  {
    title: "Binolarda sovuq va issiq suv tarmog'i normativ ishchi bosimi",
    slug: "ichki-suv-tarmogi-normativ-ishchi-bosimi",
    category: "Sanuzel va ho'l zonalar",
    subcategory: "Suv ta'minoti muhandisligi",
    data_type: "norma",
    normative_value: "Santexnika asboblarida: 0.2 - 0.45 MPa (2.0 - 4.5 bar)",
    unit: "bar / MPa",
    building_type: "Barcha bino turlari",
    room_type: "Bino ichki suv ta'minoti tarmog'i",
    condition: "Santexnika jihozlarining (smesitel, shlang) normal ishlashi va buzilmasligi uchun",
    formula: "P_max <= 0.45 MPa (4.5 bar)",
    calculation_example: "Ko'p qavatli uylarning pastki qavatlarida bosim 6-8 bargacha ko'tarilishi mumkin. Bu kran qistirmalarini yorib yuboradi, shuning uchun bosim pasaytirgich (reduktor davleniya) o'rnatiladi.",
    practical_note: "Minimal erkin bosim dush uchun kamida 1.0-1.5 bar, aralash kranlar uchun 0.5-1.0 bar bo'lishi kerak.",
    architect_note: "Kvartira kirishiga filtr, teskari klapan va reduktor o'rnatiladigan kollektor shkafi (santexnicheskiy shkaf) rejalashtiriladi.",
    source_document_number: "QMQ 2.04.01-98",
    source_band: "2.8-band",
    source_table: null,
    keywords: ["suv bosimi", "reduktor", "4.5 bar", "santexnika", "давление воды"],
    status: "AMALDA",
    order_index: 155
  }
];

module.exports = { SEED_TOPICS_BATCH3 };
