// ============================================================================
// BATCH 2: O'lchash va hisoblash | Eshiklar | Derazalar (Topics 56-105)
// Rasmiy O'zbekiston standartlari (SHNQ 2.08.01-24, SHNQ 2.01.02-04, SHNQ 2.01.18-23)
// ============================================================================

const SEED_TOPICS_BATCH2 = [
  // --- 4. O'lchash va hisoblash usullari (56-70) ---
  {
    title: "Xona toza maydonini o'lchashning rasmiy uslubi",
    slug: "xona-toza-maydonini-olchash-uslubi",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Geodeziya va kadastr",
    data_type: "norma",
    normative_value: "Devorlarning pardozlangan toza sirtlari orasidagi o'lcham",
    unit: "m²",
    building_type: "Barcha bino turlari",
    room_type: "Barcha xonalar",
    condition: "Plintus sathi ustidan (pol sathidan 10-15 sm balandlikda)",
    formula: "S = a × b",
    calculation_example: "Xona bo'yi a=5.20 m, eni b=3.40 m bo'lsa: S = 5.20 × 3.40 = 17.68 m².",
    practical_note: "Plintus, pilastrlar va dekorativ devor qoplamalari maydon hisobidan ayirib tashlanmaydi; lekin xona ichidagi pech, kamin va alohida ustunlar maydondan chegiriladi.",
    architect_note: "Kadastr o'lchovlarida gipsokartondan keyingi toza o'lcham olinadi. Loyihalashda qora suvoq va pardoz uchun devor qalinligiga 3-5 sm zaxira beriladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ilova 2 (Maydonlarni hisoblash qoidalari)",
    source_table: null,
    keywords: ["maydon o'lchash", "kadastr", "toza maydon", "izmerenie ploshadi"],
    status: "AMALDA",
    order_index: 56
  },
  {
    title: "Xona hajmini hisoblash usuli",
    slug: "xona-hajmini-hisoblash-usuli",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Arxitekturaviy hajmlar",
    data_type: "hisoblash",
    normative_value: "V = S × h",
    unit: "m³",
    building_type: "Barcha binolar",
    room_type: "Barcha xonalar",
    condition: "Toza pol sathidan toza shiftgacha bo'lgan balandlikda",
    formula: "V = S × h  [V - hajm (m³), S - toza maydon (m²), h - toza balandlik (m)]",
    calculation_example: "Maydoni S=24 m², shift balandligi h=2.85 m bo'lgan zal hajmi: V = 24 × 2.85 = 68.4 m³.",
    practical_note: "Xona hajmi shamollatish quvvati, isitish radiatorlari va konditsioner tanlashda asosiy boshlang'ich parametrdir.",
    architect_note: "Qiya shiftli mansarda xonalarida hajm trapetsiya yoki uchburchak prizma formulasi bo'yicha integrallab chiqariladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ilova 2",
    source_table: null,
    keywords: ["xona hajmi", "kubatura", "formula hajm", "объем помещения"],
    status: "AMALDA",
    order_index: 57
  },
  {
    title: "Kvartiraning umumiy va yashash maydoni farqi",
    slug: "kvartira-umumiy-va-yashash-maydoni-farqi",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Kvartira maydonlari",
    data_type: "norma",
    normative_value: "Umumiy maydon = Yashash xonalari + Yordamchi xonalar + Koeffitsientli yozgi xonalar",
    unit: "m²",
    building_type: "Turar joy binolari",
    room_type: "Kvartira",
    condition: "Kadastr pasporti va shaharsozlik loyihasida",
    formula: "S_umumiy = S_yashash + S_yordamchi (oshxona, sanuzel, koridor, kladovka) + (S_balkon × K)",
    calculation_example: "Yashash xonalari: 32 m². Oshxona: 9 m². Sanuzel: 4.5 m². Koridor: 7.5 m². Balkon (3 m² × 0.3 = 0.9 m²). S_umumiy = 32 + 9 + 4.5 + 7.5 + 0.9 = 53.9 m².",
    practical_note: "Oldi-sotdi shartnomalarida umumiy maydon (balkon bilan birga) ko'rsatiladi; yashash maydoni esa faqat yotoqxona va mehmonxona maydonlaridir.",
    architect_note: "Kvartira rejasini tuzishda yashash maydonining umumiy maydonga nisbati (K1) kamida 0.50-0.65 bo'lishi tejamkor loyiha hisoblanadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ilova 2, 2-band",
    source_table: null,
    keywords: ["umumiy maydon", "yashash maydoni", "balkon koeffitsienti", "жилая общая площадь"],
    status: "AMALDA",
    order_index: 58
  },
  {
    title: "Balkon, lodjiya va terrasalarni umumiy maydonga qo'shish koeffitsientlari",
    slug: "balkon-lodjiya-terrasa-hisoblash-koeffitsientlari",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Yozgi xonalar",
    data_type: "norma",
    normative_value: "Lodjiya: 0.5 | Balkon/terrasa: 0.3 | Oynavand lodjiya: 0.7 | Veranda: 1.0",
    unit: "koeffitsient",
    building_type: "Turar joy binolari",
    room_type: "Yozgi xonalar (balkon, lodjiya, veranda)",
    condition: "Kvartira umumiy loyihaviy va kadastr maydonini aniqlashda",
    formula: "S_hisob = S_haqiqiy × K_kamaytirish",
    calculation_example: "6 m² haqiqiy lodjiya maydoni: 6 × 0.5 = 3.0 m² hisobga olinadi. 4 m² ochiq balkon: 4 × 0.3 = 1.2 m² hisobga olinadi.",
    practical_note: "Quruvchidan kvartira sotib olayotganda balkon maydoni 100% narx bilan emas, aynan shu pasaytirish koeffitsienti bilan hisoblanishi qonuniy me'yordir.",
    architect_note: "Isitiladigan va to'liq devor bilan o'ralgan qishki bog' yoki issiq lodjiya uchun K=1.0 deb qabul qilinadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ilova 2, 3-band",
    source_table: null,
    keywords: ["balkon koeffitsienti", "lodjiya", "terrasa", "коэффициент балкона"],
    status: "AMALDA",
    order_index: 59
  },
  {
    title: "Bino umumiy maydonini (qurilish hajmini) hisoblash qoidasi",
    slug: "bino-umumiy-maydoni-qurilish-hajmi-hisobi",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Bino ko'rsatkichlari",
    data_type: "hisoblash",
    normative_value: "Barcha ustki va yerosti qavatlar tashqi devorlar bo'yicha maydoni yig'indisi",
    unit: "m²",
    building_type: "Barcha bino turlari",
    room_type: "Bino umuman",
    condition: "Ekspertiza va arxitektura-shaharsozlik kengashi uchun",
    formula: "S_bino = Σ S_qavat (tashqi devorlar konturi bo'yicha)",
    calculation_example: "3 qavatli kottej (har qavat tashqi o'lchami 10x12=120 m²): S_umumiy = 3 × 120 = 360 m².",
    practical_note: "Bino qurilish maydoni (pyatno zastroyki) - bu binoning 1-qavati podval bilan birga yer yuzasidagi eng chiqib turgan perimetridir.",
    architect_note: "Zinapoya oraliqlari balandligi bo'yicha 1 marta hisoblanadi; 2-qavatdagi ikkinchi nur (antresol) o'z pol maydoni bo'yicha qo'shiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Ilova 2, 5-band",
    source_table: null,
    keywords: ["bino maydoni", "qurilish hajmi", "pyatno zastroyki", "площадь здания"],
    status: "AMALDA",
    order_index: 60
  },
  {
    title: "Foydali maydon koeffitsienti (K1) va rejalashtirish samaradorligi",
    slug: "foydali-maydon-koeffitsienti-rejalashtirish-samaradorligi",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Samaradorlik ko'rsatkichlari",
    data_type: "hisoblash",
    normative_value: "0.75 - 0.85 (75% - 85%)",
    unit: "nisbat (K1)",
    building_type: "Ko'p xonadonli uylar, ofis markazlari",
    room_type: "Qavat maydoni",
    condition: "Sotiladigan (foydali) maydonning umumiy qavat maydoniga nisbati",
    formula: "K1 = S_foydali / S_qavat_umumiy",
    calculation_example: "Qavatning to'liq maydoni 500 m². Kvartiralar maydoni 410 m², lift-koridor xoli 90 m². K1 = 410 / 500 = 0.82 (82% a'lo samaradorlik).",
    practical_note: "Agar K1 < 0.70 bo'lsa, bino arxitekturasida juda ko'p foydasiz uzun koridor va bo'shliqlar mavjudligini bildiradi.",
    architect_note: "Tijoriy loyihalarda buyurtmachilar K1 ko'rsatkichini kamida 0.80 bo'lishini talab qilishadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.1-band",
    source_table: null,
    keywords: ["foydali maydon", "samaradorlik", "k1", "коэффициент эффективности"],
    status: "AMALDA",
    order_index: 61
  },
  {
    title: "Qizil chiziqdan bino fasadigacha bo'lgan minimal masofani o'lchash",
    slug: "qizil-chiziqdan-bino-fasadigacha-masofa-olchash",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Shaharsozlik masofalari",
    data_type: "norma",
    normative_value: "kamida 5.0 (magistral ko'cha) | 3.0 (turar joy o'tish yo'li)",
    unit: "m",
    building_type: "Barcha bino turlari",
    room_type: "Bosh reja (Sitplan)",
    condition: "Qizil chiziq chegarasidan bino fasadining eng chiqib turgan qismigacha",
    formula: null,
    calculation_example: "Ko'cha qizil chizig'idan uyingiz fundamentigacha 5.0 m bo'lsa, lekin balkon 1.2 m ko'chaga chiqsa, qoida buzilgan hisoblanadi (masofa balkon bo'yicha o'lchanadi).",
    practical_note: "Masofa binoning tsokoli, erkeri, balkoni yoki kirish zinapoyasi kabi eng bo'rtib chiqqan konsol qismidan o'lchanadi.",
    architect_note: "APZ talablarida qizil chiziq bilan birga qurilishni tartibga solish chizig'i (liniya zastroiki) ham belgilanishi mumkin.",
    source_document_number: "SHNQ 2.07.01-03*",
    source_band: "4.12-band",
    source_table: null,
    keywords: ["qizil chiziq", "masofa", "sitplan", "krasnaya liniya", "красная линия"],
    status: "AMALDA",
    order_index: 62
  },
  {
    title: "Qo'shni yer uchastkasi chegarasigacha minimal masofa o'lchami",
    slug: "qoshni-yer-chegarasigacha-minimal-masofa",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Shaharsozlik masofalari",
    data_type: "norma",
    normative_value: "Uy uchun: 3.0 m | Yordamchi bino (garaj, saroy) uchun: 1.0 m",
    unit: "m",
    building_type: "Yakka tartibdagi uy-joylar (hovli, kottej)",
    room_type: "Yer uchastkasi (Sitplan)",
    condition: "Qo'shni uchastka devoridan (chegarasidan) bino devorigacha",
    formula: null,
    calculation_example: "Uy devori qo'shni devorigacha kamida 3.0 metr. Tom novchasi (karniz) esa qo'shni hovliga suv tushirmasligi kerak.",
    practical_note: "Agar qo'shnining uyi 1 metrda qurilgan bo'lsa, siz uyingizni yong'inga qarshi oraliq (kamida 6 metr bo'lishi) talabi tufayli 5 metrda qurishingizga to'g'ri kelishi mumkin.",
    architect_note: "Yordamchi binoni 1 m masofada qurganda tom qiyaligi o'z hovlingiz tomon nishab qilinishi shart.",
    source_document_number: "SHNQ 2.07.01-03*",
    source_band: "4.14-band",
    source_table: null,
    keywords: ["qo'shni chegara", "masofa 3 metr", "sitplan", "hovli me'mori", "граница участка"],
    status: "AMALDA",
    order_index: 63
  },
  {
    title: "Tabiiy yoritilganlik koeffitsienti (KEO) normasi",
    slug: "tabiiy-yoritilganlik-koeffitsienti-keo-normasi",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Insolyatsiya va yorug'lik",
    data_type: "norma",
    normative_value: "0.5% (turar joy) | 1.0% - 1.5% (sinfxona, ofis)",
    unit: "% (KEO)",
    building_type: "Turar joy va jamoat binolari",
    room_type: "Yashash xonalari, sinflar, laboratoriyalar",
    condition: "Xonaning o'rtasidagi pol sathida tabiiy yoritilganlik",
    formula: "e = (E_ichki / E_tashqi) × 100%",
    calculation_example: "Ochiq osmon yorug'ligi E_tashqi=10 000 lux bo'lganda, xona ichidagi ish stolida kamida E_ichki = 150 lux (KEO = 1.5%) bo'lishi kerak.",
    practical_note: "KEO kam bo'lsa xona qorong'i bo'lib, inson ko'zi tez toliqadi va energiya sarfi ortadi.",
    architect_note: "Chuqur xonalarda (chuqurligi 6 metrdan ortiq) bitta deraza bilan KEO ta'minlanmaydi, deraza maydonini oshirish yoki ikki tomondan oyna ochish lozim.",
    source_document_number: "QMQ 2.01.05-19",
    source_band: "2.4-band",
    source_table: "2.1-jadval",
    keywords: ["KEO", "yoritilganlik", "tabiiy yorug'lik", "КЕО", "освещенность"],
    status: "AMALDA",
    order_index: 64
  },
  {
    title: "O'zbekistonda yashash xonalarining uzluksiz insolyatsiya (quyosh tushish) normasi",
    slug: "uzluksiz-insolyatsiya-quyosh-tushish-davomiyligi",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Insolyatsiya va quyosh",
    data_type: "norma",
    normative_value: "kamida 2.0",
    unit: "soat (22-martdan 22-sentyabrgacha)",
    building_type: "Turar joy binolari, bog'chalar, maktablar",
    room_type: "1, 2 va 3 xonali kvartiraning kamida bitta yashash xonasi",
    condition: "O'zbekistonning janubiy va markaziy zonalari uchun bahorgi tengkunlikda",
    formula: null,
    calculation_example: "Kvartira shimolga qaragan bo'lsa va to'g'ridan-to'g'ri quyosh tushmasa — bu sanitariya me'yori buzilishidir.",
    practical_note: "4 va undan ko'p xonali kvartiralarda kamida 2 ta yashash xonasiga uzluksiz 2 soat quyosh nuri tushishi shart.",
    architect_note: "Binolar orasidagi masofa insolyatsiya kartasi (solnechnaya karta) orqali hisoblanadi; qarama-qarshi turgan bino quyoshni to'sib qo'ymasligi kerak.",
    source_document_number: "SanQvaN 0329-16",
    source_band: "3.1-band",
    source_table: null,
    keywords: ["insolyatsiya", "quyosh nuri", "sanitariya", "инсоляция", "2 часа"],
    status: "AMALDA",
    order_index: 65
  },
  {
    title: "Xonadonlararo devorlar uchun havo shovqinidan izolyatsiya indeksi (Rw)",
    slug: "xonadonlararo-devor-shovqin-izolyatsiyasi-rw",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Akustika va ovoz izolyatsiyasi",
    data_type: "norma",
    normative_value: "kamida 52",
    unit: "dB (desibel)",
    building_type: "Ko'p xonadonli turar joy binolari",
    room_type: "Qo'shni xonadonlar orasidagi ajratuvchi devor",
    condition: "Havo orqali tarqaluvchi shovqinlar uchun (ovoz, musiqa, televizor)",
    formula: "Rw >= 52 dB",
    calculation_example: "Oddiy 20 sm gazoblok (D500) Rw=44 dB beradi va normaga yetmaydi! Uni kamida ikki tomondan suvoq va mineral vata qatlami bilan 52 dB ga yetkazish shart.",
    practical_note: "Qo'shnilar suhbati eshitilmasligi uchun 52-54 dB normativ chegara hisoblanadi.",
    architect_note: "Kvartiralararo devorda rozetkalarni bir-biriga qarama-qarshi teshik qilib teshib o'rnatish man etiladi (ovoz aynan shu yerdan o'tadi).",
    source_document_number: "QMQ 2.01.08-96*",
    source_band: "2.3-band",
    source_table: "1-jadval",
    keywords: ["shovqin izolyatsiyasi", "akustika", "Rw", "shovqin dB", "звукоизоляция стен"],
    status: "AMALDA",
    order_index: 66
  },
  {
    title: "Qavatlararo orayopma (pol) uchun zarbli shovqin izolyatsiyasi (Lnw)",
    slug: "orayopma-zarbli-shovqin-izolyatsiyasi-lnw",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Akustika va ovoz izolyatsiyasi",
    data_type: "norma",
    normative_value: "ko'pi bilan 60",
    unit: "dB (past bo'lsa yaxshi)",
    building_type: "Ko'p xonadonli turar joylar",
    room_type: "Qavatlararo orayopma plitasi",
    condition: "Yuqori qavatdagi qadam tovushi, sakrash va stol siljishidan hosil bo'ladigan shovqin",
    formula: "Lnw <= 60 dB",
    calculation_example: "Yalang'och 22 sm temir-beton plita Lnw=78 dB beradi (juda shovqinli). Ostiga 20 mm akustik mineral plita va suzuvchi stajka (plavayushchiy pol) qilinganda Lnw=55 dB ga tushadi.",
    practical_note: "Suzuvchi pol (plavayushchiy pol) stajkasi devorlarga tegmasligi uchun chetlariga dempfer lentasi qo'yilishi shart.",
    architect_note: "Laminat ostidagi 2 mm li oddiy penopolistirol yetarli emas; normani bajarish uchun kamida 20 mm tovush yutuvchi qatlam ko'zda tutiladi.",
    source_document_number: "QMQ 2.01.08-96*",
    source_band: "2.5-band",
    source_table: "2-jadval",
    keywords: ["zarbli shovqin", "plavayushchiy pol", "akustika", "Lnw", "ударный шум"],
    status: "AMALDA",
    order_index: 67
  },
  {
    title: "Tashqi devorlar issiqlik o'tkazuvchanlik qarshiligi (R) hisoblash formulasi",
    slug: "tashqi-devor-issiqlik-qarshiligi-r-formulasi",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Issiqlik texnikasi",
    data_type: "hisoblash",
    normative_value: "R = δ / λ",
    unit: "m²·°C/Vt",
    building_type: "Barcha bino turlari",
    room_type: "Tashqi devor konstruksiyasi",
    condition: "Ko'p qatlamli devorning umumiy issiqlik himoyasini aniqlashda",
    formula: "R_umumiy = 1/α_ichki + (Σ δ_i / λ_i) + 1/α_tashqi",
    calculation_example: "10 sm bazalt vata (δ=0.1 m, λ=0.04 Vt/m°C): R_izolyatsiya = 0.1 / 0.04 = 2.5 m²·°C/Vt. Devorning o'zi bilan birga R_jami ≈ 2.8 m²·°C/Vt.",
    practical_note: "Qatlam qanchalik qalin (δ) va issiqlik o'tkazuvchanlik koeffitsienti (λ) qanchalik kichik bo'lsa, devor qishda shunchalik issiq, yozda salqin bo'ladi.",
    architect_note: "Issiqlik ko'priklarini (mostik xoloda - monolit belbog'lar va orayopma chetlari) uzluksiz termoizolyatsiya bilan yopish shart.",
    source_document_number: "QMQ 2.01.04-18",
    source_band: "3.2-band",
    source_table: null,
    keywords: ["issiqlik qarshiligi", "R formula", "termoizolyatsiya", "тепловое сопротивление"],
    status: "AMALDA",
    order_index: 68
  },
  {
    title: "Toshkent shahri uchun tashqi devorlarning talab qilinadigan issiqlik qarshiligi (R0)",
    slug: "toshkent-shahri-tashqi-devor-issiqlik-qarshiligi-normasi",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Issiqlik texnikasi",
    data_type: "norma",
    normative_value: "kamida 2.1 - 2.4",
    unit: "m²·°C/Vt",
    building_type: "Turar joy binolari",
    room_type: "Tashqi devor",
    condition: "Toshkent shahri iqlim sharoitida (isitish davri gradus-sutkasiga binoan)",
    formula: null,
    calculation_example: "Oddiy 38 sm pishiq g'isht devor (izolyatsiyasiz) R = 0.55 m²·°C/Vt beradi — bu normadan 4 barobar past! Shuning uchun kamida 8-10 sm penoplast yoki bazalt vata talab qilinadi.",
    practical_note: "Ushbu normaga javob bermaydigan binolar davlat ekspertizasidan o'tmaydi va energiya tejamkorlik pasportini ololmaydi.",
    architect_note: "Fasadni tashqaridan izolyatsiya qilish (ho'l fasad yoki ventfasad) tavsiya etiladi; ichkaridan izolyatsiya qilish devor ichida shudring nuqtasi (tochka rosi) hosil qiladi.",
    source_document_number: "QMQ 2.01.04-18",
    source_band: "3.5-band",
    source_table: "3.1-jadval",
    keywords: ["Toshkent issiqlik normasi", "R0", "fasad izolyatsiyasi", "теплозащита Ташкент"],
    status: "AMALDA",
    order_index: 69
  },
  {
    title: "Binolarning energiya samaradorlik toifasini (energoeffektivlik) belgilash",
    slug: "bino-energiya-samaradorlik-toifalari-a-dan-g-gacha",
    category: "O'lchash va hisoblash usullari",
    subcategory: "Energiya tejamkorlik",
    data_type: "norma",
    normative_value: "A++, A+, A, B, C, D, E",
    unit: "klass (toifa)",
    building_type: "Barcha yangi qurilayotgan binolar",
    room_type: "Bino energetik pasporti",
    condition: "Yillik solishtirma issiqlik va elektr energiyasi sarfiga ko'ra",
    formula: null,
    calculation_example: "C toifasi — bazaviy normativ daraja. B va A toifalari normadan 15% dan 40% gacha tejamkor ekanligini bildiradi.",
    practical_note: "2024-yildan boshlab O'zbekistonda B toifasidan past bo'lgan davlat obyektlarini loyihalash taqiqlanadi.",
    architect_note: "Energiya tejashda arxitekturaviy yechimlar (kompakt forma, to'g'ri oriyentatsiya, quyoshdan himoyalovchi soyabonlar) 30% gacha tejash imkonini beradi.",
    source_document_number: "SHNQ 2.01.15-23",
    source_band: "2.1-band",
    source_table: "1-jadval",
    keywords: ["energoeffektivlik", "A toifa", "energiya pasporti", "энергоэффективность"],
    status: "AMALDA",
    order_index: 70
  },

  // --- 5. Eshiklar va ochilish joylari (71-87) ---
  {
    title: "Kvartira kirish eshigining minimal toza o'tish kengligi",
    slug: "kvartira-kirish-eshigi-minimal-kengligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Turar joy eshiklari",
    data_type: "norma",
    normative_value: "0.9",
    unit: "m (900 mm)",
    building_type: "Ko'p xonadonli va yakka tartibdagi uylar",
    room_type: "Kvartiraga kirish eshigi",
    condition: "Eshik qanoti 90° ochilganda toza quti oralig'i",
    formula: null,
    calculation_example: "Qurilish o'yig'i (proyom) kamida 1000×2100 mm qilib qoldiriladi. Quti qo'yilgach toza o'tish 900 mm bo'ladi.",
    practical_note: "Kirish eshigidan yirik mebel (muzlatgich, divan) va zambil (nosilka) o'tishi shart.",
    architect_note: "Kirish eshigi qalinligi va mustahkamligi bo'yicha kamida 2-sinf o'g'irlikka chidamlilik talabiga javob berishi lozim.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.9-band",
    source_table: null,
    keywords: ["kirish eshigi", "kvartira eshigi", "eshik kengligi", "входная дверь"],
    status: "AMALDA",
    order_index: 71
  },
  {
    title: "Xonalararo (yotoqxona, zal) ichki eshiklar minimal kengligi",
    slug: "xonalararo-ichki-eshiklar-minimal-kengligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Ichki eshiklar",
    data_type: "norma",
    normative_value: "0.8",
    unit: "m (800 mm)",
    building_type: "Turar joy binolari",
    room_type: "Yashash xonalari va oshxona eshigi",
    condition: "Yotoqxona, zal va ish xonalariga kirishda",
    formula: null,
    calculation_example: "Devordagi o'yiq o'lchami: 900 × 2070 mm (800×2000 mm polotno uchun).",
    practical_note: "Oshxona eshigi uchun ham 800 mm tavsiya etiladi (oshxona jihozlari bemalol kirishi uchun).",
    architect_note: "Eshik ochilganda yorug'lik tugmasini to'sib qo'ymasligi, tugma qulf tomonda 90 sm balandlikda bo'lishi kerak.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.9-band",
    source_table: null,
    keywords: ["ichki eshik", "yotoqxona eshigi", "800 mm", "межкомнатная дверь"],
    status: "AMALDA",
    order_index: 72
  },
  {
    title: "Sanuzel (vanna va hojatxona) eshiklarining minimal kengligi",
    slug: "sanuzel-vanna-hojatxona-eshigi-minimal-kengligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Sanuzel eshiklari",
    data_type: "norma",
    normative_value: "0.6 - 0.7",
    unit: "m (600-700 mm)",
    building_type: "Turar joy binolari",
    room_type: "Vanna, dush, hojatxona",
    condition: "Alohida kichik sanuzellarda toza o'tish eni",
    formula: null,
    calculation_example: "Qurilish devor o'yig'i: 700×2070 mm (600 mm lik polotno uchun) yoki 800×2070 mm (700 mm lik polotno uchun).",
    practical_note: "Kir yuvish mashinasi (chuqurligi 60 sm) sanuzelga kirishi uchun eshik polotnosini 700 mm qilish ancha qulay.",
    architect_note: "Sanuzel eshigi xavfsizlik nuqtai nazaridan FAFAQAT TASHQARIGA (koridor tomon) ochilishi shart (ichkarida odam hushidan ketsa to'sib qolmasligi uchun).",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.9-band",
    source_table: null,
    keywords: ["sanuzel eshigi", "vanna eshigi", "700 mm", "дверь санузел"],
    status: "AMALDA",
    order_index: 73
  },
  {
    title: "Turar joy va jamoat binolari ichki eshiklarining minimal toza balandligi",
    slug: "ichki-eshiklar-minimal-toza-balandligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Standart o'lchamlar",
    data_type: "norma",
    normative_value: "2.0",
    unit: "m (2000 mm)",
    building_type: "Turar joy (2.0 m) | Jamoat binolari (2.1 m)",
    room_type: "Barcha standart eshiklar",
    condition: "Toza pol sathidan toza quti yuqorisigacha",
    formula: null,
    calculation_example: "Qurilish devor o'yig'i toza poldan 2060-2080 mm balandlikda qoldiriladi.",
    practical_note: "Zamonaviy interyerda estetik maqsadlarda 2.20 m yoki shiftgacha yashirin qutili (invisible) eshiklar trendda.",
    architect_note: "Baland eshiklar xonani vizual kengaytiradi, lekin nostandart qimmatroq polotno talab qiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.9-band",
    source_table: null,
    keywords: ["eshik balandligi", "standart eshik", "2000 mm", "высота двери"],
    status: "AMALDA",
    order_index: 74
  },
  {
    title: "Evakuatsiya chiqish eshiklarining ochilish yo'nalishi qoidasi",
    slug: "evakuatsiya-eshiklari-ochilish-yonalishi-qoidasi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Yong'in xavfsizligi",
    data_type: "norma",
    normative_value: "Faqat binodan chiqish yo'nalishi tomon (tashqariga)",
    unit: "qoida",
    building_type: "Barcha bino turlari (15 kishidan ortiq bo'lgan xonalar)",
    room_type: "Evakuatsiya yo'lidagi barcha eshiklar",
    condition: "Yong'in paytida tiqilinchda odamlar bosimi bilan eshik o'z-o'zidan ochilishi uchun",
    formula: null,
    calculation_example: "Istisno: 15 kishigacha bo'lgan xonalar, sanuzellar, omborxonalar va yakka tartibdagi uylar ichki eshiklarida ichkariga ochilishga ruxsat etiladi.",
    practical_note: "Ko'p xonadonli uyda kvartira eshigi umumiy koridorga ochilganda koridorning minimal 1.2 m toza o'tish yo'lini to'sib qo'ymasligi kerak.",
    architect_note: "Ochilish radiusi qo'shni eshik bilan to'qnashmasligi (blokirovka qilmasligi) ta'minlanadi.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.4-band",
    source_table: null,
    keywords: ["eshik ochilishi", "evakuatsiya yo'nalishi", "tashqariga", "открывание дверей"],
    status: "AMALDA",
    order_index: 75
  },
  {
    title: "Evakuatsiya yo'llaridagi eshiklarning minimal toza kengligi",
    slug: "evakuatsiya-yollari-eshigi-minimal-toza-kengligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Yong'in xavfsizligi",
    data_type: "norma",
    normative_value: "0.9 (jamoat) | 0.8 (turar joy)",
    unit: "m",
    building_type: "Jamoat va ko'p qavatli turar joy binolari",
    room_type: "Zinapoyaga chiqish, vestibyul, asosiy chiqish",
    condition: "50 nafardan ortiq odam evakuatsiya qilinadigan yo'llarda",
    formula: null,
    calculation_example: "Katta zallarda eshik kengligi evakuatsiya oqimi hisobiga ko'ra har 100 kishiga kamida 0.6 m hisobida kengaytiriladi.",
    practical_note: "Zinapoya maydonchasiga chiqadigan eshik zinapoya marshining enidan tor bo'lmasligi kerak.",
    architect_note: "Eshik qutilari ostonasiz (porogsiz) qilinadi yoki past profil o'rnatiladi.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.2-band",
    source_table: null,
    keywords: ["evakuatsiya eshigi", "chiqish kengligi", "0.9 metr", "эвакуационный выход"],
    status: "AMALDA",
    order_index: 76
  },
  {
    title: "Nogironlar harakatlanish yo'lidagi eshik ostonasi (porog) maksimal balandligi",
    slug: "nogironlar-uchun-eshik-ostonasi-maksimal-balandligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Inklyuzivlik",
    data_type: "norma",
    normative_value: "ko'pi bilan 14",
    unit: "mm (1.4 sm)",
    building_type: "Barcha jamoat, savdo va turar joy binolari",
    room_type: "Kirish va ichki eshiklar",
    condition: "Nogironlar aravachasi to'siqsiz o'tishi uchun",
    formula: "h_porog <= 14 mm",
    calculation_example: "14 mm dan baland ostonalarning chetlari kamida 1:3 qiyalikdagi faska yoki kichik panduscha bilan qilinishi shart.",
    practical_note: "Balkon va kirish eshiklaridagi baland plastik ostonalar nogironlar va keksalar uchun eng katta to'siqdir.",
    architect_note: "Ideal zamonaviy arxitekturaviy yechim — pol bilan bir sathda joylashgan nol ostonali (zero threshold) avtomatik tushuvchi germetik cho'tka-planka.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.8-band",
    source_table: null,
    keywords: ["ostona", "porog", "14 mm", "nogironlar", "порог двери"],
    status: "AMALDA",
    order_index: 77
  },
  {
    title: "Nogironlar aravachasi o'tadigan eshikning minimal toza kengligi",
    slug: "nogironlar-aravachasi-eshik-minimal-kengligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Inklyuzivlik",
    data_type: "norma",
    normative_value: "0.9",
    unit: "m (900 mm)",
    building_type: "Barcha ijtimoiy va jamoat binolari",
    room_type: "Kirish, sanuzel va xona eshiklari",
    condition: "Aravachaning o'lchami va qo'llar harakati uchun minimal toza tirqish",
    formula: null,
    calculation_example: "Aravacha kengligi 700-750 mm bo'lib, ikki tomondan qo'l bilan g'ildirakni aylantirish uchun kamida 900 mm toza ochilish lozim.",
    practical_note: "Eshik tutqichi 'bosiluvchi' (rychajli) shaklda va 85-100 sm balandlikda o'rnatilishi shart (aylanuvchi dumaloq tutqich man etiladi).",
    architect_note: "Eshik ochilganda devor burchagidan tutqichgacha kamida 30-40 sm masofa qoldiriladi (aravacha yaqinlashishi uchun).",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.7-band",
    source_table: null,
    keywords: ["aravacha eshigi", "inklyuziv eshik", "900 mm", "дверь для колясок"],
    status: "AMALDA",
    order_index: 78
  },
  {
    title: "Ikki qanotli eshiklarda asosiy faol qanotning minimal kengligi",
    slug: "ikki-qanotli-eshik-asosiy-qanot-kengligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Katta eshiklar",
    data_type: "norma",
    normative_value: "kamida 0.9",
    unit: "m (900 mm)",
    building_type: "Jamoat va turar joy binolari",
    room_type: "Bino bosh kirish eshigi, vestibyul",
    condition: "Ikkinchi qanot yopiq / fiksatsiyalangan holatda bo'lganda",
    formula: null,
    calculation_example: "Umumiy o'lchami 1400 mm bo'lgan ikki qanotli eshik: bitta katta faol qanot 900 mm + bitta kichik yarim qanot 500 mm qilib loyihalanadi.",
    practical_note: "Ikkala qanot ham 600 mm dan qilinsa — kundalik foydalanishda odamlar qisilib o'tishga majbur bo'ladi.",
    architect_note: "Evakuatsiya hisobida ikkala qanot ochiladigan mexanizm (shpingalet emas, sinxronizator) qo'llanilishi kerak.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.5-band",
    source_table: null,
    keywords: ["ikki qanotli", "eshik polotnosi", "dvustvorchataya dver", "двупольная дверь"],
    status: "AMALDA",
    order_index: 79
  },
  {
    title: "Eshik ochilish radiusi va mebel joylashuvi ergonomikasi",
    slug: "eshik-ochilish-radiusi-ergonomika-masofasi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Ergonomika va loyihalash",
    data_type: "tavsiya",
    normative_value: "kamida 0.9 - 1.0",
    unit: "m (ochilish sektori)",
    building_type: "Turar joy va ofis xonalari",
    room_type: "Barcha xonalar",
    condition: "Eshik qanoti 90-100° ga to'liq ochiladigan zona",
    formula: "R_zona = Eni_polotno + 10 sm",
    calculation_example: "80 sm lik eshik uchun 90 sm radiusdagi hududga shkaf, stol yoki divan qo'yilmasligi lozim.",
    practical_note: "Eshik tutqichi devorga urilib buzilmasligi uchun polga yoki devorga cheklovchi (dvernoi stopor) o'rnatiladi.",
    architect_note: "Xonaga kirganda eshik devor tomonga ochilishi va darhol xona keng ko'rinishi (perspektiva ochilishi) me'moriy qoidadir.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Amaliy tavsiya",
    source_table: null,
    keywords: ["ochilish radiusi", "ergonomika", "stopor", "радиус открывания"],
    status: "AMALDA",
    order_index: 80
  },
  {
    title: "1 ta yengil avtomobil uchun garaj eshigi (vorota) minimal o'lchamlari",
    slug: "garaj-eshigi-vorota-minimal-olchami",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Maxsus eshiklar va darvozalar",
    data_type: "norma",
    normative_value: "Eni: kamida 2.4 - 2.5 m | Balandligi: kamida 2.0 - 2.2 m",
    unit: "m",
    building_type: "Yakka tartibdagi uylar, kottejlar, avtoturargohlar",
    room_type: "Shaxsiy garaj",
    condition: "Standart yengil avtomobil va SUV (jip) bemalol kirishi uchun",
    formula: null,
    calculation_example: "Mashina eni ko'zgulari bilan 2.1 m bo'lsa, 2.4 m lik darvozada ikki tomondan atigi 15 sm qoladi. Zamonaviy kottejlarda optimal 2.7-3.0 m kenglik olinadi.",
    practical_note: "Seksiyali ko'tariluvchi avtomatik darvozalar uchun shift ostida kamida 25-35 sm bo'shliq (podbalka) bo'lishi shart.",
    architect_note: "Garajga kirish yo'li qiyaligi (pandus) 10-15% dan oshmasligi lozim.",
    source_document_number: "SHNQ 2.07.01-03*",
    source_band: "6.40-band",
    source_table: null,
    keywords: ["garaj eshigi", "vorota", "darvoza", "avtomobil", "гаражные ворота"],
    status: "AMALDA",
    order_index: 81
  },
  {
    title: "Yong'inga qarshi eshiklarning (protivopojarnye dveri) o'tga chidamlilik chegarasi",
    slug: "yonginga-qarshi-eshiklar-otga-chidamlilik-chegarasi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Yong'in xavfsizligi",
    data_type: "norma",
    normative_value: "EI 30 - EI 60",
    unit: "daqiqa (30 - 60 min)",
    building_type: "Ko'p qavatli barcha bino turlari",
    room_type: "Qozonxona, elektrshitovoy, yong'in tamburlari, lift xollari",
    condition: "Yong'in boshqa xonalarga tarqalmasligi uchun ajratilgan zonalarda",
    formula: null,
    calculation_example: "EI 60 belgisi eshik olov va tutunga kamida 60 daqiqa davomida o'z butunligini (E) va issiqlik izolyatsiyasini (I) yo'qotmasligini bildiradi.",
    practical_note: "Yong'inga qarshi eshiklar albatta avtomatik yopuvchi mexanizm (dovodchik) va perimetr bo'ylab termo-kengayuvchi lenta bilan jihozlanadi.",
    architect_note: "Eshik romi va devor orasidagi tirqish faqat maxsus sertifikatlangan yong'inga qarshi pushti peno-germetik bilan to'ldiriladi.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "2.14-band",
    source_table: null,
    keywords: ["protivopojarnaya dver", "EI 60", "EI 30", "dovodchik", "противопожарная дверь"],
    status: "AMALDA",
    order_index: 82
  },
  {
    title: "Balkon va lodjiya eshigining minimal toza o'tish kengligi",
    slug: "balkon-lodjiya-eshigi-minimal-kengligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Fasad va balkon",
    data_type: "norma",
    normative_value: "0.7",
    unit: "m (700 mm)",
    building_type: "Turar joy binolari",
    room_type: "Balkon/lodjiyaga chiqish eshigi",
    condition: "Plastik yoki alyuminiy balkon blokida",
    formula: null,
    calculation_example: "Balkon eshigi odatda deraza bilan bitta blokda qilinadi (deraza-balkon bloki).",
    practical_note: "Balkonga odam qishki kiyimda ham bemalol chiqishi uchun polotno kengligi 75-80 sm bo'lishi ancha qulay.",
    architect_note: "Balkon eshigi pastki ostonasining balandligi xonaga yomg'ir va qor suvi kirmasligi uchun kamida 50-80 mm qilib qoldiriladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.9-band",
    source_table: null,
    keywords: ["balkon eshigi", "lodjiya eshigi", "700 mm", "балконная дверь"],
    status: "AMALDA",
    order_index: 83
  },
  {
    title: "Lift xoli va tambur-shlyuz eshiklarining minimal kengligi",
    slug: "lift-xoli-tambur-shlyuz-eshik-kengligi",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Jamoat va umumiy zonalar",
    data_type: "norma",
    normative_value: "1.2",
    unit: "m (1200 mm)",
    building_type: "Ko'p qavatli turar joy va jamoat binolari",
    room_type: "Lift xoli, tutunga qarshi tambur",
    condition: "Katta odamlar oqimi va yuk tashish yo'lida",
    formula: null,
    calculation_example: "Ikki qanotli (900+300 mm) yoki keng bir qanotli eshik qo'yiladi.",
    practical_note: "Eshiklar shaffof qismi (oynavand vitraj) mustahkam zarbaga chidamli xavfsiz shishadan yasalishi shart.",
    architect_note: "Lift xoli eshiklari tutun o'tkazmaydigan germetik qistirma (uplotnitel) bilan jihozlanadi.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.15-band",
    source_table: null,
    keywords: ["lift xoli", "tambur", "shlyuz", "eshik 1.2 m", "лифтовой холл"],
    status: "AMALDA",
    order_index: 84
  },
  {
    title: "Binoga kirish tamburida eshiklar orasidagi minimal chuqurlik",
    slug: "kirish-tamburi-eshiklar-orasidagi-chuqurlik",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Kirish guruhlari",
    data_type: "norma",
    normative_value: "kamida 1.5 (nogironlar bilan 1.8)",
    unit: "m",
    building_type: "Jamoat va turar joy binolari",
    room_type: "Kirish tamburi (shamol to'sgich)",
    condition: "Ketma-ket ikkita eshik o'rnatilganda",
    formula: "L_tambur = Eni_eshik + 0.5 m (kamida 1.5 m)",
    calculation_example: "Eshik kengligi 90 sm bo'lsa, eshik ochilganda tambur ichida yana kamida 60 sm toza joy qolishi shart.",
    practical_note: "Tambur sovuq shamolni to'sadi va bino ichidagi issiqlikni saqlaydi.",
    architect_note: "Nogironlar aravachasi tambur ichida bemalol to'xtab ikkinchi eshikni ocha olishi uchun chuqurlik kamida 1.8-2.0 m qilib loyihalanadi.",
    source_document_number: "SHNQ 2.01.18-23",
    source_band: "3.5-band",
    source_table: null,
    keywords: ["tambur", "kirish guruhi", "eshiklar orasi", "vetrozashchita", "тамбур"],
    status: "AMALDA",
    order_index: 85
  },
  {
    title: "Shisha eshiklar va to'siqlar uchun xavfsizlik talablari",
    slug: "shisha-eshiklar-xavfsizlik-talablari",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Konstruktiv xavfsizlik",
    data_type: "norma",
    normative_value: "Chiniqtirilgan shisha (kamida 8-10 mm) yoki Tripleks",
    unit: "standart",
    building_type: "Savdo markazlari, ofislar, do'konlar",
    room_type: "To'liq shisha eshik va vitrinalar",
    condition: "Inson tanasi urilganda maydalanib kesib ketmasligi uchun",
    formula: null,
    calculation_example: "Chiniqtirilgan (zakalyonnoe) shisha sinmaydigan to'mtoq mayda bo'laklarga ajraladi.",
    practical_note: "Ko'zi ojiz va e'tiborsiz odamlar urilib ketmasligi uchun shisha ustiga 1.2-1.5 m balandlikda yorqin kontrast belgilar (sariq/oq doira yoki chiziq) yopishtirilishi majburiy.",
    architect_note: "Pol sathidan to'liq shisha eshiklar ostida metall himoya profili ko'zda tutilishi tavsiya etiladi.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "4.18-band",
    source_table: null,
    keywords: ["shisha eshik", "tripleks", "zakalennoe steklo", "xavfsizlik", "стеклянная дверь"],
    status: "AMALDA",
    order_index: 86
  },
  {
    title: "Jamoat binolarida avtomatik surma (razdvijnaya) eshiklar o'lchami",
    slug: "jamoat-binolari-avtomatik-surma-eshiklar-olchami",
    category: "Eshiklar va ochilish joylari",
    subcategory: "Kirish guruhlari",
    data_type: "tavsiya",
    normative_value: "kamida 1.4 - 1.6",
    unit: "m (toza o'tish kengligi)",
    building_type: "Supermarketlar, aeroportlar, shifoxonalar, biznes markazlar",
    room_type: "Bosh kirish portali",
    condition: "Harakat datchigi (radar) bilan avtomatik ochiluvchi tizimlar",
    formula: null,
    calculation_example: "Har bir qanoti 80 sm bo'lgan 2 qanotli surma eshik ochilganda toza 1.5 m o'tish yo'li ochiladi.",
    practical_note: "Elektr uzilganda eshik o'z-o'zidan ochilib qoladigan yoki qo'l bilan oson suriladigan 'antipanika' funksiyasiga ega bo'lishi shart.",
    architect_note: "Suriladigan qanotlar orqasida devorda to'siq bo'lmasligi, mexanizm qutisi uchun shiftda kamida 20 sm zaxira joy ajratiladi.",
    source_document_number: "SHNQ 2.08.02-19",
    source_band: "4.20-band",
    source_table: null,
    keywords: ["avtomat eshik", "surma eshik", "sensor eshik", "раздвижная дверь"],
    status: "AMALDA",
    order_index: 87
  },

  // --- 6. Derazalar va tabiiy yorug'lik (88-105) ---
  {
    title: "Deraza oynasi yorug'lik maydonining pol maydoniga nisbati normasi",
    slug: "deraza-maydonining-pol-maydoniga-nisbati-normasi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Yorug'lik nisbatlari",
    data_type: "norma",
    normative_value: "1:8 dan 1:5.5 gacha (12.5% - 18%)",
    unit: "nisbat (S_oyna : S_pol)",
    building_type: "Turar joy binolari",
    room_type: "Yashash xonalari va oshxona",
    condition: "Sanitariya qoidalariga binoan majburiy minimal chegara",
    formula: "S_oyna >= S_pol / 8",
    calculation_example: "20 m² xona uchun: S_oyna kamida 20 / 8 = 2.5 m² bo'lishi shart. Standart 1.5x1.8 m deraza S=2.7 m² beradi va normaga to'liq javob beradi.",
    practical_note: "Mansarda qavatlarida nishabli tom oynalari uchun bu nisbat 1:10 gacha ruxsat etiladi (qiya tushgan yorug'lik 30% kuchliroq).",
    architect_note: "Deraza maydoni juda katta bo'lsa (1:3 dan ortiq), O'zbekistonning yozgi issiq iqlimida xonaning haddan tashqari qizib ketishi (insolyatsiya haddan oshishi) yuz beradi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.7-band",
    source_table: null,
    keywords: ["deraza maydoni", "yorug'lik nisbati", "1:8", "nisbat", "площадь окон"],
    status: "AMALDA",
    order_index: 88
  },
  {
    title: "16 m² yotoqxona uchun minimal deraza maydoni hisob-kitobi",
    slug: "on-olti-kvadrat-yotoqxona-deraza-hisobi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Hisoblash misollari",
    data_type: "hisoblash",
    normative_value: "kamida 2.0",
    unit: "m²",
    building_type: "Turar joy",
    room_type: "16 m² yotoqxona",
    condition: "Minimal 1:8 nisbat talabi bo'yicha",
    formula: "S_oyna = S_pol / 8 = 16 / 8 = 2.0 m²",
    calculation_example: "Eni 1.4 m, balandligi 1.5 m bo'lgan deraza romi umumiy 2.1 m² yuzani tashkil etadi (plastik profil chegirilganda toza shisha 1.6-1.7 m² bo'ladi).",
    practical_note: "Plastik profil maydoni umumiy romning taxminan 25-30% ini oladi, shuning uchun deraza blokini biroz kattaroq (1.5x1.5 m) tanlash kerak.",
    architect_note: "O'zbekistonda yotoqxona derazalariga quyoshdan himoyalovchi tashqi jalyuzi yoki tonirovka ko'zda tutilishi tavsiya etiladi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.7-band",
    source_table: null,
    keywords: ["yotoqxona derazasi", "16 m2", "hisoblash", "окно в спальне"],
    status: "AMALDA",
    order_index: 89
  },
  {
    title: "20 m² mehmonxona (zal) uchun minimal deraza maydoni hisobi",
    slug: "yigirma-kvadrat-zal-deraza-hisobi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Hisoblash misollari",
    data_type: "hisoblash",
    normative_value: "kamida 2.5 - 3.0",
    unit: "m²",
    building_type: "Turar joy",
    room_type: "20 m² zal",
    condition: "Qulay yashash va estetik ko'rinish uchun",
    formula: "S_oyna = S_pol / 7 = 20 / 7 ≈ 2.85 m²",
    calculation_example: "Ikki tabaqali deraza (1.8 m kenglik, 1.6 m balandlik) = 2.88 m² maydon beradi.",
    practical_note: "Zamonaviy kvartiralarda zal uchun 2.0x1.8 m yoki vitrajli panoramali oyna qo'yish afzal ko'riladi.",
    architect_note: "Katta oyna qo'yilganda ostiga radiator o'rnatish uchun kamida 35-40 sm balandlikdagi parapet qoldirilishi lozim.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.7-band",
    source_table: null,
    keywords: ["zal derazasi", "20 m2", "hisoblash zal", "окно в гостиной"],
    status: "AMALDA",
    order_index: 90
  },
  {
    title: "9 m² oshxona xonasi uchun minimal deraza maydoni hisobi",
    slug: "toqqiz-kvadrat-oshxona-deraza-hisobi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Hisoblash misollari",
    data_type: "hisoblash",
    normative_value: "kamida 1.15",
    unit: "m²",
    building_type: "Turar joy",
    room_type: "9 m² alohida oshxona",
    condition: "Gaz plitasi bo'lgan oshxonada deraza bo'lishi majburiy",
    formula: "S_oyna = S_pol / 8 = 9 / 8 = 1.125 m²",
    calculation_example: "Eni 1.0 m, balandligi 1.4 m bo'lgan deraza = 1.4 m² maydon beradi.",
    practical_note: "Oshxona derazasining kamida bitta tabaqasi fravuga rejimida (tepadan yiqilib) ochilishi shart.",
    architect_note: "Ish stoli deraza tagida joylashsa, deraza tokchasi poldan kamida 90-95 sm balandlikda qilinishi lozim.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.6-band",
    source_table: null,
    keywords: ["oshxona derazasi", "9 m2", "shamollatish", "окно на кухне"],
    status: "AMALDA",
    order_index: 91
  },
  {
    title: "Turar joy xonalarida deraza tokchasining (podokonnik) poldan balandligi",
    slug: "deraza-tokchasi-poldan-balandligi-standarti",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "O'rnatish balandliklari",
    data_type: "tavsiya",
    normative_value: "0.8 - 0.9",
    unit: "m (800 - 900 mm)",
    building_type: "Turar joy binolari",
    room_type: "Yotoqxona, bolalar xonasi, zal",
    condition: "Standart radiator joylashtirish va bolalar xavfsizligi",
    formula: null,
    calculation_example: "Toza poldan 800 mm balandlik radiator (balandligi 500 mm) + radiator osti va ustidagi 100-150 mm havo aylanish tirqishlarini ta'minlaydi.",
    practical_note: "Kreslo yoki stulda o'tirgan odamning ko'rish chizig'i qulay bo'lishi uchun 80 sm ideal parametrdir.",
    architect_note: "Agar tokcha 60 sm dan past bo'lsa, xavfsizlik to'sig'i yoki zarbaga chidamli chiniqtirilgan shisha qo'llanilishi shart.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Standart amaliyot",
    source_table: null,
    keywords: ["podokonnik", "deraza tokchasi", "balandlik", "radiator", "подоконник"],
    status: "AMALDA",
    order_index: 92
  },
  {
    title: "Oshxona ish stoli (countertop) bilan bitta sathdagi deraza tokchasi balandligi",
    slug: "oshxona-ish-stoli-deraza-tokchasi-balandligi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "O'rnatish balandliklari",
    data_type: "tavsiya",
    normative_value: "0.90 - 0.92",
    unit: "m (900 - 920 mm)",
    building_type: "Turar joy, kottejlar",
    room_type: "Oshxona",
    condition: "Oshxona stol usti (stoleshnitsa) deraza tokchasiga tutashganda",
    formula: null,
    calculation_example: "Standart mebel balandligi 85 sm + stoleshnitsa qalinligi 4 sm = 89-90 sm. Qurilishdagi qora devor o'yig'i toza poldan 92-95 sm da qoldiriladi.",
    practical_note: "Agar bu oldindan hisobga olinmasa, mebel o'rnatilganda deraza tabaqasi stoleshnitsaga yoki kran (smesitel)ga urilib ochilmay qoladi.",
    architect_note: "Deraza tagiga rakovina qo'yilsa, maxsus yotuvchi yoki bukiluvchi oshxona smesiteli tanlanadi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Interyer tavsiyasi",
    source_table: null,
    keywords: ["oshxona stoleshnitsa", "podokonnik oshxona", "stoleshnitsa", "подоконник столешница"],
    status: "AMALDA",
    order_index: 93
  },
  {
    title: "Deraza tepa qutisining shiftdan masofasi (pazuxa)",
    slug: "deraza-tepa-qutisi-shiftdan-masofasi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Konstruktiv montaj",
    data_type: "tavsiya",
    normative_value: "0.20 - 0.35",
    unit: "m (200 - 350 mm)",
    building_type: "Barcha bino turlari",
    room_type: "Barcha xonalar",
    condition: "Deraza usti peremichkasi va parda karnizi uchun joy",
    formula: null,
    calculation_example: "Osma gipsokarton shift 10 sm tushganda, parda karnizi o'rnatilgach deraza bemalol ochilishi uchun kamida 20 sm masofa shart.",
    practical_note: "Deraza to'g'ridan-to'g'ri shift tagiga taqalib qolsa, shiftni tushirish va parda osish imkonsiz bo'lib qoladi.",
    architect_note: "Yorug'lik xona chuqurligiga chuqurroq kirishi uchun derazaning yuqori cheti iloji boricha shiftga yaqin bo'lishi yaxshi, lekin karniz hisobga olinishi lozim.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "Konstruktiv tavsiya",
    source_table: null,
    keywords: ["peremichka", "karniz", "shift masofasi", "parda", "откос верхний"],
    status: "AMALDA",
    order_index: 94
  },
  {
    title: "Panoramali polgacha (Fransuzcha) derazalarda majburiy himoya to'sig'i",
    slug: "panoramali-fransuz-deraza-himoya-tosigi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Konstruktiv xavfsizlik",
    data_type: "norma",
    normative_value: "kamida 1.1",
    unit: "m (1100 mm balandlikda)",
    building_type: "Ko'p qavatli turar joy binolari (2-qavat va undan yuqori)",
    room_type: "Polgacha oynali xonalar",
    condition: "Odamlar va bolalar pastga tushib ketishining oldini olish uchun",
    formula: "h_tosik >= 1100 mm",
    calculation_example: "Poldan 1.1 m gacha bo'lgan pastki shisha blok ochilmaydigan (gluhoe) va kamida 10-12 mm zarbaga chidamli tripleks bo'lishi yoki metall tutqich (perila) o'rnatilishi shart.",
    practical_note: "Oddiy oyna qo'yilsa, odam qoqilib derazaga yiqilganda shisha sinib fojia yuz berishi mumkin.",
    architect_note: "Tashqi tomondan yengil metall dekorativ panjara (fransuz balkoni) o'rnatilishi ham me'yorni qoplaydi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.12-band",
    source_table: null,
    keywords: ["fransuz deraza", "panoramali oyna", "himoya to'sig'i", "perila", "французское окно"],
    status: "AMALDA",
    order_index: 95
  },
  {
    title: "Vitraj va katta shishali fasadlarning minimal issiqlik izolyatsiyasi qarshiligi",
    slug: "vitraj-fasad-minimal-issiqlik-qarshiligi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Energiya tejamkorlik",
    data_type: "norma",
    normative_value: "kamida 0.55 - 0.65",
    unit: "m²·°C/Vt",
    building_type: "Jamoat va zamonaviy turar joy binolari",
    room_type: "Vitraj fasad, qishki bog'",
    condition: "Alyuminiy yoki PVX romli panoramali oynavand konstruktsiyalarda",
    formula: null,
    calculation_example: "Oddiy bir kamerali oyna R=0.35 beradi va O'zbekiston sharoitiga to'g'ri kelmaydi. Termoko'priksiz alyuminiy sovuqda muzlab qoladi.",
    practical_note: "Termo-uzilishli (termostavka kamida 24-34 mm) alyuminiy profil va ikki kamerali energiya tejovchi (Low-E) shisha paket talab etiladi.",
    architect_note: "Katta vitrajlar ostida issiq havo pardasini hosil qiluvchi pol ichi konvektorlari (vnutripolny konvektor) loyihalanadi.",
    source_document_number: "QMQ 2.01.04-18",
    source_band: "3.8-band",
    source_table: null,
    keywords: ["vitraj", "fasad", "issiqlik himoyasi", "Low-E", "витраж теплоизоляция"],
    status: "AMALDA",
    order_index: 96
  },
  {
    title: "Turar joy deraza bloklarining normativ issiqlik qarshiligi (R_deraza)",
    slug: "turar-joy-deraza-bloki-issiqlik-qarshiligi-normasi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Energiya tejamkorlik",
    data_type: "norma",
    normative_value: "kamida 0.50 - 0.56",
    unit: "m²·°C/Vt",
    building_type: "Turar joy binolari",
    room_type: "Standart derazalar",
    condition: "O'zbekistonning II iqlimiy mintaqasi (Toshkent, Samarqand va b.)",
    formula: null,
    calculation_example: "Standart 5 kamerali PVX profil (70 mm) + 2 kamerali oyna paketi (32 mm 4-10-4-10-4i) = R ≈ 0.62 m²·°C/Vt (normani to'liq bajaradi).",
    practical_note: "Bitta qatlamli oddiy oyna o'rnatish qat'iyan taqiqlanadi (kondensat oqadi va xona sovib ketadi).",
    architect_note: "Derazaning o'rnatish choki (montajny shov) 3 qatlamli bo'lishi shart: ichidan bug' to'siq, o'rtada penoizolyatsiya, tashqarida bug' o'tkazuvchi diffuzion lenta (PSUL).",
    source_document_number: "QMQ 2.01.04-18",
    source_band: "3.6-band",
    source_table: "3.2-jadval",
    keywords: ["deraza normasi", "issiqlik qarshiligi", "PVX profil", "steklopaket", "сопротивление теплопередаче окна"],
    status: "AMALDA",
    order_index: 97
  },
  {
    title: "Energiya tejovchi ikki kamerali shisha paket (steklopaket) standarti",
    slug: "ikki-kamerali-steklopaket-standarti",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Konstruktiv turlar",
    data_type: "tavsiya",
    normative_value: "32 - 40",
    unit: "mm (formula: 4-10-4-10-4 yoki 4-14Ar-4-14Ar-4i)",
    building_type: "Barcha bino turlari",
    room_type: "Barcha tashqi derazalar",
    condition: "3 qavat shisha va 2 ta havo/argon kamerasi",
    formula: null,
    calculation_example: "Tashqi shisha 4 mm, oraliq ramka 10 mm, o'rta shisha 4 mm, oraliq 10 mm, ichki shisha 4 mm = jami 32 mm qalinlik.",
    practical_note: "Kameraga argon gazi to'ldirilishi va ichki oynaga kumush oksidi purkalganda (Low-E) issiqlikni qaytarish samarasi 40% ga oshadi.",
    architect_note: "Ko'chadan keladigan transport shovqinini yutish uchun tashqi oynani qalinroq (6 mm) qilib asimmetrik shisha paket tanlash akustika qoidasidir.",
    source_document_number: "O'z DSt 3524:2021",
    source_band: "5-bob",
    source_table: null,
    keywords: ["steklopaket", "32 mm", "ikki kamerali", "argon", "Low-E", "стеклопакет"],
    status: "AMALDA",
    order_index: 98
  },
  {
    title: "Quyoshdan himoyalovchi va past emissiyali (Multifunksional) shishalar",
    slug: "quyoshdan-himoyalovchi-multifunksional-shishalar",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Shisha texnologiyalari",
    data_type: "tavsiya",
    normative_value: "Quyosh faktori (g) <= 40% | Yorug'lik o'tkazuvchanlik (LT) >= 60%",
    unit: "% ko'rsatkichlar",
    building_type: "O'zbekistonning barcha quyoshli mintaqalari",
    room_type: "Janubiy va g'arbiy fasad derazalari",
    condition: "Yozda xonani qizib ketishdan asrash va konditsioner xarajatini kamaytirish",
    formula: null,
    calculation_example: "Multifunksional shisha quyoshning infraqizil nurlarini 60% qaytaradi, lekin ko'rinadigan tabiiy yorug'likni 65% o'tkazadi.",
    practical_note: "Oddiy oynadan ko'ra biroz qimmatroq, lekin elektr sarfini 30-40% qisqartirib o'zini 2-3 yilda qoplaydi.",
    architect_note: "Ko'zga xunuk ko'rinadigan qora plyonka yopishtirish o'rniga zavodda purkalgan shaffof neytral multifunksional shisha qo'llash fasad go'zalligini saqlaydi.",
    source_document_number: "QMQ 2.01.04-18",
    source_band: "7.2-band",
    source_table: null,
    keywords: ["multifunksional shisha", "quyoshdan himoya", "solar factor", "мультифункциональное стекло"],
    status: "AMALDA",
    order_index: 99
  },
  {
    title: "Mansarda qiya tom derazalarini (mansardnye okna) o'rnatish balandligi",
    slug: "mansarda-qiya-tom-derazalari-ornatish-balandligi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Maxsus derazalar",
    data_type: "norma",
    normative_value: "Pastki qismi: 0.9 - 1.1 m | Yuqori cheti: 2.0 - 2.2 m",
    unit: "m (poldan balandlik)",
    building_type: "Chordoq va mansardali uylar",
    room_type: "Mansarda yashash xonasi",
    condition: "Tom qiyaligi 15° dan 90° gacha bo'lganda",
    formula: null,
    calculation_example: "Agar deraza 1.4 m dan balandda o'rnatilsa, o'tirgan odam osmondan boshqa hech narsani ko'ra olmaydi. 90-100 sm da o'rnatilsa atrof landshafti ko'rinadi.",
    practical_note: "Qishda qor bosib ochilmay qolmasligi uchun tom darchasi maxsus gidroizolyatsiya okladi bilan o'rnatiladi.",
    architect_note: "Deraza ostidagi ichki otkos vertikal, ustidagi otkos esa polga gorizontal qilinadi — bu yorug'likning butun xonaga keng tarqalishini ta'minlaydi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.8-band",
    source_table: null,
    keywords: ["mansarda oynasi", "velux", "qiya tom derazasi", "мансардное окно"],
    status: "AMALDA",
    order_index: 100
  },
  {
    title: "Yorug'lik qudug'i (svetovoy fonar / zenitny fonar) orqali yoritish",
    slug: "zenit-fonar-yoruglik-qudugi-normasi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Maxsus derazalar",
    data_type: "tavsiya",
    normative_value: "Zenit fonari pol maydonining 5 - 10% ini tashkil qiladi",
    unit: "m²",
    building_type: "Jamoat binolari, savdo markazlari, kottejlar",
    room_type: "Dahliz, markaziy zina xoli, atriumi",
    condition: "Binoning derazasiz ichki qismlariga tepadan tabiiy yorug'lik tushirishda",
    formula: null,
    calculation_example: "Tepadan tushgan yorug'lik vertikal devor derazasiga qaraganda 2-2.5 barobar samaraliroq yoritadi.",
    practical_note: "Zenit fonarlarida tashqi qavat zarbaga chidamli chiniqtirilgan oyna, ichki qavat esa sinib tushmaydigan tripleks shisha bo'lishi majburiy.",
    architect_note: "Kondensat to'planib pastga tommasligi uchun profil ichida drenaj kanallari va qishda qorni erituvchi isitish kabeli ko'zda tutiladi.",
    source_document_number: "QMQ 2.01.05-19",
    source_band: "3.4-band",
    source_table: null,
    keywords: ["zenit fonar", "tom oynasi", "yorug'lik qudug'i", "зенитный фонарь"],
    status: "AMALDA",
    order_index: 101
  },
  {
    title: "Sanuzel va hojatxonalarda tabiiy yorug'lik (deraza) me'yori",
    slug: "sanuzelda-tabiiy-yoruglik-deraza-normasi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Sanuzellar",
    data_type: "tavsiya",
    normative_value: "Majburiy emas, lekin tavsiya etiladi (KEO >= 0.3%)",
    unit: "tavsiya",
    building_type: "Yakka tartibdagi uylar, kottejlar, villa",
    room_type: "Vanna xonasi va sanuzel",
    condition: "Kottejlarda tashqi fasad devorida imkoniyat bo'lganda",
    formula: null,
    calculation_example: "Ko'p qavatli uylarda sanuzel ichki zonada bo'lib derazasiz loyihalanishiga to'liq ruxsat beriladi.",
    practical_note: "Kottejda sanuzel derazasi poldan kamida 1.4-1.6 m balandlikda (intimlik uchun) yoki loyqa (matovoe) shisha bilan qilinadi.",
    architect_note: "Tabiiy deraza sanuzeldagi mog'or va mikroblarni quyosh ultrabinafshasi bilan zararsizlantirishga katta yordam beradi.",
    source_document_number: "SHNQ 2.08.01-24",
    source_band: "3.6-band",
    source_table: null,
    keywords: ["sanuzel derazasi", "vanna oynasi", "matovoe steklo", "окно в ванной"],
    status: "AMALDA",
    order_index: 102
  },
  {
    title: "Zinapoya kataklarida (lestnichnaya kletka) majburiy tabiiy yoritilganlik",
    slug: "zinapoya-kataklarida-tabiiy-yoruglik-normasi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Yong'in evakuatsiyasi",
    data_type: "norma",
    normative_value: "Har bir qavatda tashqi devorda kamida 1.2 m² deraza",
    unit: "m² (har qavatga)",
    building_type: "Ko'p qavatli binolar (L1 toifali zinapoyalar)",
    room_type: "Evakuatsiya zinapoya katagi",
    condition: "Elektr uzilganda yong'in paytida odamlarning xavfsiz tushishi uchun",
    formula: null,
    calculation_example: "Zinapoya katagida har bir qavat maydonchasida ochiladigan oyna bo'lishi shart.",
    practical_note: "O'zbekistonda 9 qavatdan baland uylarda tutun kirmaydigan (N1 toifali - tashqi ochiq o'tish balkoni bor) zinapoyalar qo'llaniladi.",
    architect_note: "Zinapoyadagi derazalar tutunni chiqarish (dimoudalenie) uchun ham xizmat qiladi, shuning uchun ochiladigan mexanizmga ega bo'lishi kerak.",
    source_document_number: "SHNQ 2.01.02-04",
    source_band: "4.12-band",
    source_table: null,
    keywords: ["zinapoya derazasi", "L1 zinapoya", "evakuatsiya yorug'ligi", "окно на лестнице"],
    status: "AMALDA",
    order_index: 103
  },
  {
    title: "Maxfiy / Shaxsiy xonalar uchun loyqa (matoviy) shishalar turlari",
    slug: "shaxsiy-xonalar-loyqa-matoviy-shisha-turlari",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Shisha turlari",
    data_type: "tavsiya",
    normative_value: "Qum bilan ishlov berilgan (peskostruy), kislotali (satina) yoki Smart-shisha",
    unit: "texnologiya",
    building_type: "Barcha bino turlari",
    room_type: "Sanuzel derazalari, dush peregorodkalari, ofis muzokara xonalari",
    condition: "Ichkarini ko'rsatmasdan tabiiy yorug'likni o'tkazish talab qilinganda",
    formula: null,
    calculation_example: "Satina (matelux) shisha 80% yorug'likni o'tkazadi, lekin siluetdan boshqa hech narsani aniq ko'rsatmaydi.",
    practical_note: "Peskostruy qilingan shishada barmoq izi qolishi mumkin; kimyoviy kislotali satina esa silliq va oson yuviladi.",
    architect_note: "Smart-shisha (elektr bilan xiralashuvchi oyna) zamonaviy interyerda tugma bosilganda bir zumda shaffofdan to'liq sutsimon rangga o'tadi.",
    source_document_number: "O'z DSt 3524:2021",
    source_band: "Ilova",
    source_table: null,
    keywords: ["matovoe steklo", "satina", "smart shisha", "loyqa oyna", "матовое стекло"],
    status: "AMALDA",
    order_index: 104
  },
  {
    title: "Deraza tashqi o'yig'i (otkos) chuqurligi va issiqlik ko'prigi oldini olish",
    slug: "deraza-tashqi-otkos-chuqurligi-issiqlik-koprigi",
    category: "Derazalar va tabiiy yorug'lik",
    subcategory: "Montaj qoidalari",
    data_type: "norma",
    normative_value: "Tashqi devor qalinligining 1/3 qismida o'rnatish",
    unit: "sm (odatda devor yuzasidan 10-15 sm ichkarida)",
    building_type: "Barcha bino turlari",
    room_type: "Tashqi devor deraza o'yig'i",
    condition: "Shudring nuqtasi (tochka rosi) shisha paket ichiga tushmasligi uchun",
    formula: null,
    calculation_example: "40 sm lik g'isht devorda deraza tashqi yuzadan 12-14 sm ichkariga o'rnatiladi va tashqi otkos 3-5 sm ekstrudirlangan penopolistirol (XPS) bilan izolyatsiya qilinadi.",
    practical_note: "Agar deraza devorning eng tashqi chetiga taqab o'rnatilsa — qishda ichki otkoslar muzlab, mog'orlab ketadi.",
    architect_note: "Deraza osti tashqi qalay suvoqchasi (otliv) kamida 5% nishablikda va devordan 3-4 sm tashqariga chiqarilib kapelnik bilan bajariladi.",
    source_document_number: "QMQ 2.01.04-18",
    source_band: "5.4-band",
    source_table: null,
    keywords: ["otkos", "deraza montaji", "tochka rosi", "otliv", "откосы оконные"],
    status: "AMALDA",
    order_index: 105
  }
];

module.exports = { SEED_TOPICS_BATCH2 };
